# 02 - Column EDA, cleaning decisions, and CSV export

Notebook này chạy offline từ raw CSV của notebook 01. Thứ tự bắt buộc là: load data gốc -> phân tích từng column/value -> ghi rõ quyết định xử lý -> chạy parser/cleaning rule -> kiểm tra chất lượng -> xuất CSV clean.

Toàn bộ code cleaning nằm trong notebook này; không cần chạy `clean_and_report.py` hay import `utils.clean`.

## Bước 1 - Load raw data

Đây là dữ liệu gốc để phân tích. Raw columns được giữ lại trong output clean để audit về sau.

In [1]:
from pathlib import Path
import json
import re
import unicodedata
from dataclasses import asdict, dataclass, field
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from datetime import datetime, timezone
from typing import Any

import pandas as pd

try:
    import matplotlib.pyplot as plt
    import seaborn as sns
    sns.set_theme(style='whitegrid')
    PLOTTING_AVAILABLE = True
except ImportError:
    PLOTTING_AVAILABLE = False

pd.set_option('display.max_columns', 140)
pd.set_option('display.max_colwidth', 120)

NOTEBOOK_DIR = Path.cwd()
if NOTEBOOK_DIR.name != 'notebook':
    NOTEBOOK_DIR = NOTEBOOK_DIR / 'notebook'
DATA_DIR = NOTEBOOK_DIR / 'data'
RAW_PATH = DATA_DIR / 'suumo_parser_records_raw.csv'
LEGACY_RAW_PATH = DATA_DIR / 'suumo_parser_records_eda.csv'
CLEAN_PATH = DATA_DIR / 'suumo_parser_records_clean.csv'
CURRENT_PATH = DATA_DIR / 'suumo_rentals_current.csv'
STATION_PATH = DATA_DIR / 'suumo_station_access.csv'
CURRENT_STATION_PATH = DATA_DIR / 'suumo_station_access_current.csv'
REPORT_PATH = DATA_DIR / 'suumo_clean_report.json'

source_path = RAW_PATH if RAW_PATH.exists() else LEGACY_RAW_PATH
if not source_path.exists():
    raise FileNotFoundError('Missing raw cache. Run 01_pull_and_cache_overview.ipynb first.')

RAW_STRING_COLUMNS = {
    'data_hash': 'string',
    'phone_number': 'string',
    'shop_property_code': 'string',
    'suumo_property_code': 'string',
}
raw = pd.read_csv(source_path, encoding='utf-8-sig', low_memory=False, dtype=RAW_STRING_COLUMNS)
if source_path != RAW_PATH:
    raw.to_csv(RAW_PATH, index=False, encoding='utf-8-sig')
    print(f'Copied legacy raw cache to {RAW_PATH}')
print(f'Raw rows: {len(raw):,}')
print(f'Raw columns: {len(raw.columns):,}')
print(f'Raw path: {RAW_PATH.resolve()}')

Raw rows: 17,927
Raw columns: 57
Raw path: /Users/hoangvinh/Library/CloudStorage/OneDrive-Personal/Workspace/japan_analysis/notebook/data/suumo_parser_records_raw.csv

## Bước 2 - Profile từng column trước khi xử lý

Bảng này cho biết dtype, missing thật, hidden missing sentinel như `-`/`なし`/`不要`, số giá trị khác nhau, và top values an toàn. Các cột nhạy cảm/free-text bị chặn phần sample nhưng vẫn được đếm để hiểu coverage.

In [2]:
NULL_SENTINELS = {'', '-', '―', '－', 'なし', '無し', '未定'}
MONEY_ZERO_SENTINELS = NULL_SENTINELS | {'不要'}
SENSITIVE_COLUMNS = {
    'address', 'address_normalized', 'phone_number', 'phone_number_normalized',
    'remarks', 'guarantee_company', 'other_initial_costs', 'other_monthly_costs',
    'station_access', 'station_access_normalized', 'batch_file_path',
}

def normalize_text_for_profile(value):
    if value is None or pd.isna(value):
        return None
    normalized = unicodedata.normalize('NFKC', str(value)).strip()
    return normalized or None

def normalize_text_series(series):
    """Chuẩn hóa toàn bộ Series text theo cùng rule với profile raw."""
    return series.map(normalize_text_for_profile).astype('string')

def clean_categorical(series):
    """Chuẩn hóa categorical text và đổi các sentinel thành giá trị thiếu."""
    normalized = normalize_text_series(series)
    return normalized.mask(normalized.isin(NULL_SENTINELS))

def safe_top_values(series, top_n=5):
    if series.name in SENSITIVE_COLUMNS:
        return '[blocked from display]'
    counts = series.map(normalize_text_for_profile).value_counts(dropna=False).head(top_n)
    return '; '.join(f'{idx}: {count}' for idx, count in counts.items())

profile_rows = []
for column in raw.columns:
    normalized = raw[column].map(normalize_text_for_profile)
    profile_rows.append({
        'column': column,
        'dtype': str(raw[column].dtype),
        'non_null': int(raw[column].notna().sum()),
        'missing': int(raw[column].isna().sum()),
        'missing_pct': round(raw[column].isna().mean() * 100, 2),
        'sentinel_count': int(normalized.isin(MONEY_ZERO_SENTINELS).sum()),
        'unique_non_null': int(raw[column].nunique(dropna=True)),
        'top_values': safe_top_values(raw[column]),
    })
raw_column_profile = pd.DataFrame(profile_rows).sort_values(['missing_pct', 'sentinel_count'], ascending=[False, False])
raw_column_profile

,column,dtype,non_null,missing,missing_pct,sentinel_count,unique_non_null,top_values
8,batch_started_loading_at,float64,0,17927,100.00,0,0,None: 17927
9,batch_finished_loading_at,float64,0,17927,100.00,0,0,None: 17927
10,batch_loaded_at,float64,0,17927,100.00,0,0,None: 17927
13,error_message,float64,0,17927,100.00,0,0,None: 17927
14,error_type,float64,0,17927,100.00,0,0,None: 17927
15,image_public_url,float64,0,17927,100.00,0,0,None: 17927
16,image_storage_path,float64,0,17927,100.00,0,0,None: 17927
23,brokerage_fee,object,1515,16412,91.55,1296,17,None: 16412; 不要: 1296; 1.1ヶ月: 93; 0.55ヶ月: 85; 1ヶ月: 16
31,contract_period,object,7922,10005,55.81,0,19,None: 10005; 普通借家 2年: 5909; 普通借家 1年: 1662; 定期借家 2年: 242; 定期借家 1年: 30
21,other_monthly_costs,object,9447,8480,47.30,0,2652,[blocked from display]
20,other_initial_costs,object,9603,8324,46.43,0,2117,[blocked from display]
24,guarantee_company,object,14917,3010,16.79,0,3768,[blocked from display]
26,remarks,object,15958,1969,10.98,0,5400,[blocked from display]
22,energy_efficiency,object,17927,0,0.00,17926,2,-: 17926; ★★★★★★(削減率50%達成): 1
40,insulation_performance,object,17927,0,0.00,17926,2,-: 17926; 6段階/7段階中: 1
44,estimated_utility_cost,object,17927,0,0.00,17926,2,-: 17926; 約10.4万円/年: 1
38,depreciation_text,object,17927,0,0.00,17921,5,-: 17921; 6.6万円: 3; 9.1万円: 1; 5.9万円: 1; 42.9万円: 1
25,guarantee_deposit_text,object,17927,0,0.00,17910,7,-: 17910; 5.9万円: 6; 6.6万円: 4; 2万円: 4; 5万円: 1
39,deposit_text,object,17927,0,0.00,16129,159,-: 16129; 2万円: 95; 5万円: 94; 12.2万円: 88; 10万円: 64
45,key_money_text,object,17927,0,0.00,8485,390,-: 8485; 10万円: 830; 5万円: 249; 15万円: 212; 8万円: 206
49,total_units,object,17927,0,0.00,8283,184,-: 8283; 168戸: 810; 70戸: 650; 36戸: 629; 63戸: 474
41,conditions,object,17927,0,0.00,7572,256,-: 7572; 二人入居可: 1943; ペット相談: 1912; 二人入居可/ペット相談: 1612; 二人入居可/子供可/ペット相談: 649
56,parking,object,17927,0,0.00,6991,507,-: 6991; 敷地内27500円: 655; 敷地内22000円: 638; 敷地内33000円: 633; 敷地内20000円: 468
30,direction,object,17927,0,0.00,1926,9,南: 5020; 西: 3487; 東: 3150; 北: 2058; -: 1926
51,layout_detail,object,17927,0,0.00,1754,1970,-: 1754; 洋6: 862; 洋6 K: 452; K: 416; 洋6.2: 305
37,insurance,object,17927,0,0.00,1696,125,要: 7742; 2万円2年: 2171; 1.8万円2年: 1762; -: 1696; 1.1万円1年: 747
46,management_fee_text,object,17927,0,0.00,966,149,10000円: 3505; 8000円: 2925; 5000円: 1075; -: 966; 7000円: 934
28,shop_property_code,string,17927,0,0.00,668,15991,-: 668; 11201095155300: 68; 112440730: 6; 112736691: 5; 112574008: 5
52,floor_text,object,17927,0,0.00,13,33,3階: 2320; 2階: 2314; 4階: 1942; 6階: 1548; 5階: 1530
55,station_access,object,17927,0,0.00,1,6454,[blocked from display]
0,batch_id,int64,17927,0,0.00,0,180,127: 100; 82: 100; 103: 100; 102: 100; 101: 100
1,source_id,int64,17927,0,0.00,0,1,1: 17927
2,batch_file_path,object,17927,0,0.00,0,180,[blocked from display]
3,batch_status,object,17927,0,0.00,0,1,pending: 17927
4,batch_row_count,int64,17927,0,0.00,0,5,100: 17600; 99: 99; 93: 93; 78: 78; 57: 57
5,batch_inserted_count,int64,17927,0,0.00,0,1,0: 17927
6,batch_failed_count,int64,17927,0,0.00,0,1,0: 17927
7,batch_created_at,object,17927,0,0.00,0,180,2026-08-06 01:04:14.536830+07:00: 100; 2026-08-04 07:18:44.408867+07:00: 100; 2026-08-06 01:00:23.702468+07:00: 100;...
11,suumo_property_code,string,17927,0,0.00,0,17380,100513148551: 3; 100513148570: 3; 100513148629: 3; 100513148636: 3; 100518256547: 3
12,data_hash,string,17927,0,0.00,0,17922,6debac78e843bf2eb8fd600044eea1e2c8e1dece790677aaf365859af585cd33: 2; 445bb040956adab126b3c619f58270662b8890746e99d96...
17,is_valid,bool,17927,0,0.00,0,1,True: 17927
18,parsed_at,object,17927,0,0.00,0,17927,2026-08-09T14:13:53.839837+00:00: 1; 2026-08-05T17:59:37.229312+00:00: 1; 2026-08-05T17:59:37.724780+00:00: 1; 2026-...
19,task_id,int64,17927,0,0.00,0,17927,21525: 1; 9695: 1; 9701: 1; 9700: 1; 9699: 1
27,move_in,object,17927,0,0.00,0,19,即: 10802; 相談: 3114; '26年8月中旬: 946; '26年8月下旬: 794; '26年9月下旬: 653
29,transaction_type,object,17927,0,0.00,0,3,仲介: 17795; 貸主: 102; 代理: 30
32,rent_price_text,object,17927,0,0.00,0,409,7万円: 370; 7.1万円: 327; 7.8万円: 305; 7.3万円: 288; 7.5万円: 286
33,exclusive_area_text,object,17927,0,0.00,0,1298,21.89m2: 568; 25.67m2: 477; 21.09m2: 406; 40.75m2: 381; 21.9m2: 295
34,building_type,object,17927,0,0.00,0,5,マンション: 17056; アパート: 755; 一戸建て: 78; テラス・タウンハウス: 28; その他: 10
35,information_updated_at_text,object,17927,0,0.00,0,19,2026/08/04: 5386; 2026/08/03: 4899; 2026/08/08: 3108; 2026/08/05: 2992; 2026/08/06: 609
36,address,object,17927,0,0.00,0,87,[blocked from display]
42,structure,object,17927,0,0.00,0,9,鉄筋コン: 14132; 鉄骨: 1838; 鉄骨鉄筋: 1107; 木造: 612; 軽量鉄骨: 122
43,next_update_date_text,object,17927,0,0.00,0,21,2026/08/12: 3863; 2026/08/11: 3474; 2026/08/16: 2297; 2026/08/13: 2185; 2026/08/19: 1526
47,building_age_text,object,17927,0,0.00,0,72,新築: 5061; 築2年: 1296; 築3年: 674; 築5年: 610; 築19年: 574
48,built_at_text,object,17927,0,0.00,0,611,2026年7月: 2329; 2026年6月: 1057; 2026年8月: 515; 2026年3月: 432; 2025年2月: 427
50,layout,object,17927,0,0.00,0,21,1K: 7926; 1LDK: 4824; 1DK: 1769; ワンルーム: 1533; 2LDK: 847
53,building_floors,object,17927,0,0.00,0,254,3階/10階建: 488; 7階/10階建: 468; 9階/10階建: 464; 4階/10階建: 462; 2階/10階建: 423
54,phone_number,string,17927,0,0.00,0,296,[blocked from display]

## Bước 3 - Drill-down từng column khi cần

Đổi `COLUMN_TO_INSPECT` để xem phân phối giá trị của một cột cụ thể trước khi quyết định rule. Hàm này cố tình không cho display các cột nhạy cảm/free-text dài.

In [3]:
def inspect_raw_column(column, top_n=30):
    if column in SENSITIVE_COLUMNS:
        raise ValueError(f'{column} is blocked from notebook display.')
    if column not in raw.columns:
        raise KeyError(f'Unknown column: {column}')
    series = raw[column]
    normalized = series.map(normalize_text_for_profile)
    summary = pd.Series({
        'dtype': str(series.dtype),
        'rows': len(series),
        'non_null': int(series.notna().sum()),
        'missing': int(series.isna().sum()),
        'missing_pct': round(series.isna().mean() * 100, 2),
        'sentinel_count': int(normalized.isin(MONEY_ZERO_SENTINELS).sum()),
        'unique_non_null': int(series.nunique(dropna=True)),
    })
    display(summary.to_frame(column))
    display(normalized.value_counts(dropna=False).head(top_n).to_frame('count'))

COLUMN_TO_INSPECT = 'rent_price_text'
inspect_raw_column(COLUMN_TO_INSPECT)

                rent_price_text
dtype                    object
rows                      17927
non_null                  17927
missing                       0
missing_pct                 0.0
sentinel_count                0
unique_non_null             409

                 count
rent_price_text
7万円                370
7.1万円              327
7.8万円              305
7.3万円              288
7.5万円              286
8万円                284
8.4万円              280
6万円                269
7.2万円              263
8.5万円              249
7.6万円              247
5万円                233
6.9万円              224
8.3万円              211
12万円               210
6.5万円              209
8.2万円              205
12.2万円             198
6.8万円              192
11.9万円             192
5.5万円              188
7.9万円              187
11万円               186
7.7万円              185
6.2万円              173
15万円               169
8.1万円              169
7.4万円              161
4万円                160
9万円                158

## Bước 4 - Drop cột không dùng phân tích và giải thích cột còn lại

Bước này tạo một dataframe riêng tên `analysis_raw` để phục vụ EDA và thiết kế warehouse. `raw` gốc không bị overwrite vì các bước cleaning phía sau vẫn cần một số cột lineage như `parsed_at`, `batch_created_at`, và `data_hash` để tạo current/history đúng.

Các cột bị drop ở đây thuộc nhóm all-null, operational metadata, đường dẫn file, hoặc dữ liệu nhạy cảm không nên đưa vào mart phân tích.

In [4]:
DROP_COLUMNS_FOR_ANALYSIS = [
    'batch_started_loading_at',
    'batch_finished_loading_at',
    'batch_loaded_at',
    'error_message',
    'error_type',
    'image_public_url',
    'image_storage_path',
    'batch_file_path',
    'batch_status',
    'batch_row_count',
    'batch_inserted_count',
    'batch_failed_count',
    'batch_created_at',
    # 'data_hash',
    'parsed_at',
    'next_update_date_text',
    'phone_number',
]

DROP_COLUMN_REASONS = {
    'batch_started_loading_at': 'Thời điểm loader bắt đầu load batch; snapshot hiện tại 0% non-null, chỉ là metadata vận hành.',
    'batch_finished_loading_at': 'Thời điểm loader kết thúc load batch; snapshot hiện tại 0% non-null, chỉ là metadata vận hành.',
    'batch_loaded_at': 'Thời điểm batch load thành công; snapshot hiện tại 0% non-null, không dùng phân tích listing.',
    'error_message': 'Thông điệp lỗi parser/loader; snapshot hiện tại 0% non-null.',
    'error_type': 'Loại lỗi parser/loader; snapshot hiện tại 0% non-null.',
    'image_public_url': 'URL ảnh public; snapshot hiện tại 0% non-null.',
    'image_storage_path': 'Đường dẫn ảnh trong object storage; snapshot hiện tại 0% non-null.',
    'batch_file_path': 'Đường dẫn file batch trong MinIO; chỉ cần ở raw/staging để audit, không phải thuộc tính listing.',
    'batch_status': 'Trạng thái batch; current snapshot chỉ có một giá trị nên không phân tích được.',
    'batch_row_count': 'Số dòng trong batch; metadata vận hành, không phải thuộc tính căn hộ.',
    'batch_inserted_count': 'Số record batch đã insert; current snapshot chỉ có một giá trị.',
    'batch_failed_count': 'Số record batch lỗi; current snapshot chỉ có một giá trị.',
    'batch_created_at': 'Timestamp batch raw; phần cleaning phía sau sẽ dùng bản typed batch_created_at_utc thay vì cột raw này.',
    # 'data_hash': 'Hash nội dung để trace thay đổi; hữu ích cho staging/history nhưng không cần trong view EDA wide này.',
    'parsed_at': 'Timestamp parser raw; phần cleaning phía sau sẽ dùng parsed_at_utc thay vì cột raw này.',
    'next_update_date_text': 'Ngày cập nhật tiếp theo dạng raw text; phần cleaning dùng next_update_date typed.',
    'phone_number': 'Số điện thoại liên hệ; dữ liệu nhạy cảm/operational, không đưa vào mart phân tích.',
}

missing_drop_columns = [column for column in DROP_COLUMNS_FOR_ANALYSIS if column not in raw.columns]
if missing_drop_columns:
    raise KeyError(f'Các cột muốn drop không tồn tại trong raw: {missing_drop_columns}')

analysis_raw = raw.drop(columns=DROP_COLUMNS_FOR_ANALYSIS).copy()
print(f'Raw columns before drop: {len(raw.columns)}')
print(f'Dropped columns: {len(DROP_COLUMNS_FOR_ANALYSIS)}')
print(f'Columns after drop: {len(analysis_raw.columns)}')

pd.DataFrame({
    'dropped_column': DROP_COLUMNS_FOR_ANALYSIS,
    'reason_vi': [DROP_COLUMN_REASONS[column] for column in DROP_COLUMNS_FOR_ANALYSIS],
})

Raw columns before drop: 57
Dropped columns: 16
Columns after drop: 41

,dropped_column,reason_vi
0,batch_started_loading_at,"Thời điểm loader bắt đầu load batch; snapshot hiện tại 0% non-null, chỉ là metadata vận hành."
1,batch_finished_loading_at,"Thời điểm loader kết thúc load batch; snapshot hiện tại 0% non-null, chỉ là metadata vận hành."
2,batch_loaded_at,"Thời điểm batch load thành công; snapshot hiện tại 0% non-null, không dùng phân tích listing."
3,error_message,Thông điệp lỗi parser/loader; snapshot hiện tại 0% non-null.
4,error_type,Loại lỗi parser/loader; snapshot hiện tại 0% non-null.
5,image_public_url,URL ảnh public; snapshot hiện tại 0% non-null.
6,image_storage_path,Đường dẫn ảnh trong object storage; snapshot hiện tại 0% non-null.
7,batch_file_path,"Đường dẫn file batch trong MinIO; chỉ cần ở raw/staging để audit, không phải thuộc tính listing."
8,batch_status,Trạng thái batch; current snapshot chỉ có một giá trị nên không phân tích được.
9,batch_row_count,"Số dòng trong batch; metadata vận hành, không phải thuộc tính căn hộ."
10,batch_inserted_count,Số record batch đã insert; current snapshot chỉ có một giá trị.
11,batch_failed_count,Số record batch lỗi; current snapshot chỉ có một giá trị.
12,batch_created_at,Timestamp batch raw; phần cleaning phía sau sẽ dùng bản typed batch_created_at_utc thay vì cột raw này.
13,parsed_at,Timestamp parser raw; phần cleaning phía sau sẽ dùng parsed_at_utc thay vì cột raw này.
14,next_update_date_text,Ngày cập nhật tiếp theo dạng raw text; phần cleaning dùng next_update_date typed.
15,phone_number,"Số điện thoại liên hệ; dữ liệu nhạy cảm/operational, không đưa vào mart phân tích."

In [5]:
COLUMN_GROUP_ORDER = {
    'Lineage và định danh': [
        'task_id', 'batch_id', 'source_id', 'suumo_property_code', 'data_hash', 'is_valid', 'shop_property_code',
    ],
    'Thời gian, trạng thái giao dịch và vào ở': [
        'information_updated_at_text', 'move_in', 'transaction_type', 'contract_period',
    ],
    'Địa điểm và tiếp cận giao thông': [
        'address', 'station_access',
    ],
    'Giá thuê và chi phí hàng tháng': [
        'rent_price_text', 'management_fee_text', 'other_monthly_costs',
    ],
    'Chi phí ban đầu và bảo lãnh': [
        'deposit_text', 'key_money_text', 'guarantee_deposit_text', 'depreciation_text',
        'brokerage_fee', 'other_initial_costs', 'guarantee_company',
    ],
    'Diện tích, layout, tầng và tuổi nhà': [
        'layout', 'layout_detail', 'exclusive_area_text', 'building_age_text', 'built_at_text',
        'floor_text', 'building_floors', 'total_units',
    ],
    'Loại tòa nhà, kết cấu và hướng': [
        'building_type', 'structure', 'direction',
    ],
    'Điều kiện thuê, bảo hiểm và bãi đỗ xe': [
        'conditions', 'insurance', 'parking',
    ],
    'Năng lượng và tiện ích dự kiến': [
        'energy_efficiency', 'insulation_performance', 'estimated_utility_cost',
    ],
    'Free text cần giữ staging/audit': [
        'remarks',
    ],
}

ordered_analysis_columns = [column for columns in COLUMN_GROUP_ORDER.values() for column in columns]
missing_from_order = sorted(set(analysis_raw.columns) - set(ordered_analysis_columns))
unknown_in_order = sorted(set(ordered_analysis_columns) - set(analysis_raw.columns))
if missing_from_order or unknown_in_order:
    raise ValueError({
        'columns_not_documented': missing_from_order,
        'documented_but_not_in_analysis_raw': unknown_in_order,
    })

analysis_raw = analysis_raw[ordered_analysis_columns]
remaining_columns = pd.DataFrame({
    'order': range(1, len(analysis_raw.columns) + 1),
    'column': analysis_raw.columns,
    'non_null': analysis_raw.notna().sum().values,
    'missing_pct': (analysis_raw.isna().mean() * 100).round(2).values,
    'unique_non_null': [analysis_raw[column].nunique(dropna=True) for column in analysis_raw.columns],
})
remaining_columns

    order                       column  non_null  missing_pct  unique_non_null
0       1                      task_id     17927         0.00            17927
1       2                     batch_id     17927         0.00              180
2       3                    source_id     17927         0.00                1
3       4          suumo_property_code     17927         0.00            17380
4       5                    data_hash     17927         0.00            17922
5       6                     is_valid     17927         0.00                1
6       7           shop_property_code     17927         0.00            15991
7       8  information_updated_at_text     17927         0.00               19
8       9                      move_in     17927         0.00               19
9      10             transaction_type     17927         0.00                3
10     11              contract_period      7922        55.81               19
11     12                      address     17927         0.00               87
12     13               station_access     17927         0.00             6454
13     14              rent_price_text     17927         0.00              409
14     15          management_fee_text     17927         0.00              149
15     16          other_monthly_costs      9447        47.30             2652
16     17                 deposit_text     17927         0.00              159
17     18               key_money_text     17927         0.00              390
18     19       guarantee_deposit_text     17927         0.00                7
19     20            depreciation_text     17927         0.00                5
20     21                brokerage_fee      1515        91.55               17
21     22          other_initial_costs      9603        46.43             2117
22     23            guarantee_company     14917        16.79             3768
23     24                       layout     17927         0.00               21
24     25                layout_detail     17927         0.00             1970
25     26          exclusive_area_text     17927         0.00             1298
26     27            building_age_text     17927         0.00               72
27     28                built_at_text     17927         0.00              611
28     29                   floor_text     17927         0.00               33
29     30              building_floors     17927         0.00              254
30     31                  total_units     17927         0.00              184
31     32                building_type     17927         0.00                5
32     33                    structure     17927         0.00                9
33     34                    direction     17927         0.00                9
34     35                   conditions     17927         0.00              256
35     36                    insurance     17927         0.00              125
36     37                      parking     17927         0.00              507
37     38            energy_efficiency     17927         0.00                2
38     39       insulation_performance     17927         0.00                2
39     40       estimated_utility_cost     17927         0.00                2
40     41                      remarks     15958        10.98             5400

In [6]:
COLUMN_EXPLANATIONS = [
    {'group': 'Lineage và định danh', 'column': 'task_id', 'explanation_vi': 'ID kỹ thuật của task crawl/parser. Dùng để join sang bảng station_access và trace record về task nguồn.', 'warehouse_use': 'Giữ trong mart như technical key.'},
    {'group': 'Lineage và định danh', 'column': 'batch_id', 'explanation_vi': 'ID batch chứa parser record. Hữu ích để trace dữ liệu được sinh từ batch nào, nhưng không phải metric kinh doanh.', 'warehouse_use': 'Giữ staging/mart nếu cần lineage.'},
    {'group': 'Lineage và định danh', 'column': 'source_id', 'explanation_vi': 'ID nguồn dữ liệu trong metadata crawler. Snapshot hiện chỉ có SUUMO nên cột này không phân nhóm được dữ liệu.', 'warehouse_use': 'Có thể bỏ khỏi mart nếu chỉ có một source.'},
    {'group': 'Lineage và định danh', 'column': 'suumo_property_code', 'explanation_vi': 'Mã bất động sản do SUUMO cung cấp. Đây là business key quan trọng để deduplicate và lấy bản ghi current mới nhất.', 'warehouse_use': 'Giữ trong mart.'},
    {'group': 'Lineage và định danh', 'column': 'data_hash', 'explanation_vi': 'Hash của nội dung record tại thời điểm crawl/parser. Dùng để trace thay đổi và xác định bản ghi history khác nhau theo từng snapshot.', 'warehouse_use': 'Giữ trong staging/history và có thể giữ trong mart để audit.'},
    {'group': 'Lineage và định danh', 'column': 'is_valid', 'explanation_vi': 'Flag parser record hợp lệ. Loader hiện chỉ đưa record hợp lệ vào warehouse nên current snapshot chỉ có true.', 'warehouse_use': 'Bỏ khỏi mart nếu luôn true; giữ staging để audit.'},
    {'group': 'Lineage và định danh', 'column': 'shop_property_code', 'explanation_vi': 'Mã listing theo cửa hàng môi giới. Cardinality cao, có thể thay đổi theo shop và không ổn định bằng suumo_property_code.', 'warehouse_use': 'Giữ staging/audit; không ưu tiên mart phân tích.'},
    {'group': 'Thời gian, trạng thái giao dịch và vào ở', 'column': 'information_updated_at_text', 'explanation_vi': '情報更新日, ngày SUUMO ghi nhận thông tin listing được cập nhật ở dạng text gốc. Cột này giúp đánh giá độ mới của listing trước khi parse sang kiểu date.', 'warehouse_use': 'Giữ staging; mart dùng information_updated_at kiểu date.'},
    {'group': 'Thời gian, trạng thái giao dịch và vào ở', 'column': 'move_in', 'explanation_vi': 'Thông tin khi nào có thể vào ở. Ví dụ 即 là vào ở ngay, 相談 là cần trao đổi, còn dạng 26年9月初旬 là lịch vào ở dự kiến.', 'warehouse_use': 'Giữ staging; mart dùng move_in_status, move_in_month, move_in_period.'},
    {'group': 'Thời gian, trạng thái giao dịch và vào ở', 'column': 'transaction_type', 'explanation_vi': 'Hình thức giao dịch. Ví dụ 仲介 nghĩa là qua môi giới; ảnh hưởng cách hiểu phí môi giới và kênh giao dịch.', 'warehouse_use': 'Giữ staging; mart dùng transaction_type_clean.'},
    {'group': 'Thời gian, trạng thái giao dịch và vào ở', 'column': 'contract_period', 'explanation_vi': 'Thời hạn và loại hợp đồng thuê. Ví dụ 普通借家 là hợp đồng thuê thông thường, 定期借家 là hợp đồng thuê có kỳ hạn cố định.', 'warehouse_use': 'Giữ staging; mart dùng contract_type, contract_years và contract_months.'},
    {'group': 'Địa điểm và tiếp cận giao thông', 'column': 'address', 'explanation_vi': 'Địa chỉ listing dạng đầy đủ. Giữ raw address để audit và parse thành prefecture, district, municipality, ward, locality, chome; không tự thêm prefecture khi raw không có.', 'warehouse_use': 'Giữ staging/raw; mart dùng các cấp địa lý đã parse tùy mục đích phân tích.'},
    {'group': 'Địa điểm và tiếp cận giao thông', 'column': 'station_access', 'explanation_vi': 'Thông tin tuyến/ga và thời gian đi bộ, bus hoặc xe. Một listing có thể có nhiều dòng ga, nên nên tách thành bảng station_access một-nhiều.', 'warehouse_use': 'Giữ staging; mart dùng primary_station_* và bảng station_access riêng.'},
    {'group': 'Giá thuê và chi phí hàng tháng', 'column': 'rent_price_text', 'explanation_vi': '家賃, tiền thuê nhà hàng tháng ở dạng text gốc như 8.5万円. Đây là giá thuê chính chưa gồm các phí khác.', 'warehouse_use': 'Giữ staging; mart dùng rent_jpy.'},
    {'group': 'Giá thuê và chi phí hàng tháng', 'column': 'management_fee_text', 'explanation_vi': '管理費/共益費, phí quản lý hoặc phí khu vực chung hàng tháng. Ở Nhật khoản này thường trả cùng tiền thuê và cần cộng vào chi phí tháng.', 'warehouse_use': 'Giữ staging; mart dùng management_fee_jpy.'},
    {'group': 'Giá thuê và chi phí hàng tháng', 'column': 'other_monthly_costs', 'explanation_vi': 'DEFERRED/SKIP PARSING: free text trộn phí hàng tháng, phí gia hạn và phí một lần; hiện chỉ giữ để audit.', 'warehouse_use': 'Giữ raw/staging; không parse JPY, không cộng monthly total và không đưa feature định lượng vào mart cho đến khi có rule ổn định.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'deposit_text', 'explanation_vi': '敷金, tiền cọc khi thuê nhà. Thường có khả năng hoàn lại một phần/toàn phần tùy hợp đồng, khác với tiền lễ.', 'warehouse_use': 'Giữ staging; mart dùng deposit_jpy.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'key_money_text', 'explanation_vi': '礼金, tiền lễ hay tiền cảm ơn chủ nhà theo tập quán thuê nhà ở Nhật. Khoản này thường không hoàn lại, nên ảnh hưởng mạnh đến chi phí ban đầu.', 'warehouse_use': 'Giữ staging; mart dùng key_money_jpy.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'guarantee_deposit_text', 'explanation_vi': '保証金, tiền bảo đảm. Tùy listing, khoản này có thể gần giống tiền cọc nhưng vẫn nên tách riêng vì ý nghĩa hợp đồng khác nhau.', 'warehouse_use': 'Giữ staging; mart dùng guarantee_deposit_jpy.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'depreciation_text', 'explanation_vi': '敷引/償却, khoản bị trừ hoặc khấu hao từ tiền cọc/tiền bảo đảm. Thường là phần không hoàn lại khi kết thúc hợp đồng.', 'warehouse_use': 'Giữ staging; mart dùng depreciation_jpy.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'brokerage_fee', 'explanation_vi': '仲介手数料, phí môi giới trả cho công ty môi giới. Có thể ghi bằng yen hoặc theo số tháng tiền thuê, ví dụ 1ヶ月.', 'warehouse_use': 'Giữ staging; mart dùng brokerage_fee_estimated_jpy hoặc các cột parsed.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'other_initial_costs', 'explanation_vi': 'ほか初期費用, các chi phí ban đầu khác như thay khóa, vệ sinh, bảo lãnh. Thường là free text có tổng tiền và chi tiết.', 'warehouse_use': 'Giữ staging; mart dùng other_initial_costs_total_jpy nếu parse được.'},
    {'group': 'Chi phí ban đầu và bảo lãnh', 'column': 'guarantee_company', 'explanation_vi': 'DEFERRED/SKIP PARSING: free text về công ty và điều kiện bảo lãnh có cấu trúc phức tạp; hiện chỉ giữ để audit.', 'warehouse_use': 'Giữ raw/staging; không parse và không đưa thành feature phân tích cho đến khi có rule ổn định.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'layout', 'explanation_vi': '間取り, kiểu bố trí phòng như 1R, 1K, 1DK, 1LDK. Đây là dimension quan trọng để so sánh căn hộ cùng phân khúc.', 'warehouse_use': 'Giữ staging; mart dùng layout_normalized và layout_room_count.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'layout_detail', 'explanation_vi': '間取り詳細, chi tiết loại và kích thước từng không gian theo đơn vị chiếu tatami.', 'warehouse_use': 'Giữ raw; mart dùng feature tổng hợp và bảng layout_spaces một-nhiều, kèm parse status/failure count.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'exclusive_area_text', 'explanation_vi': '専有面積, diện tích sử dụng riêng của căn hộ ở dạng text, ví dụ 25.66m2. Đây là diện tích dùng để tính giá thuê trên m2.', 'warehouse_use': 'Giữ staging; mart dùng exclusive_area_m2.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'building_age_text', 'explanation_vi': '築年数, tuổi nhà dạng text. 新築 nghĩa là nhà mới xây; 築99年以上 nghĩa là ít nhất 99 năm chứ không phải giá trị chính xác.', 'warehouse_use': 'Giữ staging; mart dùng building_age_years và building_age_is_lower_bound.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'built_at_text', 'explanation_vi': '築年月, năm/tháng xây dựng. Nếu source chỉ ghi năm thì phải giữ precision để không hiểu nhầm là tháng 1 thật.', 'warehouse_use': 'Giữ staging; mart dùng built_at và built_at_precision.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'floor_text', 'explanation_vi': '階, tầng của căn hộ. Có thể là một tầng cụ thể như 3階 hoặc range như 1-3階 đối với nhà nhiều tầng.', 'warehouse_use': 'Giữ staging; mart dùng floor_min, floor_max, floor_number.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'building_floors', 'explanation_vi': '階建, tổng số tầng của tòa nhà hoặc mô tả kiểu 3階/10階建. Dùng để biết căn hộ nằm trong tòa cao bao nhiêu tầng.', 'warehouse_use': 'Giữ staging; mart dùng building_total_floors.'},
    {'group': 'Diện tích, layout, tầng và tuổi nhà', 'column': 'total_units', 'explanation_vi': '総戸数, tổng số căn/hộ trong tòa nhà nếu source cung cấp. Có thể phản ánh quy mô tòa nhà.', 'warehouse_use': 'Giữ staging; mart dùng total_units_count.'},
    {'group': 'Loại tòa nhà, kết cấu và hướng', 'column': 'building_type', 'explanation_vi': '建物種別, loại bất động sản như mansion/apartment. Ở Nhật マンション thường là chung cư/kết cấu kiên cố hơn apartment nhỏ.', 'warehouse_use': 'Giữ staging; mart dùng building_type_clean.'},
    {'group': 'Loại tòa nhà, kết cấu và hướng', 'column': 'structure', 'explanation_vi': '構造, kết cấu tòa nhà như RC, SRC, thép, gỗ. Có thể ảnh hưởng chất lượng, cách âm, tuổi thọ và giá thuê.', 'warehouse_use': 'Giữ staging; mart dùng structure_clean.'},
    {'group': 'Loại tòa nhà, kết cấu và hướng', 'column': 'direction', 'explanation_vi': '向き, hướng ban công/cửa chính của căn hộ như Nam, Đông, Tây. Có thể ảnh hưởng ánh sáng và giá.', 'warehouse_use': 'Giữ staging; mart dùng direction_clean.'},
    {'group': 'Điều kiện thuê, bảo hiểm và bãi đỗ xe', 'column': 'conditions', 'explanation_vi': '条件, điều kiện thuê như pet, người ở, loại khách thuê, hoặc các điều kiện đặc biệt. Coverage không đầy đủ nên cần dùng thận trọng.', 'warehouse_use': 'DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa đưa feature conditions vào mart.'},
    {'group': 'Điều kiện thuê, bảo hiểm và bãi đỗ xe', 'column': 'insurance', 'explanation_vi': '損保, bảo hiểm tài sản/hỏa hoạn khi thuê nhà. Có thể ghi cần bảo hiểm, số tiền, và kỳ hạn như 1.8万円2年.', 'warehouse_use': 'Giữ staging; mart dùng insurance_required, insurance_jpy, insurance_period_years.'},
    {'group': 'Điều kiện thuê, bảo hiểm và bãi đỗ xe', 'column': 'parking', 'explanation_vi': '駐車場, thông tin bãi đỗ xe. Có thể ghi trong khuôn viên, gần đó, khoảng cách, giá, kiểu chỗ đỗ và số xe cho phép; dấu - chỉ là source không list parking rõ ràng.', 'warehouse_use': 'Giữ staging; mart dùng parking_listed, parking_location, parking_distance_m, parking_fee_jpy, parking_detail, parking_max_spaces.'},
    {'group': 'Năng lượng và tiện ích dự kiến', 'column': 'energy_efficiency', 'explanation_vi': 'エネルギー消費性能, hiệu suất tiêu thụ năng lượng. Snapshot hiện gần như chỉ có sentinel thiếu dữ liệu nên chưa có giá trị phân tích.', 'warehouse_use': 'DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.'},
    {'group': 'Năng lượng và tiện ích dự kiến', 'column': 'insulation_performance', 'explanation_vi': '断熱性能, hiệu suất cách nhiệt. Snapshot hiện gần như không có dữ liệu thực.', 'warehouse_use': 'DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.'},
    {'group': 'Năng lượng và tiện ích dự kiến', 'column': 'estimated_utility_cost', 'explanation_vi': '目安光熱費, chi phí điện/nước/gas tham khảo. Snapshot hiện gần như không có dữ liệu thực.', 'warehouse_use': 'DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.'},
    {'group': 'Free text cần giữ staging/audit', 'column': 'remarks', 'explanation_vi': '備考, ghi chú tự do của listing. Có thể chứa nhiều thông tin phụ nhưng noise cao và không nên đưa vào mart wide nếu chưa có NLP/rule parse.', 'warehouse_use': 'DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.'},
]

column_dictionary = pd.DataFrame(COLUMN_EXPLANATIONS)
if set(column_dictionary['column']) != set(analysis_raw.columns):
    raise ValueError({
        'missing_explanations': sorted(set(analysis_raw.columns) - set(column_dictionary['column'])),
        'extra_explanations': sorted(set(column_dictionary['column']) - set(analysis_raw.columns)),
    })
column_dictionary['column'] = pd.Categorical(
    column_dictionary['column'], categories=ordered_analysis_columns, ordered=True
)
column_dictionary = column_dictionary.sort_values('column').reset_index(drop=True)
column_dictionary.insert(0, 'order', range(1, len(column_dictionary) + 1))

with pd.option_context(
    'display.max_colwidth', None,
    'display.max_columns', None,
    'display.width', None,
):
    display(column_dictionary)

,order,group,column,explanation_vi,warehouse_use
0,1,Lineage và định danh,task_id,ID kỹ thuật của task crawl/parser. Dùng để join sang bảng station_access và trace record về task nguồn.,Giữ trong mart như technical key.
1,2,Lineage và định danh,batch_id,"ID batch chứa parser record. Hữu ích để trace dữ liệu được sinh từ batch nào, nhưng không phải metric kinh doanh.",Giữ staging/mart nếu cần lineage.
2,3,Lineage và định danh,source_id,ID nguồn dữ liệu trong metadata crawler. Snapshot hiện chỉ có SUUMO nên cột này không phân nhóm được dữ liệu.,Có thể bỏ khỏi mart nếu chỉ có một source.
3,4,Lineage và định danh,suumo_property_code,Mã bất động sản do SUUMO cung cấp. Đây là business key quan trọng để deduplicate và lấy bản ghi current mới nhất.,Giữ trong mart.
4,5,Lineage và định danh,data_hash,Hash của nội dung record tại thời điểm crawl/parser. Dùng để trace thay đổi và xác định bản ghi history khác nhau theo từng snapshot.,Giữ trong staging/history và có thể giữ trong mart để audit.
5,6,Lineage và định danh,is_valid,Flag parser record hợp lệ. Loader hiện chỉ đưa record hợp lệ vào warehouse nên current snapshot chỉ có true.,Bỏ khỏi mart nếu luôn true; giữ staging để audit.
6,7,Lineage và định danh,shop_property_code,"Mã listing theo cửa hàng môi giới. Cardinality cao, có thể thay đổi theo shop và không ổn định bằng suumo_property_code.",Giữ staging/audit; không ưu tiên mart phân tích.
7,8,"Thời gian, trạng thái giao dịch và vào ở",information_updated_at_text,"情報更新日, ngày SUUMO ghi nhận thông tin listing được cập nhật ở dạng text gốc. Cột này giúp đánh giá độ mới của listing trước khi parse sang kiểu date.",Giữ staging; mart dùng information_updated_at kiểu date.
8,9,"Thời gian, trạng thái giao dịch và vào ở",move_in,"Thông tin khi nào có thể vào ở. Ví dụ 即 là vào ở ngay, 相談 là cần trao đổi, còn dạng 26年9月初旬 là lịch vào ở dự kiến.","Giữ staging; mart dùng move_in_status, move_in_month, move_in_period."
9,10,"Thời gian, trạng thái giao dịch và vào ở",transaction_type,Hình thức giao dịch. Ví dụ 仲介 nghĩa là qua môi giới; ảnh hưởng cách hiểu phí môi giới và kênh giao dịch.,Giữ staging; mart dùng transaction_type_clean.
10,11,"Thời gian, trạng thái giao dịch và vào ở",contract_period,"Thời hạn và loại hợp đồng thuê. Ví dụ 普通借家 là hợp đồng thuê thông thường, 定期借家 là hợp đồng thuê có kỳ hạn cố định.","Giữ staging; mart dùng contract_type, contract_years và contract_months."
11,12,Địa điểm và tiếp cận giao thông,address,"Địa chỉ listing dạng đầy đủ. Giữ raw address để audit và parse thành prefecture, district, municipality, ward, locality, chome; không tự thêm prefecture khi raw không có.",Giữ staging/raw; mart dùng các cấp địa lý đã parse tùy mục đích phân tích.
12,13,Địa điểm và tiếp cận giao thông,station_access,"Thông tin tuyến/ga và thời gian đi bộ, bus hoặc xe. Một listing có thể có nhiều dòng ga, nên nên tách thành bảng station_access một-nhiều.",Giữ staging; mart dùng primary_station_* và bảng station_access riêng.
13,14,Giá thuê và chi phí hàng tháng,rent_price_text,"家賃, tiền thuê nhà hàng tháng ở dạng text gốc như 8.5万円. Đây là giá thuê chính chưa gồm các phí khác.",Giữ staging; mart dùng rent_jpy.
14,15,Giá thuê và chi phí hàng tháng,management_fee_text,"管理費/共益費, phí quản lý hoặc phí khu vực chung hàng tháng. Ở Nhật khoản này thường trả cùng tiền thuê và cần cộng vào chi phí tháng.",Giữ staging; mart dùng management_fee_jpy.
15,16,Giá thuê và chi phí hàng tháng,other_monthly_costs,"DEFERRED/SKIP PARSING: free text trộn phí hàng tháng, phí gia hạn và phí một lần; hiện chỉ giữ để audit.","Giữ raw/staging; không parse JPY, không cộng monthly total và không đưa feature định lượng vào mart cho đến khi có rule ổn định."
16,17,Chi phí ban đầu và bảo lãnh,deposit_text,"敷金, tiền cọc khi thuê nhà. Thường có khả năng hoàn lại một phần/toàn phần tùy hợp đồng, khác với tiền lễ.",Giữ staging; mart dùng deposit_jpy.
17,18,Chi phí ban đầu và bảo lãnh,key_money_text,"礼金, tiền lễ hay tiền cảm ơn chủ nhà theo tập quán thuê nhà ở Nhật. Khoản này thường không hoàn lại, nên ảnh hưởng mạnh đến chi phí ban đầu.",Giữ staging; mart dùng key_money_jpy.
18,19,Chi phí ban đầu và bảo lãnh,guarantee_deposit_text,"保証金, tiền bảo đảm. Tùy listing, khoản này có thể gần giống tiền cọc nhưng vẫn nên tách riêng vì ý nghĩa hợp đồng khác nhau.",Giữ staging; mart dùng guarantee_deposit_jpy.
19,20,Chi phí ban đầu và bảo lãnh,depreciation_text,"敷引/償却, khoản bị trừ hoặc khấu hao từ tiền cọc/tiền bảo đảm. Thường là phần không hoàn lại khi kết thúc hợp đồng.",Giữ staging; mart dùng depreciation_jpy.
20,21,Chi phí ban đầu và bảo lãnh,brokerage_fee,"仲介手数料, phí môi giới trả cho công ty môi giới. Có thể ghi bằng yen hoặc theo số tháng tiền thuê, ví dụ 1ヶ月.",Giữ staging; mart dùng brokerage_fee_estimated_jpy hoặc các cột parsed.
21,22,Chi phí ban đầu và bảo lãnh,other_initial_costs,"ほか初期費用, các chi phí ban đầu khác như thay khóa, vệ sinh, bảo lãnh. Thường là free text có tổng tiền và chi tiết.",Giữ staging; mart dùng other_initial_costs_total_jpy nếu parse được.
22,23,Chi phí ban đầu và bảo lãnh,guarantee_company,DEFERRED/SKIP PARSING: free text về công ty và điều kiện bảo lãnh có cấu trúc phức tạp; hiện chỉ giữ để audit.,Giữ raw/staging; không parse và không đưa thành feature phân tích cho đến khi có rule ổn định.
23,24,"Diện tích, layout, tầng và tuổi nhà",layout,"間取り, kiểu bố trí phòng như 1R, 1K, 1DK, 1LDK. Đây là dimension quan trọng để so sánh căn hộ cùng phân khúc.",Giữ staging; mart dùng layout_normalized và layout_room_count.
24,25,"Diện tích, layout, tầng và tuổi nhà",layout_detail,"間取り詳細, chi tiết loại và kích thước từng không gian theo đơn vị chiếu tatami.","Giữ raw; mart dùng feature tổng hợp và bảng layout_spaces một-nhiều, kèm parse status/failure count."
25,26,"Diện tích, layout, tầng và tuổi nhà",exclusive_area_text,"専有面積, diện tích sử dụng riêng của căn hộ ở dạng text, ví dụ 25.66m2. Đây là diện tích dùng để tính giá thuê trên m2.",Giữ staging; mart dùng exclusive_area_m2.
26,27,"Diện tích, layout, tầng và tuổi nhà",building_age_text,"築年数, tuổi nhà dạng text. 新築 nghĩa là nhà mới xây; 築99年以上 nghĩa là ít nhất 99 năm chứ không phải giá trị chính xác.",Giữ staging; mart dùng building_age_years và building_age_is_lower_bound.
27,28,"Diện tích, layout, tầng và tuổi nhà",built_at_text,"築年月, năm/tháng xây dựng. Nếu source chỉ ghi năm thì phải giữ precision để không hiểu nhầm là tháng 1 thật.",Giữ staging; mart dùng built_at và built_at_precision.
28,29,"Diện tích, layout, tầng và tuổi nhà",floor_text,"階, tầng của căn hộ. Có thể là một tầng cụ thể như 3階 hoặc range như 1-3階 đối với nhà nhiều tầng.","Giữ staging; mart dùng floor_min, floor_max, floor_number."
29,30,"Diện tích, layout, tầng và tuổi nhà",building_floors,"階建, tổng số tầng của tòa nhà hoặc mô tả kiểu 3階/10階建. Dùng để biết căn hộ nằm trong tòa cao bao nhiêu tầng.",Giữ staging; mart dùng building_total_floors.
30,31,"Diện tích, layout, tầng và tuổi nhà",total_units,"総戸数, tổng số căn/hộ trong tòa nhà nếu source cung cấp. Có thể phản ánh quy mô tòa nhà.",Giữ staging; mart dùng total_units_count.
31,32,"Loại tòa nhà, kết cấu và hướng",building_type,"建物種別, loại bất động sản như mansion/apartment. Ở Nhật マンション thường là chung cư/kết cấu kiên cố hơn apartment nhỏ.",Giữ staging; mart dùng building_type_clean.
32,33,"Loại tòa nhà, kết cấu và hướng",structure,"構造, kết cấu tòa nhà như RC, SRC, thép, gỗ. Có thể ảnh hưởng chất lượng, cách âm, tuổi thọ và giá thuê.",Giữ staging; mart dùng structure_clean.
33,34,"Loại tòa nhà, kết cấu và hướng",direction,"向き, hướng ban công/cửa chính của căn hộ như Nam, Đông, Tây. Có thể ảnh hưởng ánh sáng và giá.",Giữ staging; mart dùng direction_clean.
34,35,"Điều kiện thuê, bảo hiểm và bãi đỗ xe",conditions,"条件, điều kiện thuê như pet, người ở, loại khách thuê, hoặc các điều kiện đặc biệt. Coverage không đầy đủ nên cần dùng thận trọng.",DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa đưa feature conditions vào mart.
35,36,"Điều kiện thuê, bảo hiểm và bãi đỗ xe",insurance,"損保, bảo hiểm tài sản/hỏa hoạn khi thuê nhà. Có thể ghi cần bảo hiểm, số tiền, và kỳ hạn như 1.8万円2年.","Giữ staging; mart dùng insurance_required, insurance_jpy, insurance_period_years."
36,37,"Điều kiện thuê, bảo hiểm và bãi đỗ xe",parking,"駐車場, thông tin bãi đỗ xe. Có thể ghi trong khuôn viên, gần đó, khoảng cách, giá, kiểu chỗ đỗ và số xe cho phép; dấu - chỉ là source không list parking rõ ràng.","Giữ staging; mart dùng parking_listed, parking_location, parking_distance_m, parking_fee_jpy, parking_detail, parking_max_spaces."
37,38,Năng lượng và tiện ích dự kiến,energy_efficiency,"エネルギー消費性能, hiệu suất tiêu thụ năng lượng. Snapshot hiện gần như chỉ có sentinel thiếu dữ liệu nên chưa có giá trị phân tích.",DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.
38,39,Năng lượng và tiện ích dự kiến,insulation_performance,"断熱性能, hiệu suất cách nhiệt. Snapshot hiện gần như không có dữ liệu thực.",DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.
39,40,Năng lượng và tiện ích dự kiến,estimated_utility_cost,"目安光熱費, chi phí điện/nước/gas tham khảo. Snapshot hiện gần như không có dữ liệu thực.",DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.
40,41,Free text cần giữ staging/audit,remarks,"備考, ghi chú tự do của listing. Có thể chứa nhiều thông tin phụ nhưng noise cao và không nên đưa vào mart wide nếu chưa có NLP/rule parse.",DEFERRED/SKIP: giữ raw để audit; chưa parse và chưa tạo feature cho mart.

## Bước 5 - Kiểm tra và xử lý từng cột

Phần này đi theo đúng danh sách cột còn lại ở `column_dictionary`. Mỗi cột có 3 block riêng:

1. **Kiểm tra raw**: xem null, sentinel, unique, top values hoặc summary an toàn.
2. **Chạy xử lý**: function xử lý riêng của cột đó nằm ngay trong section của cột, rồi ghi output vào `processed_outputs`.
3. **Kiểm tra sau xử lý**: xem coverage, sample output, và phân phối kết quả đã parse.

Không còn function `process_column()` gom tất cả rule ở một chỗ. Bạn có thể chạy từng cột dần dần, kiểm kết quả, rồi yêu cầu sửa đúng section đang sai.

### Hàm hỗ trợ kiểm tra row và xử lý từng cột

Các hàm dưới đây dùng chung cho toàn bộ section cột. Mỗi hàm có comment/docstring tiếng Việt nói rõ dùng để làm gì. Mặc định preview row sẽ dùng cột an toàn, không in địa chỉ đầy đủ, ghi chú dài, số điện thoại, hoặc free text nhạy cảm.

In [7]:

# Các cột này không nên hiển thị raw text mặc định trong notebook vì có thể quá chi tiết,
# chứa nội dung tự do, hoặc không cần thiết cho phân tích nhanh.
SENSITIVE_RAW_COLUMNS = {
    # 'address',
    # 'phone_number',
    # 'remarks',
    # 'guarantee_company',
    # 'other_initial_costs',
    # 'other_monthly_costs',
    # 'station_access',
}

# Bộ cột an toàn dùng khi cần xem một vài row khớp điều kiện mà không lộ text nhạy cảm.
SAFE_ROW_PREVIEW_COLUMNS = [
    'task_id',
    'batch_id',
    'suumo_property_code',
    'rent_price_text',
    'management_fee_text',
    'layout',
    'exclusive_area_text',
    'building_age_text',
    'floor_text',
    'building_type',
    'transaction_type',
]

# Dictionary lưu kết quả xử lý từng cột. Mỗi section column sẽ ghi output vào đây.
processed_outputs = {}

# DEFERRED/SKIP: giữ raw và helper audit nhưng chưa parse các cột này thành feature phân tích.
# Không tự suy diễn điều kiện thuê từ conditions hoặc cộng các số tiền free text khi chưa có rule đáng tin cậy.
DEFERRED_PROCESSING_COLUMNS = {
    'other_monthly_costs',
    'guarantee_company',
    'conditions',
    'energy_efficiency',
    'insulation_performance',
    'estimated_utility_cost',
    'remarks',
}

JPY_VALUE_PATTERN = re.compile(
    r'^(?P<amount>\d[\d,]*(?:\.\d+)?)\s*(?P<unit>万円|円)$'
)


def parse_jpy_value(value, sentinel_as_zero=False):
    """Đổi chuỗi tiền dạng 万円/円 thành số yen nguyên; giá trị không hợp lệ trả về None."""
    normalized = normalize_text_for_profile(value)
    if normalized is None:
        return None
    if normalized in MONEY_ZERO_SENTINELS:
        return 0 if sentinel_as_zero else None

    match = JPY_VALUE_PATTERN.fullmatch(normalized)
    if match is None:
        return None

    try:
        amount = Decimal(match.group('amount').replace(',', ''))
    except InvalidOperation:
        return None

    if match.group('unit') == '万円':
        amount *= Decimal('10000')

    return int(amount.quantize(Decimal('1'), rounding=ROUND_HALF_UP))


MONTH_VALUE_PATTERN = re.compile(
    r'^(?P<months>\d+(?:\.\d+)?)\s*(?:ヶ|ヵ|か|ケ)月$'
)


def parse_month_value(value):
    """Đổi phí dạng số tháng tiền thuê, ví dụ 1.1ヶ月, thành float; dạng khác trả về None."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in MONEY_ZERO_SENTINELS:
        return None

    match = MONTH_VALUE_PATTERN.fullmatch(normalized)
    if match is None:
        return None

    try:
        return float(Decimal(match.group('months')))
    except InvalidOperation:
        return None


INITIAL_COST_TOTAL_PATTERN = re.compile(
    r'^合計(?P<amount>\d+(?:\.\d+)?)万円(?:\(内訳:.*\))?$'
)


def parse_initial_cost_total(value):
    """Lấy tổng chi phí ban đầu từ prefix 合計...万円; không cộng lại các khoản trong 内訳."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in MONEY_ZERO_SENTINELS:
        return None

    match = INITIAL_COST_TOTAL_PATTERN.fullmatch(normalized)
    if match is None:
        return None

    return parse_jpy_value(f"{match.group('amount')}万円")


LAYOUT_PATTERN = re.compile(
    r'^(?P<rooms>\d+)(?P<layout_type>R|K|DK|LK|LDK|SK|SDK|SLDK)$'
)


def parse_layout(value):
    """Chuẩn hóa layout và trả về (layout_normalized, room_count, has_service_room)."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, None, None

    normalized = normalized.upper()
    if normalized == 'ワンルーム':
        return '1R', 1, False

    match = LAYOUT_PATTERN.fullmatch(normalized)
    if match is None:
        return None, None, None

    room_count = int(match.group('rooms'))
    if room_count <= 0:
        return None, None, None

    layout_type = match.group('layout_type')
    return normalized, room_count, 'S' in layout_type


LAYOUT_DETAIL_SPACE_TYPE_MAP = {
    '洋': 'western_room',
    '和': 'japanese_room',
    '納戸': 'service_room',
    'S': 'service_room',
    'K': 'kitchen',
    'DK': 'dining_kitchen',
    'LDK': 'living_dining_kitchen',
    'L': 'living',
    'D': 'dining',
    'LD': 'living_dining',
    'ロフト': 'loft',
}
LAYOUT_DETAIL_LABELS = tuple(
    sorted(LAYOUT_DETAIL_SPACE_TYPE_MAP, key=len, reverse=True)
)
LAYOUT_DETAIL_COMPONENT_PATTERN = re.compile(
    r'(?P<label>'
    + '|'.join(re.escape(label) for label in LAYOUT_DETAIL_LABELS)
    + r')(?P<size>\d+(?:\.\d+)?)?'
)
LAYOUT_DETAIL_NUMBER_PATTERN = re.compile(r'^\d+(?:\.\d+)?$')
LAYOUT_DETAIL_RANGE_PATTERN = re.compile(r'^\d+(?:\.\d+)?-\d+(?:\.\d+)?$')


def _layout_detail_components_from_token(token):
    """Quét một token, kể cả dạng ghép như LD10K2, và giữ phần parse được."""
    components = []
    failures = 0
    position = 0
    while position < len(token):
        match = LAYOUT_DETAIL_COMPONENT_PATTERN.match(token, position)
        if match is None:
            failures += 1
            break
        label = match.group('label')
        size_text = match.group('size')
        components.append({
            'space_label': label,
            'space_type': LAYOUT_DETAIL_SPACE_TYPE_MAP[label],
            'size_jo': float(Decimal(size_text)) if size_text is not None else None,
            'raw_token': match.group(0),
        })
        position = match.end()
    return components, failures


def parse_layout_detail(value):
    """Parse layout_detail thành text sạch, components, trạng thái và số token lỗi."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, [], 'missing', 0

    tokens = normalized.split()
    components = []
    failures = 0
    index = 0
    while index < len(tokens):
        token = tokens[index]
        if token in LAYOUT_DETAIL_SPACE_TYPE_MAP and index + 1 < len(tokens):
            next_token = tokens[index + 1]
            if LAYOUT_DETAIL_NUMBER_PATTERN.fullmatch(next_token):
                components.append({
                    'space_label': token,
                    'space_type': LAYOUT_DETAIL_SPACE_TYPE_MAP[token],
                    'size_jo': float(Decimal(next_token)),
                    'raw_token': f'{token} {next_token}',
                })
                index += 2
                continue
            if LAYOUT_DETAIL_RANGE_PATTERN.fullmatch(next_token):
                components.append({
                    'space_label': token,
                    'space_type': LAYOUT_DETAIL_SPACE_TYPE_MAP[token],
                    'size_jo': None,
                    'raw_token': f'{token} {next_token}',
                })
                failures += 1
                index += 2
                continue

        token_components, token_failures = _layout_detail_components_from_token(token)
        components.extend(token_components)
        failures += token_failures
        index += 1

    if not components:
        status = 'unparsed'
    elif failures:
        status = 'partial'
    else:
        status = 'full'
    return normalized, components, status, failures


def summarize_layout_detail_components(components):
    """Tạo các feature listing-level từ danh sách thành phần layout đã parse."""
    by_label = {}
    for component in components:
        by_label.setdefault(component['space_label'], []).append(component)

    private_sizes = [
        component['size_jo']
        for component in components
        if component['space_type'] in {'western_room', 'japanese_room'}
        and component['size_jo'] is not None
    ]

    if by_label.get('LDK'):
        kitchen_type = 'LDK'
        common_components = by_label['LDK']
    elif by_label.get('LD') and by_label.get('K'):
        kitchen_type = 'LD+K'
        common_components = by_label['LD'] + by_label['K']
    elif by_label.get('DK'):
        kitchen_type = 'DK'
        common_components = by_label['DK']
    elif by_label.get('D') and by_label.get('K'):
        kitchen_type = 'D+K'
        common_components = by_label['D'] + by_label['K']
    elif by_label.get('K'):
        kitchen_type = 'K'
        common_components = by_label['K']
    else:
        kitchen_type = None
        common_components = []

    common_sizes = [
        component['size_jo'] for component in common_components
        if component['size_jo'] is not None
    ]
    loft_sizes = [
        component['size_jo'] for component in components
        if component['space_type'] == 'loft' and component['size_jo'] is not None
    ]
    return {
        'layout_space_count': len(components),
        'western_room_count': sum(c['space_type'] == 'western_room' for c in components),
        'japanese_room_count': sum(c['space_type'] == 'japanese_room' for c in components),
        'service_room_count': sum(c['space_type'] == 'service_room' for c in components),
        'largest_private_room_jo': max(private_sizes) if private_sizes else None,
        'kitchen_type': kitchen_type,
        'kitchen_size_jo': sum(common_sizes) if common_sizes else None,
        'loft_present': any(c['space_type'] == 'loft' for c in components),
        'loft_size_jo': max(loft_sizes) if loft_sizes else None,
    }


AREA_M2_PATTERN = re.compile(r'^(?P<area>\d+(?:\.\d+)?)\s*(?:m2|m²|㎡)$', re.IGNORECASE)


def parse_area_m2(value):
    """Đổi diện tích sử dụng riêng từ text sang m²; giá trị thiếu/sai trả về None."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None

    match = AREA_M2_PATTERN.fullmatch(normalized)
    if match is None:
        return None

    area = Decimal(match.group('area'))
    return float(area) if area > 0 else None


BUILDING_AGE_PATTERN = re.compile(r'^築(?P<years>\d+)年(?P<lower_bound>以上)?$')


def parse_building_age(value):
    """Đổi 新築 thành 0, 築N年/築N年以上 thành N; dạng lạ trả về None."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None
    if normalized == '新築':
        return 0

    match = BUILDING_AGE_PATTERN.fullmatch(normalized)
    return int(match.group('years')) if match else None


BUILT_AT_PATTERN = re.compile(r'^(?P<year>\d{4})年(?:(?P<month>\d{1,2})月)?$')


def parse_year_month(value):
    """Parse 築年月 thành Timestamp; ngày 1 chỉ là mốc lưu trữ, không phải ngày xây dựng thực."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return pd.NaT

    match = BUILT_AT_PATTERN.fullmatch(normalized)
    if match is None:
        return pd.NaT

    year = int(match.group('year'))
    month = int(match.group('month')) if match.group('month') else 1
    if not 1 <= month <= 12:
        return pd.NaT

    try:
        return pd.Timestamp(year=year, month=month, day=1)
    except (ValueError, OverflowError):
        return pd.NaT


FLOOR_RANGE_PATTERN = re.compile(r'^(?P<floor_min>\d+)(?:-(?P<floor_max>\d+))?階$')


def parse_floor_range(value):
    """Parse tầng đơn hoặc khoảng tầng; giá trị thiếu/sai định dạng trả về (None, None)."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, None

    match = FLOOR_RANGE_PATTERN.fullmatch(normalized)
    if match is None:
        return None, None

    floor_min = int(match.group('floor_min'))
    floor_max = int(match.group('floor_max')) if match.group('floor_max') else floor_min
    if floor_min < 1 or floor_max < floor_min:
        return None, None
    return floor_min, floor_max


BUILDING_TOTAL_FLOORS_PATTERN = re.compile(
    r'^(?:(?P<listed_start>\d+)(?:-(?P<listed_end>\d+))?階/)?'
    r'(?:(?:地下\d+地上)|地上)?(?P<total>\d+)階建$'
)


def parse_building_total_floors(value):
    """Lấy số tầng nổi của tòa nhà từ 階建; không cộng tầng hầm."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None
    if normalized == '平屋':
        return 1

    match = BUILDING_TOTAL_FLOORS_PATTERN.fullmatch(normalized)
    if match is None:
        return None
    total = int(match.group('total'))
    if total < 1:
        return None
    if match.group('listed_start') is not None:
        listed_start = int(match.group('listed_start'))
        listed_end = int(match.group('listed_end')) if match.group('listed_end') else listed_start
        if listed_start < 1 or listed_end < listed_start or listed_end > total:
            return None
    return total


TOTAL_UNITS_PATTERN = re.compile(r'^(?P<count>[0-9]+)戸$')


def parse_total_units(value):
    """Đọc 総戸数 dạng số戸; sentinel và giá trị không hợp lệ trả về None."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None
    match = TOTAL_UNITS_PATTERN.fullmatch(normalized)
    if match is None:
        return None
    count = int(match.group('count'))
    return count if count > 0 else None

MOVE_IN_STATUS_IMMEDIATE = 'immediate'
MOVE_IN_STATUS_CONSULTATION = 'consultation'
MOVE_IN_STATUS_SCHEDULED = 'scheduled'
MOVE_IN_STATUS_UNKNOWN = 'unknown'
MOVE_IN_PERIOD_MAP = {
    '上旬': 'early',
    '初旬': 'early',
    '中旬': 'middle',
    '下旬': 'late',
}
MOVE_IN_SCHEDULE_PATTERN = re.compile(
    r"^[`'’‘]?\s*(?P<year>\d{2,4})年\s*(?P<month>\d{1,2})月\s*(?P<period>上旬|初旬|中旬|下旬)?$"
)


def parse_move_in(value):
    """Parse move_in thành (status, YYYY-MM, period), ưu tiên năm ghi trong raw text."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return MOVE_IN_STATUS_UNKNOWN, None, None

    if normalized == '即':
        return MOVE_IN_STATUS_IMMEDIATE, None, None
    if normalized == '相談':
        return MOVE_IN_STATUS_CONSULTATION, None, None

    match = MOVE_IN_SCHEDULE_PATTERN.match(normalized)
    if match is None:
        return MOVE_IN_STATUS_UNKNOWN, None, None

    year_text = match.group('year')
    year = int(year_text)
    if len(year_text) == 2:
        year += 2000

    month = int(match.group('month'))
    if not 1 <= month <= 12:
        return MOVE_IN_STATUS_UNKNOWN, None, None

    period = MOVE_IN_PERIOD_MAP.get(match.group('period'))
    return MOVE_IN_STATUS_SCHEDULED, f'{year:04d}-{month:02d}', period

CONTRACT_TYPE_MAP = {
    '普通借家': 'ordinary',
    '定期借家': 'fixed_term',
}
CONTRACT_DURATION_PATTERN = re.compile(
    r'^(?P<type>普通借家|定期借家)\s*'
    r'(?:(?P<years>\d+)\s*年)?'
    r'(?:(?P<months>\d+)\s*(?:ヶ|か|ケ)?月)?$'
)


def parse_contract(value):
    """Parse hợp đồng theo loại và thời lượng năm/tháng; loại ngày kết thúc sẽ bị loại."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, None, None

    match = CONTRACT_DURATION_PATTERN.match(normalized)
    if match is None or (match.group('years') is None and match.group('months') is None):
        return None, None, None

    contract_type = CONTRACT_TYPE_MAP[match.group('type')]
    contract_years = int(match.group('years')) if match.group('years') else 0
    contract_months = int(match.group('months')) if match.group('months') else 0
    return contract_type, contract_years, contract_months


INSURANCE_AMOUNT_PATTERN = re.compile(
    r'^(?P<amount>[0-9][0-9,]*(?:[.][0-9]+)? *(?:万円|円)) *(?:(?P<years>[0-9]+)年)?$'
)


def parse_insurance(value):
    """Đọc yêu cầu bảo hiểm, số tiền JPY và kỳ hạn năm; không quy đổi thành phí tháng."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, None, None
    if normalized == '不要':
        return False, None, None
    if normalized == '要':
        return True, None, None

    match = INSURANCE_AMOUNT_PATTERN.fullmatch(normalized)
    if match is None:
        return None, None, None
    amount_jpy = parse_jpy_value(match.group('amount'))
    years = int(match.group('years')) if match.group('years') else None
    if amount_jpy is None or amount_jpy <= 0 or (years is not None and years <= 0):
        return None, None, None
    return True, amount_jpy, years


PARKING_LOCATION_FEE_PATTERN = re.compile(
    r'^(?P<location>敷地内|近隣)(?:(?P<distance>[0-9]+)m)?(?P<fee>[0-9][0-9,]*)円$'
)
PARKING_CAPACITY_PATTERN = re.compile(r'^駐(?P<spaces>[23])台可$')
PARKING_DETAIL_VALUES = {
    '平置駐', '屋内駐', '機械式駐', '屋根付駐', '平置屋根付駐',
    'シャッタ付屋内駐', 'リモコンシャッタ付駐',
}


def parse_parking(value):
    """Tách vị trí, khoảng cách, giá, kiểu chỗ đỗ và số xe; thiếu/không hiểu trả về null."""
    empty = (None, None, None, None, None, None)
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return empty

    tokens = normalized.split('/')
    main = tokens[0]
    location, distance_m, fee_jpy, detail, max_spaces = 'unspecified', None, None, None, None
    if main == '付無料':
        fee_jpy = 0
    elif main in PARKING_DETAIL_VALUES:
        detail = main
    elif match := PARKING_CAPACITY_PATTERN.fullmatch(main):
        max_spaces = int(match.group('spaces'))
    else:
        match = PARKING_LOCATION_FEE_PATTERN.fullmatch(main)
        if match is None:
            return empty
        location = 'onsite' if match.group('location') == '敷地内' else 'nearby'
        if match.group('distance') is not None:
            distance_m = int(match.group('distance'))
        if (location == 'onsite' and distance_m is not None) or (distance_m is not None and distance_m <= 0):
            return empty
        fee_jpy = parse_jpy_value(f"{match.group('fee')}円")
        if fee_jpy is None or fee_jpy <= 0:
            return empty

    for token in tokens[1:]:
        if token in PARKING_DETAIL_VALUES and detail is None:
            detail = token
        elif (capacity_match := PARKING_CAPACITY_PATTERN.fullmatch(token)) and max_spaces is None:
            max_spaces = int(capacity_match.group('spaces'))
        else:
            return empty
    return True, location, distance_m, fee_jpy, detail, max_spaces

JAPAN_PREFECTURE_NAMES = (
    '北海道', '青森県', '岩手県', '宮城県', '秋田県', '山形県', '福島県',
    '茨城県', '栃木県', '群馬県', '埼玉県', '千葉県', '東京都', '神奈川県',
    '新潟県', '富山県', '石川県', '福井県', '山梨県', '長野県', '岐阜県',
    '静岡県', '愛知県', '三重県', '滋賀県', '京都府', '大阪府', '兵庫県',
    '奈良県', '和歌山県', '鳥取県', '島根県', '岡山県', '広島県', '山口県',
    '徳島県', '香川県', '愛媛県', '高知県', '福岡県', '佐賀県', '長崎県',
    '熊本県', '大分県', '宮崎県', '鹿児島県', '沖縄県',
)
PREFECTURE_PATTERN = re.compile(
    r'^(?P<prefecture>'
    + '|'.join(re.escape(name) for name in sorted(JAPAN_PREFECTURE_NAMES, key=len, reverse=True))
    + r')'
)
OSAKA_MUNICIPALITY_NAMES = (
    '大阪市', '堺市', '岸和田市', '豊中市', '池田市', '吹田市', '泉大津市',
    '高槻市', '貝塚市', '守口市', '枚方市', '茨木市', '八尾市', '泉佐野市',
    '富田林市', '寝屋川市', '河内長野市', '松原市', '大東市', '和泉市',
    '箕面市', '柏原市', '羽曳野市', '門真市', '摂津市', '高石市', '藤井寺市',
    '東大阪市', '泉南市', '四條畷市', '交野市', '大阪狭山市', '阪南市',
    '島本町', '豊能町', '能勢町', '忠岡町', '熊取町', '田尻町', '岬町',
    '太子町', '河南町', '千早赤阪村',
)
DESIGNATED_CITY_NAMES = {'大阪市', '堺市'}
KANJI_DIGITS = {'一': 1, '二': 2, '三': 3, '四': 4, '五': 5, '六': 6, '七': 7, '八': 8, '九': 9}


def _parse_kanji_integer(value):
    if value in KANJI_DIGITS:
        return KANJI_DIGITS[value]
    if value == '十':
        return 10
    if '十' in value and all(character in KANJI_DIGITS or character == '十' for character in value):
        tens_text, ones_text = value.split('十', 1)
        tens = KANJI_DIGITS.get(tens_text, 1)
        ones = KANJI_DIGITS.get(ones_text, 0)
        return tens * 10 + ones
    return None


def _split_address_locality(value):
    if not value:
        return None, None

    numeric_chome = re.match(r'^(?P<locality>.+?)(?P<chome>\d{1,3})丁目', value)
    if numeric_chome:
        return numeric_chome.group('locality'), int(numeric_chome.group('chome'))

    kanji_chome = re.match(r'^(?P<locality>.+?)(?P<chome>[一二三四五六七八九十]+)丁目', value)
    if kanji_chome:
        chome = _parse_kanji_integer(kanji_chome.group('chome'))
        if chome is not None:
            return kanji_chome.group('locality'), chome

    if not re.search(r'[-－ー]', value):
        suffix_number = re.match(r'^(?P<locality>.*[一-龯ぁ-んァ-ン])(?P<chome>\d{1,3})$', value)
        if suffix_number:
            return suffix_number.group('locality'), int(suffix_number.group('chome'))

    return value, None


def parse_address_parts(value):
    """Parse địa chỉ thành prefecture/district/municipality/ward/locality/chome."""
    normalized = normalize_text_for_profile(value)
    if normalized is None or normalized in NULL_SENTINELS:
        return None, None, None, None, None, None

    remaining = normalized
    prefecture_match = PREFECTURE_PATTERN.match(remaining)
    prefecture = prefecture_match.group('prefecture') if prefecture_match else None
    if prefecture_match:
        remaining = remaining[prefecture_match.end():]

    district_match = re.match(r'^(?P<district>[^市区町村]+郡)', remaining)
    district = district_match.group('district') if district_match else None
    if district_match:
        remaining = remaining[district_match.end():]

    municipality = None
    for candidate in sorted(OSAKA_MUNICIPALITY_NAMES, key=len, reverse=True):
        if remaining.startswith(candidate):
            municipality = candidate
            remaining = remaining[len(candidate):]
            break

    if municipality is None:
        municipality_match = re.match(r'^(?P<municipality>.+?(?:市|町|村))', remaining)
        if municipality_match:
            municipality = municipality_match.group('municipality')
            remaining = remaining[municipality_match.end():]

    ward = None
    if municipality in DESIGNATED_CITY_NAMES:
        ward_match = re.match(r'^(?P<ward>[^市区町村郡]+区)', remaining)
        if ward_match:
            ward = ward_match.group('ward')
            remaining = remaining[ward_match.end():]

    locality, chome = _split_address_locality(remaining)
    return prefecture, district, municipality, ward, locality, chome


STATION_ACCESS_TIME_PATTERN = re.compile(r'(?P<mode>バス|歩|車)\s*(?P<minutes>\d+)\s*分')
STATION_OUTPUT_COLUMNS = [
    'station_parse_failure_count',
    'primary_station_line',
    'primary_station_name',
    'primary_access_mode',
    'primary_total_travel_minutes',
    'station_count',
]


def _parse_station_access_line(line):
    """Parse một dòng route/ga thành một record station chuẩn hóa."""
    normalized = normalize_text_for_profile(line)
    if normalized is None or normalized in NULL_SENTINELS or '/' not in normalized:
        return None

    station_line, access_text = normalized.split('/', 1)
    station_line = station_line.strip()
    time_matches = list(STATION_ACCESS_TIME_PATTERN.finditer(access_text))
    if not station_line or not time_matches:
        return None

    station_name = access_text[:time_matches[0].start()].strip()
    station_name = re.sub(r'駅$', '', station_name).strip()
    if not station_name:
        return None

    total_travel_minutes = sum(int(match.group('minutes')) for match in time_matches)
    modes = [match.group('mode') for match in time_matches]
    if 'バス' in station_line or 'バス' in modes:
        access_mode = 'bus'
    elif '車' in modes:
        access_mode = 'car'
    else:
        access_mode = 'walk'

    return {
        'station_line': station_line,
        'station_name': station_name,
        'access_mode': access_mode,
        'total_travel_minutes': total_travel_minutes,
    }


def _station_rows_for_record(record):
    """Tách station_access theo từng dòng và đếm các dòng parse thất bại."""
    normalized = normalize_text_for_profile(record.get('station_access'))
    if normalized is None or normalized in NULL_SENTINELS:
        return [], 0

    rows = []
    failures = 0
    lines = [line.strip() for line in re.split(r'[\r\n]+', normalized) if line.strip()]
    for access_order, line in enumerate(lines, start=1):
        parsed = _parse_station_access_line(line)
        if parsed is None:
            failures += 1
            continue
        parsed.update({
            'task_id': record.get('task_id'),
            'batch_id': record.get('batch_id'),
            'suumo_property_code': record.get('suumo_property_code'),
            'access_order': access_order,
        })
        rows.append(parsed)
    return rows, failures


def _safe_display_columns(df, display_columns=None, allow_sensitive=False):
    """Dùng để chọn danh sách cột an toàn khi preview row trong notebook."""
    if display_columns is None:
        display_columns = [column for column in SAFE_ROW_PREVIEW_COLUMNS if column in df.columns]
    if allow_sensitive:
        return [column for column in display_columns if column in df.columns]
    return [
        column for column in display_columns
        if column in df.columns and column not in SENSITIVE_RAW_COLUMNS
    ]


def inspect_column_values(df, column, top_n=15):
    """Dùng để kiểm tra một cột trước xử lý: dtype, null, sentinel, unique và top values."""
    if column not in df.columns:
        raise KeyError(f'Không tìm thấy cột: {column}')
    series = df[column]
    normalized = series.map(normalize_text_for_profile)
    summary = pd.Series({
        'dtype': str(series.dtype),
        'rows': len(series),
        'non_null': int(series.notna().sum()),
        'null_count': int(series.isna().sum()),
        'null_pct': round(series.isna().mean() * 100, 2),
        'sentinel_count': int(normalized.isin(MONEY_ZERO_SENTINELS).sum()),
        'unique_non_null': int(series.nunique(dropna=True)),
    })
    display(summary.to_frame(column))

    if column in SENSITIVE_RAW_COLUMNS:
        print(f'Raw top values của {column!r} bị chặn mặc định. Dùng derived output hoặc allow_sensitive=True khi thật sự cần audit.')
        return summary

    display(normalized.value_counts(dropna=False).head(top_n).to_frame('count'))
    return summary


def find_rows_by_value(df, column, value, contains=False, case=False, max_rows=30, display_columns=None, allow_sensitive=False):
    """Dùng để tìm các row có column=value; có thể dùng contains=True để tìm chuỗi chứa value."""
    if column not in df.columns:
        raise KeyError(f'Không tìm thấy cột: {column}')
    series = df[column]
    if contains:
        mask = series.astype('string').str.contains(str(value), case=case, na=False, regex=False)
    else:
        mask = series.map(normalize_text_for_profile) == normalize_text_for_profile(value)

    columns = _safe_display_columns(df, display_columns=display_columns, allow_sensitive=allow_sensitive)
    result = df.loc[mask, columns].head(max_rows).copy()
    print(f'Matched rows: {int(mask.sum()):,}. Showing: {len(result):,}')
    return result


def preview_null_rows(df, column, max_rows=20, display_columns=None, allow_sensitive=False):
    """Dùng để xem sample các row bị null ở một cột, phục vụ kiểm tra missing pattern."""
    if column not in df.columns:
        raise KeyError(f'Không tìm thấy cột: {column}')
    columns = _safe_display_columns(df, display_columns=display_columns, allow_sensitive=allow_sensitive)
    result = df.loc[df[column].isna(), columns].head(max_rows).copy()
    print(f'Null rows: {int(df[column].isna().sum()):,}. Showing: {len(result):,}')
    return result


def _output_summary(output_df):
    """Dùng để tạo bảng coverage nhanh cho dataframe kết quả sau xử lý một cột."""
    return pd.DataFrame({
        'output_column': output_df.columns,
        'non_null': output_df.notna().sum().values,
        'null_pct': (output_df.isna().mean() * 100).round(2).values,
        'unique_non_null': [output_df[column].nunique(dropna=True) for column in output_df.columns],
    })


def check_processed_column(column, top_n=10):
    """Dùng để kiểm tra lại kết quả sau khi đã chạy block xử lý riêng của một cột."""
    if column not in processed_outputs:
        raise KeyError(f'Chưa có output cho {column}. Hãy chạy block xử lý của cột này trước.')
    output_df = processed_outputs[column]
    display(_output_summary(output_df))
    display(output_df.head(10))

    for output_column in output_df.columns:
        series = output_df[output_column]
        if series.nunique(dropna=True) <= 30:
            print(f'\n--- {output_column} top values ---')
            display(series.value_counts(dropna=False).head(top_n).to_frame('count'))
    return output_df

# Ví dụ dùng khi bạn muốn tự drill-down thêm:
# find_rows_by_value(analysis_raw, 'layout', '1K')
# find_rows_by_value(analysis_raw, 'parking', '近隣', contains=True)
# preview_null_rows(analysis_raw, 'contract_period')

### Nhóm: Lineage và định danh

#### `task_id`

ID kỹ thuật của task crawl/parser. Dùng để join sang bảng station_access và trace record về task nguồn.

In [8]:
# Kiểm tra raw column `task_id` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'task_id')

                task_id
dtype             int64
rows              17927
non_null          17927
null_count            0
null_pct            0.0
sentinel_count        0
unique_non_null   17927

         count
task_id
21525        1
9695         1
9701         1
9700         1
9699         1
9698         1
9697         1
9696         1
9694         1
9703         1
9693         1
9692         1
9691         1
9690         1
9689         1

dtype              int64
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null    17927
dtype: object

In [9]:
# Function xử lý riêng cho `task_id`: ép ID task về kiểu Int64 để join/trace ổn định.
def process_task_id():
    output_df = pd.DataFrame({'task_id': pd.array(raw['task_id'], dtype='Int64')})
    processed_outputs['task_id'] = output_df
    return output_df.head(10)

process_task_id()

   task_id
0    21525
1    21526
2    21527
3    21528
4    21529
5    21530
6    21531
7    21532
8    21533
9    21534

In [10]:
# Kiểm tra lại output sau xử lý của column `task_id`.
check_processed_column('task_id')

  output_column  non_null  null_pct  unique_non_null
0       task_id     17927       0.0            17927

   task_id
0    21525
1    21526
2    21527
3    21528
4    21529
5    21530
6    21531
7    21532
8    21533
9    21534

       task_id
0        21525
1        21526
2        21527
3        21528
4        21529
...        ...
17922     3720
17923     3721
17924     3722
17925     3723
17926     3724

[17927 rows x 1 columns]

#### `batch_id`

ID batch chứa parser record. Hữu ích để trace dữ liệu được sinh từ batch nào, nhưng không phải metric kinh doanh.

In [11]:
# Kiểm tra raw column `batch_id` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'batch_id')

                batch_id
dtype              int64
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null      180

          count
batch_id
127         100
82          100
103         100
102         100
101         100
100         100
99          100
98          100
97          100
96          100
95          100
94          100
93          100
92          100
91          100

dtype              int64
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null      180
dtype: object

In [12]:
# Function xử lý riêng cho `batch_id`: ép ID batch về kiểu Int64 để trace batch nguồn.
def process_batch_id():
    output_df = pd.DataFrame({'batch_id': pd.array(raw['batch_id'], dtype='Int64')})
    processed_outputs['batch_id'] = output_df
    return output_df.head(10)

process_batch_id()

   batch_id
0       217
1       217
2       217
3       217
4       217
5       217
6       217
7       217
8       217
9       217

In [13]:
# Kiểm tra lại output sau xử lý của column `batch_id`.
check_processed_column('batch_id')

  output_column  non_null  null_pct  unique_non_null
0      batch_id     17927       0.0              180

   batch_id
0       217
1       217
2       217
3       217
4       217
5       217
6       217
7       217
8       217
9       217

       batch_id
0           217
1           217
2           217
3           217
4           217
...         ...
17922        38
17923        38
17924        38
17925        38
17926        38

[17927 rows x 1 columns]

#### `source_id`

ID nguồn dữ liệu trong metadata crawler. Snapshot hiện chỉ có SUUMO nên cột này không phân nhóm được dữ liệu.

In [14]:
# Kiểm tra raw column `source_id` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'source_id')

                source_id
dtype               int64
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null         1

           count
source_id
1          17927

dtype              int64
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null        1
dtype: object

In [15]:
# Function xử lý riêng cho `source_id`: ép source id về Int64; hiện chỉ có một source SUUMO.
def process_source_id():
    output_df = pd.DataFrame({'source_id': pd.array(raw['source_id'], dtype='Int64')})
    processed_outputs['source_id'] = output_df
    return output_df.head(10)

process_source_id()

   source_id
0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1

In [16]:
# Kiểm tra lại output sau xử lý của column `source_id`.
check_processed_column('source_id')

  output_column  non_null  null_pct  unique_non_null
0     source_id     17927       0.0                1

   source_id
0          1
1          1
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1

--- source_id top values ---

           count
source_id
1          17927

       source_id
0              1
1              1
2              1
3              1
4              1
...          ...
17922          1
17923          1
17924          1
17925          1
17926          1

[17927 rows x 1 columns]

#### `suumo_property_code`

Mã bất động sản do SUUMO cung cấp. Đây là business key quan trọng để deduplicate và lấy bản ghi current mới nhất.

In [17]:
# Kiểm tra raw column `suumo_property_code` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'suumo_property_code')

                suumo_property_code
dtype                        string
rows                          17927
non_null                      17927
null_count                        0
null_pct                        0.0
sentinel_count                    0
unique_non_null               17380

                     count
suumo_property_code
100513148551             3
100513148570             3
100513148629             3
100513148636             3
100518256547             3
100513334320             2
100513334567             2
100513334430             2
100513334296             2
100513334416             2
100513334565             2
100513334437             2
100513334310             2
100513334425             2
100513334297             2

dtype              string
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null     17380
dtype: object

In [18]:
find_rows_by_value(analysis_raw, 'suumo_property_code', '100513148551', display_columns=['task_id', 'batch_id', 'suumo_property_code', 'data_hash'])

Matched rows: 3. Showing: 3

,task_id,batch_id,suumo_property_code,data_hash
457,21189,213,100513148551,d53fac2d33b38924516a211b7e33a3464d3fa6e83171bea5cc962543805f45fe
10207,11354,115,100513148551,c01244502e2736f131f2619f4968b2a2fbc93f7be7485e007e69e0e6a0acfb85
14404,7230,73,100513148551,265c836f5a77a9b5c7c02cb01f320d4771d8574c904adeab44a71b69c9f7ed21

In [19]:
# Function xử lý riêng cho `suumo_property_code`: normalize text để giữ business key ổn định.
def process_suumo_property_code():
    output_df = pd.DataFrame({'suumo_property_code': normalize_text_series(raw['suumo_property_code'])})
    processed_outputs['suumo_property_code'] = output_df
    return output_df.head(10)

process_suumo_property_code()

  suumo_property_code
0        100508459006
1        100508459054
2        100508459047
3        100508459049
4        100508459044
5        100508459056
6        100508459048
7        100508459045
8        100508459033
9        100508459004

In [20]:
# Kiểm tra lại output sau xử lý của column `suumo_property_code`.
check_processed_column('suumo_property_code')

         output_column  non_null  null_pct  unique_non_null
0  suumo_property_code     17927       0.0            17380

  suumo_property_code
0        100508459006
1        100508459054
2        100508459047
3        100508459049
4        100508459044
5        100508459056
6        100508459048
7        100508459045
8        100508459033
9        100508459004

      suumo_property_code
0            100508459006
1            100508459054
2            100508459047
3            100508459049
4            100508459044
...                   ...
17922        100516573404
17923        100516573420
17924        100516573419
17925        100516573398
17926        100516573386

[17927 rows x 1 columns]

#### `is_valid`

Flag parser record hợp lệ. Loader hiện chỉ đưa record hợp lệ vào warehouse nên current snapshot chỉ có true.

In [21]:
# Kiểm tra raw column `is_valid` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'is_valid')

                is_valid
dtype               bool
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null        1

          count
is_valid
True      17927

dtype               bool
rows               17927
non_null           17927
null_count             0
null_pct             0.0
sentinel_count         0
unique_non_null        1
dtype: object

In [22]:
# Function xử lý riêng cho `is_valid`: ép về boolean để kiểm tra loader có lọc invalid đúng không.
def process_is_valid():
    output_df = pd.DataFrame({'is_valid': raw['is_valid'].astype('boolean')})
    processed_outputs['is_valid'] = output_df
    return output_df.head(10)

process_is_valid()

   is_valid
0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True

In [23]:
# Kiểm tra lại output sau xử lý của column `is_valid`.
check_processed_column('is_valid')

  output_column  non_null  null_pct  unique_non_null
0      is_valid     17927       0.0                1

   is_valid
0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8      True
9      True

--- is_valid top values ---

          count
is_valid
True      17927

       is_valid
0          True
1          True
2          True
3          True
4          True
...         ...
17922      True
17923      True
17924      True
17925      True
17926      True

[17927 rows x 1 columns]

#### `shop_property_code`

Mã listing theo cửa hàng môi giới. Cardinality cao, có thể thay đổi theo shop và không ổn định bằng suumo_property_code.

In [24]:
# Kiểm tra raw column `shop_property_code` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'shop_property_code')

                shop_property_code
dtype                       string
rows                         17927
non_null                     17927
null_count                       0
null_pct                       0.0
sentinel_count                 668
unique_non_null              15991

                    count
shop_property_code
-                     668
11201095155300         68
112440730               6
112736691               5
112574008               5
112270540               5
112655637               5
112639836               5
324147                  5
112440731               4
112270446               4
325316                  4
96635756                4
112655456               4
4897316                 4

dtype              string
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count        668
unique_non_null     15991
dtype: object

In [25]:
# Function xử lý riêng cho `shop_property_code`: normalize mã listing của shop và đổi sentinel thành null.
def process_shop_property_code():
    output_df = pd.DataFrame({'shop_property_code_clean': clean_categorical(raw['shop_property_code'])})
    processed_outputs['shop_property_code'] = output_df
    return output_df.head(10)

process_shop_property_code()

  shop_property_code_clean
0                112417146
1                112417154
2                112417156
3                112417148
4                112417157
5                112417149
6                112417150
7                112417158
8                112417151
9                112417159

In [26]:
# Kiểm tra lại output sau xử lý của column `shop_property_code`.
check_processed_column('shop_property_code')

              output_column  non_null  null_pct  unique_non_null
0  shop_property_code_clean     17259      3.73            15990

  shop_property_code_clean
0                112417146
1                112417154
2                112417156
3                112417148
4                112417157
5                112417149
6                112417150
7                112417158
8                112417151
9                112417159

      shop_property_code_clean
0                    112417146
1                    112417154
2                    112417156
3                    112417148
4                    112417157
...                        ...
17922                  1059960
17923                  1059946
17924                  1059947
17925                  1059964
17926                  1059929

[17927 rows x 1 columns]

### Nhóm: Thời gian, trạng thái giao dịch và vào ở

#### `information_updated_at_text`

Ngày SUUMO ghi nhận thông tin listing được cập nhật, ở dạng text gốc. Sau cleaning nên dùng information_updated_at kiểu date.

In [27]:
# Kiểm tra raw column `information_updated_at_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'information_updated_at_text')

                information_updated_at_text
dtype                                object
rows                                  17927
non_null                              17927
null_count                                0
null_pct                                0.0
sentinel_count                            0
unique_non_null                          19

                             count
information_updated_at_text
2026/08/04                    5386
2026/08/03                    4899
2026/08/08                    3108
2026/08/05                    2992
2026/08/06                     609
2026/08/09                     476
2026/07/30                     121
2026/07/31                     117
2026/08/02                      63
2026/08/01                      57
2026/07/29                      23
2026/08/07                      22
2026/07/27                      16
2026/07/28                      13
2026/07/22                      12

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null        19
dtype: object

In [28]:
# Function xử lý riêng cho `information_updated_at_text`: parse ngày cập nhật thông tin từ text sang date.
def process_information_updated_at_text():
    output_df = pd.DataFrame({
        'information_updated_at': pd.to_datetime(raw['information_updated_at_text'], format='%Y/%m/%d', errors='coerce')
    })
    processed_outputs['information_updated_at_text'] = output_df
    return output_df.head(10)

process_information_updated_at_text()

  information_updated_at
0             2026-08-09
1             2026-08-09
2             2026-08-09
3             2026-08-09
4             2026-08-09
5             2026-08-09
6             2026-08-09
7             2026-08-09
8             2026-08-09
9             2026-08-09

In [29]:
# Kiểm tra lại output sau xử lý của column `information_updated_at_text`.
check_processed_column('information_updated_at_text')

            output_column  non_null  null_pct  unique_non_null
0  information_updated_at     17927       0.0               19

  information_updated_at
0             2026-08-09
1             2026-08-09
2             2026-08-09
3             2026-08-09
4             2026-08-09
5             2026-08-09
6             2026-08-09
7             2026-08-09
8             2026-08-09
9             2026-08-09

--- information_updated_at top values ---

                        count
information_updated_at
2026-08-04               5386
2026-08-03               4899
2026-08-08               3108
2026-08-05               2992
2026-08-06                609
2026-08-09                476
2026-07-30                121
2026-07-31                117
2026-08-02                 63
2026-08-01                 57

      information_updated_at
0                 2026-08-09
1                 2026-08-09
2                 2026-08-09
3                 2026-08-09
4                 2026-08-09
...                      ...
17922             2026-08-03
17923             2026-08-03
17924             2026-08-03
17925             2026-08-03
17926             2026-08-03

[17927 rows x 1 columns]

#### `move_in`

Thông tin khi nào có thể vào ở. Ví dụ 即 là vào ở ngay, 相談 là cần trao đổi, còn dạng 26年9月初旬 là lịch vào ở dự kiến.

In [30]:
# Kiểm tra raw column `move_in` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'move_in')

                move_in
dtype            object
rows              17927
non_null          17927
null_count            0
null_pct            0.0
sentinel_count        0
unique_non_null      19

           count
move_in
即          10802
相談          3114
'26年8月中旬     946
'26年8月下旬     794
'26年9月下旬     653
'26年8月上旬     568
'26年9月中旬     366
'26年9月上旬     337
'26年10月下旬    181
'26年10月上旬     73
'26年10月中旬     57
'26年11月下旬     18
'26年11月上旬      5
'26年11月中旬      4
'26年12月上旬      4

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null        19
dtype: object

In [31]:
# Function xử lý riêng cho `move_in`: đọc năm/tháng trực tiếp từ raw text và tách status/period.
def process_move_in():
    parsed = pd.Series([
        parse_move_in(value)
        for value in raw['move_in']
    ], index=raw.index)
    output_df = pd.DataFrame({
        'move_in_status': parsed.map(lambda value: value[0]).astype('string'),
        'move_in_month': parsed.map(lambda value: value[1]).astype('string'),
        'move_in_period': parsed.map(lambda value: value[2]).astype('string'),
    })
    processed_outputs['move_in'] = output_df
    return output_df.head(10)

process_move_in()

  move_in_status move_in_month move_in_period
0      immediate          <NA>           <NA>
1      immediate          <NA>           <NA>
2      immediate          <NA>           <NA>
3      immediate          <NA>           <NA>
4      immediate          <NA>           <NA>
5      immediate          <NA>           <NA>
6      immediate          <NA>           <NA>
7      immediate          <NA>           <NA>
8      immediate          <NA>           <NA>
9      immediate          <NA>           <NA>

In [32]:
# Kiểm tra lại output sau xử lý của column `move_in`.
check_processed_column('move_in')

    output_column  non_null  null_pct  unique_non_null
0  move_in_status     17927      0.00                4
1   move_in_month      4010     77.63                7
2  move_in_period      4010     77.63                3

  move_in_status move_in_month move_in_period
0      immediate          <NA>           <NA>
1      immediate          <NA>           <NA>
2      immediate          <NA>           <NA>
3      immediate          <NA>           <NA>
4      immediate          <NA>           <NA>
5      immediate          <NA>           <NA>
6      immediate          <NA>           <NA>
7      immediate          <NA>           <NA>
8      immediate          <NA>           <NA>
9      immediate          <NA>           <NA>

--- move_in_status top values ---

                count
move_in_status
immediate       10802
scheduled        4010
consultation     3114
unknown             1

--- move_in_month top values ---

               count
move_in_month
<NA>           13917
2026-08         2308
2026-09         1358
2026-10          311
2026-11           27
2026-12            4
2027-01            1
2028-08            1

--- move_in_period top values ---

                count
move_in_period
<NA>            13917
late             1647
middle           1373
early             990

      move_in_status move_in_month move_in_period
0          immediate          <NA>           <NA>
1          immediate          <NA>           <NA>
2          immediate          <NA>           <NA>
3          immediate          <NA>           <NA>
4          immediate          <NA>           <NA>
...              ...           ...            ...
17922      immediate          <NA>           <NA>
17923      immediate          <NA>           <NA>
17924      immediate          <NA>           <NA>
17925      immediate          <NA>           <NA>
17926      immediate          <NA>           <NA>

[17927 rows x 3 columns]

#### `transaction_type`

Hình thức giao dịch. Ví dụ 仲介 nghĩa là qua môi giới; ảnh hưởng cách hiểu phí môi giới và kênh giao dịch.

In [33]:
# Kiểm tra raw column `transaction_type` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'transaction_type')

                transaction_type
dtype                     object
rows                       17927
non_null                   17927
null_count                     0
null_pct                     0.0
sentinel_count                 0
unique_non_null                3

                  count
transaction_type
仲介                17795
貸主                  102
代理                   30

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null         3
dtype: object

In [34]:
# Function xử lý riêng cho `transaction_type`: normalize hình thức giao dịch như 仲介 và đổi sentinel thành null.
def process_transaction_type():
    output_df = pd.DataFrame({'transaction_type_clean': clean_categorical(raw['transaction_type'])})
    processed_outputs['transaction_type'] = output_df
    return output_df.head(10)

process_transaction_type()

  transaction_type_clean
0                     仲介
1                     仲介
2                     仲介
3                     仲介
4                     仲介
5                     仲介
6                     仲介
7                     仲介
8                     仲介
9                     仲介

In [35]:
# Kiểm tra lại output sau xử lý của column `transaction_type`.
check_processed_column('transaction_type')

            output_column  non_null  null_pct  unique_non_null
0  transaction_type_clean     17927       0.0                3

  transaction_type_clean
0                     仲介
1                     仲介
2                     仲介
3                     仲介
4                     仲介
5                     仲介
6                     仲介
7                     仲介
8                     仲介
9                     仲介

--- transaction_type_clean top values ---

                        count
transaction_type_clean
仲介                      17795
貸主                        102
代理                         30

      transaction_type_clean
0                         仲介
1                         仲介
2                         仲介
3                         仲介
4                         仲介
...                      ...
17922                     仲介
17923                     仲介
17924                     仲介
17925                     仲介
17926                     仲介

[17927 rows x 1 columns]

#### `contract_period`

Thời hạn và loại hợp đồng thuê. Ví dụ 普通借家 là hợp đồng thuê thông thường, 定期借家 là hợp đồng thuê có kỳ hạn cố định.

In [36]:
# Kiểm tra raw column `contract_period` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'contract_period')

                contract_period
dtype                    object
rows                      17927
non_null                   7922
null_count                10005
null_pct                  55.81
sentinel_count                0
unique_non_null              19

                  count
contract_period
None              10005
普通借家 2年            5909
普通借家 1年            1662
定期借家 2年             242
定期借家 1年              30
定期借家 5年              28
定期借家 3年              11
定期借家 10年              7
普通借家 2ヶ月              7
普通借家 3年               6
定期借家 8年               4
定期借家 6年               3
定期借家 4年               3
定期借家 西暦2086年9月まで      3
定期借家 5年4ヶ月            2

dtype              object
rows                17927
non_null             7922
null_count          10005
null_pct            55.81
sentinel_count          0
unique_non_null        19
dtype: object

In [37]:
contract_period_counts = (
      raw['contract_period']
      .astype('string')
      .fillna('<NA>')
      .value_counts(dropna=False)
      .rename_axis('contract_period')
      .reset_index(name='count')
  )

print(f'Total unique values: {len(contract_period_counts)}')
display(contract_period_counts)

Total unique values: 20

     contract_period  count
0               <NA>  10005
1            普通借家 2年   5909
2            普通借家 1年   1662
3            定期借家 2年    242
4            定期借家 1年     30
5            定期借家 5年     28
6            定期借家 3年     11
7           定期借家 10年      7
8           普通借家 2ヶ月      7
9            普通借家 3年      6
10           定期借家 8年      4
11           定期借家 6年      3
12           定期借家 4年      3
13  定期借家 西暦2086年9月まで      3
14        定期借家 5年4ヶ月      2
15  定期借家 西暦2036年2月まで      1
16           普通借家 6年      1
17  定期借家 西暦2036年1月まで      1
18  定期借家 西暦2027年4月まで      1
19           普通借家 5年      1

In [38]:
# Function xử lý riêng cho `contract_period`: parse loại hợp đồng và thời lượng theo năm/tháng.
def process_contract_period():
    parsed = raw['contract_period'].map(parse_contract)
    output_df = pd.DataFrame({
        'contract_type': parsed.map(lambda value: value[0]).astype('string'),
        'contract_years': pd.array(parsed.map(lambda value: value[1]), dtype='Int64'),
        'contract_months': pd.array(parsed.map(lambda value: value[2]), dtype='Int64'),
    })
    processed_outputs['contract_period'] = output_df
    return output_df.sample(n=10)

process_contract_period()

      contract_type  contract_years  contract_months
136        ordinary               2                0
9418           <NA>            <NA>             <NA>
14572          <NA>            <NA>             <NA>
4394           <NA>            <NA>             <NA>
15044          <NA>            <NA>             <NA>
13405    fixed_term              10                0
10979          <NA>            <NA>             <NA>
14429          <NA>            <NA>             <NA>
1015       ordinary               2                0
12602      ordinary               2                0

In [39]:
# Kiểm tra lại output sau xử lý của column `contract_period`.
check_processed_column('contract_period')

     output_column  non_null  null_pct  unique_non_null
0    contract_type      7916     55.84                2
1   contract_years      7916     55.84                9
2  contract_months      7916     55.84                3

  contract_type  contract_years  contract_months
0          <NA>            <NA>             <NA>
1          <NA>            <NA>             <NA>
2          <NA>            <NA>             <NA>
3          <NA>            <NA>             <NA>
4          <NA>            <NA>             <NA>
5          <NA>            <NA>             <NA>
6          <NA>            <NA>             <NA>
7          <NA>            <NA>             <NA>
8          <NA>            <NA>             <NA>
9          <NA>            <NA>             <NA>

--- contract_type top values ---

               count
contract_type
<NA>           10011
ordinary        7586
fixed_term       330

--- contract_years top values ---

                count
contract_years
<NA>            10011
2                6151
1                1692
5                  31
3                  17
10                  7
0                   7
8                   4
6                   4
4                   3

--- contract_months top values ---

                 count
contract_months
<NA>             10011
0                 7907
2                    7
4                    2

      contract_type  contract_years  contract_months
0              <NA>            <NA>             <NA>
1              <NA>            <NA>             <NA>
2              <NA>            <NA>             <NA>
3              <NA>            <NA>             <NA>
4              <NA>            <NA>             <NA>
...             ...             ...              ...
17922      ordinary               1                0
17923      ordinary               1                0
17924      ordinary               1                0
17925      ordinary               1                0
17926      ordinary               1                0

[17927 rows x 3 columns]

### Nhóm: Địa điểm và tiếp cận giao thông

#### `address`

Địa chỉ listing dạng đầy đủ. Giữ raw address để audit và parse thành prefecture, district, municipality, ward, locality, chome; không tự thêm prefecture khi raw không có.

In [40]:
# Kiểm tra raw column `address` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'address')

                address
dtype            object
rows              17927
non_null          17927
null_count            0
null_pct            0.0
sentinel_count        0
unique_non_null      87

                count
address
大阪府大阪市淀川区宮原1     1498
大阪府大阪市淀川区十三本町2   1403
大阪府大阪市淀川区十三東3     732
大阪府大阪市淀川区西宮原2     647
大阪府大阪市淀川区塚本2      570
大阪府大阪市淀川区東三国1     555
大阪府大阪市淀川区西宮原1     541
大阪府大阪市淀川区新北野1     520
大阪府大阪市淀川区十三東1     486
大阪府大阪市淀川区宮原5      435
大阪府大阪市淀川区田川3      429
大阪府大阪市淀川区木川東4     416
大阪府大阪市淀川区加島3      396
大阪府大阪市淀川区西三国1     380
大阪府大阪市淀川区東三国6     368

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null        87
dtype: object

In [41]:
# Function xử lý riêng cho `address`: giữ raw address và parse đủ cấp hành chính/locality/chome.
def process_address():
    parsed = raw['address'].map(parse_address_parts)
    output_df = pd.DataFrame({
        'address_raw': raw['address'].astype('string'),
        'prefecture': parsed.map(lambda value: value[0]).astype('string'),
        'district': parsed.map(lambda value: value[1]).astype('string'),
        'municipality': parsed.map(lambda value: value[2]).astype('string'),
        'ward': parsed.map(lambda value: value[3]).astype('string'),
        'locality': parsed.map(lambda value: value[4]).astype('string'),
        'chome': pd.array(parsed.map(lambda value: value[5]), dtype='Int64'),
    })
    processed_outputs['address'] = output_df
    return output_df.head(10)

process_address()

     address_raw prefecture district municipality ward locality  chome
0  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
1  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
2  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
3  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
4  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
5  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
6  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
7  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
8  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
9  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1

In [42]:
# Kiểm tra lại output sau xử lý của column `address`.
check_processed_column('address')

  output_column  non_null  null_pct  unique_non_null
0   address_raw     17927       0.0               87
1    prefecture     17927       0.0                1
2      district         0     100.0                0
3  municipality     17927       0.0                1
4          ward     17927       0.0                1
5      locality     17927       0.0               23
6         chome     17927       0.0                7

     address_raw prefecture district municipality ward locality  chome
0  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
1  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
2  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
3  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
4  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
5  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
6  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
7  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
8  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
9  大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1

--- prefecture top values ---

            count
prefecture
大阪府         17927

--- district top values ---

          count
district
<NA>      17927

--- municipality top values ---

              count
municipality
大阪市           17927

--- ward top values ---

      count
ward
淀川区   17927

--- locality top values ---

          count
locality
宮原         2531
東三国        1803
十三本町       1634
十三東        1398
西宮原        1349
西中島        1250
塚本         1212
木川東        1113
西三国         781
三国本町        679

--- chome top values ---

       count
chome
1       6095
2       5154
3       3110
4       2025
5        831
6        655
7         57

          address_raw prefecture district municipality ward locality  chome
0       大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
1       大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
2       大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
3       大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
4       大阪府大阪市淀川区西三国１        大阪府     <NA>          大阪市  淀川区      西三国      1
...               ...        ...      ...          ...  ...      ...    ...
17922  大阪府大阪市淀川区十三本町２        大阪府     <NA>          大阪市  淀川区     十三本町      2
17923  大阪府大阪市淀川区十三本町２        大阪府     <NA>          大阪市  淀川区     十三本町      2
17924  大阪府大阪市淀川区十三本町２        大阪府     <NA>          大阪市  淀川区     十三本町      2
17925  大阪府大阪市淀川区十三本町２        大阪府     <NA>          大阪市  淀川区     十三本町      2
17926  大阪府大阪市淀川区十三本町２        大阪府     <NA>          大阪市  淀川区     十三本町      2

[17927 rows x 7 columns]

#### `station_access`

Thông tin tuyến/ga và thời gian đi bộ, bus hoặc xe. Một listing có thể có nhiều dòng ga, nên nên tách thành bảng station_access một-nhiều.

In [43]:
# Kiểm tra raw column `station_access` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'station_access')

                station_access
dtype                   object
rows                     17927
non_null                 17927
null_count                   0
null_pct                   0.0
sentinel_count               1
unique_non_null           6454

                                                         count
station_access
阪急神戸線/十三駅 歩6分\nJR東海道本線/塚本駅 歩20分\n阪急神戸線/神崎川駅 歩20分           242
阪急京都線/十三駅 歩5分\n阪急神戸線/神崎川駅 歩20分\nJR東海道本線/塚本駅 歩19分           178
地下鉄御堂筋線/新大阪駅 歩7分\n地下鉄御堂筋線/東三国駅 歩3分\nJR東海道本線/東淀川駅 歩5分       140
阪急神戸線/十三駅 歩10分\n地下鉄御堂筋線/西中島南方駅 歩13分\n阪急京都線/南方駅 歩15分        137
阪急神戸線/十三駅 歩6分\nJR東海道本線/塚本駅 歩19分\n地下鉄御堂筋線/西中島南方駅 歩29分       123
JR東海道本線/塚本駅 歩2分\nJR東西線/御幣島駅 歩19分\n阪急神戸線/十三駅 歩20分           113
阪急神戸線/十三駅 歩9分\n地下鉄御堂筋線/西中島南方駅 歩13分\n阪急京都線/南方駅 歩15分         110
阪急神戸線/十三駅 歩6分\n阪急神戸線/神崎川駅 歩19分\n阪急京都線/南方駅 歩28分             109
JR東海道本線/塚本駅 歩12分\n阪急神戸線/十三駅 歩20分\nJR東西線/御幣島駅 歩20分           86
阪急神戸線/十三駅 歩7分\nJR東海道本線/塚本駅 歩20分\n阪急神戸線/神崎川駅 歩20分            77
地下鉄御堂筋線/東三国駅 歩5分\nJR東海道本線/東淀川駅 歩7分\n東海道新幹線/新大阪駅 歩7分         77
阪急神戸線/十三駅 歩7分\nJR東海道本線/塚本駅 歩16分\n阪急宝塚線/中津駅 歩22分             76
地下鉄御堂筋線/東三国駅 歩8分\nJR東海道本線/東淀川駅 歩9分\n東海道新幹線/新大阪駅 歩9分         62
阪急神戸線/十三駅 歩10分\n地下鉄御堂筋線/西中島南方駅 歩13分\nJRおおさか東線/新大阪駅 歩23分     59
JR東海道本線/塚本駅 歩2分\nJR東西線/御幣島駅 歩19分\n阪急京都線/十三駅 歩20分            59

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          1
unique_non_null      6454
dtype: object

In [44]:
# Function xử lý riêng cho `station_access`: split route ga/tuyến, lấy primary route và đếm số route.
# Cho phép chạy riêng cell này: nếu cell helper chưa được chạy thì định nghĩa fallback tại đây.
if 'STATION_OUTPUT_COLUMNS' not in globals():
    STATION_OUTPUT_COLUMNS = [
        'station_parse_failure_count',
        'primary_station_line',
        'primary_station_name',
        'primary_access_mode',
        'primary_total_travel_minutes',
        'station_count',
    ]

if '_station_rows_for_record' not in globals():
    STATION_ACCESS_TIME_PATTERN = re.compile(r'(?P<mode>バス|歩|車)\s*(?P<minutes>\d+)\s*分')

    def _parse_station_access_line(line):
        normalized = normalize_text_for_profile(line)
        if normalized is None or normalized in NULL_SENTINELS or '/' not in normalized:
            return None

        station_line, access_text = normalized.split('/', 1)
        station_line = station_line.strip()
        time_matches = list(STATION_ACCESS_TIME_PATTERN.finditer(access_text))
        if not station_line or not time_matches:
            return None

        station_name = access_text[:time_matches[0].start()].strip()
        station_name = re.sub(r'駅$', '', station_name).strip()
        if not station_name:
            return None

        total_travel_minutes = sum(int(match.group('minutes')) for match in time_matches)
        modes = [match.group('mode') for match in time_matches]
        if 'バス' in station_line or 'バス' in modes:
            access_mode = 'bus'
        elif '車' in modes:
            access_mode = 'car'
        else:
            access_mode = 'walk'

        return {
            'station_line': station_line,
            'station_name': station_name,
            'access_mode': access_mode,
            'total_travel_minutes': total_travel_minutes,
        }

    def _station_rows_for_record(record):
        normalized = normalize_text_for_profile(record.get('station_access'))
        if normalized is None or normalized in NULL_SENTINELS:
            return [], 0

        rows = []
        failures = 0
        lines = [line.strip() for line in re.split(r'[\r\n]+', normalized) if line.strip()]
        for access_order, line in enumerate(lines, start=1):
            parsed = _parse_station_access_line(line)
            if parsed is None:
                failures += 1
                continue
            parsed.update({
                'task_id': record.get('task_id'),
                'batch_id': record.get('batch_id'),
                'suumo_property_code': record.get('suumo_property_code'),
                'access_order': access_order,
            })
            rows.append(parsed)
        return rows, failures

def process_station_access():
    temp = raw[['task_id', 'batch_id', 'suumo_property_code', 'station_access']].copy()
    rows = []
    failures_by_task = {}
    for _, record in temp.iterrows():
        record_rows, failures = _station_rows_for_record(record)
        rows.extend(record_rows)
        failures_by_task[record['task_id']] = failures
    station_df = pd.DataFrame(rows)
    output_df = pd.DataFrame(index=raw.index)
    output_df['station_parse_failure_count'] = raw['task_id'].map(failures_by_task).fillna(0).astype('Int64')
    for column in ['primary_station_line', 'primary_station_name', 'primary_access_mode']:
        output_df[column] = pd.Series(pd.NA, index=raw.index, dtype='string')
    for column in ['primary_total_travel_minutes', 'station_count']:
        output_df[column] = pd.Series(pd.NA, index=raw.index, dtype='Int64')
    if not station_df.empty:
        primary = station_df.sort_values(['task_id', 'access_order']).drop_duplicates('task_id').set_index('task_id')
        counts = station_df.groupby('task_id').size()
        output_df['primary_station_line'] = raw['task_id'].map(primary['station_line']).astype('string')
        output_df['primary_station_name'] = raw['task_id'].map(primary['station_name']).astype('string')
        output_df['primary_access_mode'] = raw['task_id'].map(primary['access_mode']).astype('string')
        output_df['primary_total_travel_minutes'] = pd.to_numeric(
            raw['task_id'].map(primary['total_travel_minutes']), errors='coerce'
        ).astype('Int64')
        output_df['station_count'] = pd.to_numeric(raw['task_id'].map(counts), errors='coerce').astype('Int64')
    output_df = output_df[STATION_OUTPUT_COLUMNS]
    processed_outputs['station_access'] = output_df
    return output_df.head(10)

process_station_access()

,station_parse_failure_count,primary_station_line,primary_station_name,primary_access_mode,primary_total_travel_minutes,station_count
0,0,地下鉄御堂筋線,東三国,walk,12,3
1,0,地下鉄御堂筋線,東三国,walk,12,3
2,0,地下鉄御堂筋線,東三国,walk,12,3
3,0,地下鉄御堂筋線,東三国,walk,12,3
4,0,地下鉄御堂筋線,東三国,walk,12,3
5,0,地下鉄御堂筋線,東三国,walk,12,3
6,0,地下鉄御堂筋線,東三国,walk,12,3
7,0,地下鉄御堂筋線,東三国,walk,12,3
8,0,地下鉄御堂筋線,東三国,walk,12,3
9,0,地下鉄御堂筋線,東三国,walk,12,3

In [45]:
# Kiểm tra lại output sau xử lý của column `station_access`.
check_processed_column('station_access')

                  output_column  non_null  null_pct  unique_non_null
0   station_parse_failure_count     17927      0.00                1
1          primary_station_line     17926      0.01               10
2          primary_station_name     17926      0.01               15
3           primary_access_mode     17926      0.01                2
4  primary_total_travel_minutes     17926      0.01               28
5                 station_count     17926      0.01                3

,station_parse_failure_count,primary_station_line,primary_station_name,primary_access_mode,primary_total_travel_minutes,station_count
0,0,地下鉄御堂筋線,東三国,walk,12,3
1,0,地下鉄御堂筋線,東三国,walk,12,3
2,0,地下鉄御堂筋線,東三国,walk,12,3
3,0,地下鉄御堂筋線,東三国,walk,12,3
4,0,地下鉄御堂筋線,東三国,walk,12,3
5,0,地下鉄御堂筋線,東三国,walk,12,3
6,0,地下鉄御堂筋線,東三国,walk,12,3
7,0,地下鉄御堂筋線,東三国,walk,12,3
8,0,地下鉄御堂筋線,東三国,walk,12,3
9,0,地下鉄御堂筋線,東三国,walk,12,3

--- station_parse_failure_count top values ---

                             count
station_parse_failure_count
0                            17927

--- primary_station_line top values ---

                      count
primary_station_line
地下鉄御堂筋線                7500
阪急神戸線                  3646
JR東海道本線                2931
阪急宝塚線                  2086
阪急京都線                  1027
JR東西線                   607
JRおおさか東線                 78
東海道新幹線                   32
北大阪急行                    15
山陽新幹線                     4

--- primary_station_name top values ---

                      count
primary_station_name
十三                     4105
東三国                    3626
新大阪                    2385
西中島南方                  2147
塚本                     1895
三国                     1720
神崎川                     757
加島                      605
東淀川                     475
南方                      174

--- primary_access_mode top values ---

                     count
primary_access_mode
walk                 17924
bus                      2
<NA>                     1

--- primary_total_travel_minutes top values ---

                              count
primary_total_travel_minutes
5                              2774
7                              2018
6                              1679
3                              1545
10                             1506
8                              1488
9                              1467
4                              1270
12                             1031
2                              1011

--- station_count top values ---

               count
station_count
3              17323
2                472
1                131
<NA>               1

,station_parse_failure_count,primary_station_line,primary_station_name,primary_access_mode,primary_total_travel_minutes,station_count
0,0,地下鉄御堂筋線,東三国,walk,12,3
1,0,地下鉄御堂筋線,東三国,walk,12,3
2,0,地下鉄御堂筋線,東三国,walk,12,3
3,0,地下鉄御堂筋線,東三国,walk,12,3
4,0,地下鉄御堂筋線,東三国,walk,12,3
...,...,...,...,...,...,...
17922,0,阪急神戸線,十三,walk,6,3
17923,0,阪急神戸線,十三,walk,6,3
17924,0,阪急神戸線,十三,walk,6,3
17925,0,阪急神戸線,十三,walk,6,3
17926,0,阪急神戸線,十三,walk,6,3

### Nhóm: Giá thuê và chi phí hàng tháng

#### `rent_price_text`

家賃, tiền thuê nhà hàng tháng ở dạng text gốc như 8.5万円. Đây là giá thuê chính chưa gồm các phí khác.

In [46]:
# Kiểm tra raw column `rent_price_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'rent_price_text')

                rent_price_text
dtype                    object
rows                      17927
non_null                  17927
null_count                    0
null_pct                    0.0
sentinel_count                0
unique_non_null             409

                 count
rent_price_text
7万円                370
7.1万円              327
7.8万円              305
7.3万円              288
7.5万円              286
8万円                284
8.4万円              280
6万円                269
7.2万円              263
8.5万円              249
7.6万円              247
5万円                233
6.9万円              224
8.3万円              211
12万円               210

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null       409
dtype: object

In [47]:
# Function xử lý riêng cho `rent_price_text`: parse 家賃 từ 万円/円 sang yen Nhật.
def process_rent_price_text():
    output_df = pd.DataFrame({'rent_jpy': pd.array(raw['rent_price_text'].map(parse_jpy_value), dtype='Int64')})
    processed_outputs['rent_price_text'] = output_df
    return output_df.head(10)

process_rent_price_text()

   rent_jpy
0     81500
1     81500
2     82500
3     82500
4     83000
5     83000
6     83500
7     83500
8     84000
9     84000

In [48]:
# Kiểm tra lại output sau xử lý của column `rent_price_text`.
check_processed_column('rent_price_text')

  output_column  non_null  null_pct  unique_non_null
0      rent_jpy     17927       0.0              409

   rent_jpy
0     81500
1     81500
2     82500
3     82500
4     83000
5     83000
6     83500
7     83500
8     84000
9     84000

       rent_jpy
0         81500
1         81500
2         82500
3         82500
4         83000
...         ...
17922     70700
17923     70700
17924     71000
17925     71000
17926     71000

[17927 rows x 1 columns]

#### `management_fee_text`

管理費/共益費, phí quản lý hoặc phí khu vực chung hàng tháng. Ở Nhật khoản này thường trả cùng tiền thuê và cần cộng vào chi phí tháng.

In [49]:
# Kiểm tra raw column `management_fee_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'management_fee_text')

                management_fee_text
dtype                        object
rows                          17927
non_null                      17927
null_count                        0
null_pct                        0.0
sentinel_count                  966
unique_non_null                 149

                     count
management_fee_text
10000円                3505
8000円                 2925
5000円                 1075
-                      966
7000円                  934
9000円                  822
12000円                 768
15000円                 738
6000円                  713
12500円                 615
6350円                  554
7450円                  455
8500円                  431
3000円                  384
13000円                 355

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count        966
unique_non_null       149
dtype: object

In [50]:
# Function xử lý riêng cho `management_fee_text`: parse 管理費/共益費; sentinel như '-' được hiểu là 0.
def process_management_fee_text():
    output_df = pd.DataFrame({
        'management_fee_jpy': pd.array(raw['management_fee_text'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True)), dtype='Int64')
    })
    processed_outputs['management_fee_text'] = output_df
    return output_df.head(10)

process_management_fee_text()

   management_fee_jpy
0                8000
1                8000
2                8000
3                8000
4                8000
5                8000
6                8000
7                8000
8                8000
9                8000

In [51]:
# Kiểm tra lại output sau xử lý của column `management_fee_text`.
check_processed_column('management_fee_text')

        output_column  non_null  null_pct  unique_non_null
0  management_fee_jpy     17927       0.0              149

   management_fee_jpy
0                8000
1                8000
2                8000
3                8000
4                8000
5                8000
6                8000
7                8000
8                8000
9                8000

       management_fee_jpy
0                    8000
1                    8000
2                    8000
3                    8000
4                    8000
...                   ...
17922                6350
17923                6350
17924                6350
17925                6350
17926                6350

[17927 rows x 1 columns]

#### `other_monthly_costs` — DEFERRED / SKIP PARSING

> **Trạng thái: tạm bỏ qua xử lý định lượng.** Giữ nguyên raw column và giữ helper audit bên dưới để xem xét sau. Không parse thành JPY, không cộng vào tổng chi phí hàng tháng, vì free text đang trộn phí hàng tháng, phí gia hạn và phí một lần. Agent xử lý tiếp notebook phải coi cột này là deferred cho đến khi có rule phân loại đáng tin cậy.

ほか諸費用, các chi phí khác ngoài tiền thuê và phí quản lý.

In [52]:
# Kiểm tra raw column `other_monthly_costs` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'other_monthly_costs')

                other_monthly_costs
dtype                        object
rows                          17927
non_null                       9447
null_count                     8480
null_pct                       47.3
sentinel_count                    0
unique_non_null                2652

                            count
other_monthly_costs
None                         8480
更新料1ヵ月                        322
プレサポ24(課税対象) 1320円(月額)        251
更新事務手数料16500円                 236
水道代2000円                      187
安心サポート241320円/室内清掃費用38500円    176
更新料11000円                     155
更新料 新賃料1.00ヶ月分                152
更新料 賃料1.00ヶ月分                 126
水道代2200円                      111
プレサポ(課税対象) 990円(月額)           109
室内清掃費用 22000円                  93
水道代2420円                       90
更新料 11000円 プレサポ24 月額1320円      87
室内清掃費用 33000円                  86

dtype              object
rows                17927
non_null             9447
null_count           8480
null_pct             47.3
sentinel_count          0
unique_non_null      2652
dtype: object

In [53]:
# DEFERRED/SKIP PARSING: giữ function này chỉ để audit coverage; không tạo amount JPY và không dùng trong monthly total.
def process_other_monthly_costs():
    """Audit raw text; KHÔNG phải parser chi phí và chưa được dùng làm feature phân tích."""
    assert 'other_monthly_costs' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['other_monthly_costs'])
    output_df = pd.DataFrame({
        'other_monthly_costs_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'other_monthly_costs_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['other_monthly_costs'] = output_df
    return output_df.head(10)

process_other_monthly_costs()

   other_monthly_costs_present  other_monthly_costs_text_length
0                        False                             <NA>
1                        False                             <NA>
2                        False                             <NA>
3                        False                             <NA>
4                        False                             <NA>
5                        False                             <NA>
6                        False                             <NA>
7                        False                             <NA>
8                        False                             <NA>
9                        False                             <NA>

In [54]:
# Kiểm tra lại output sau xử lý của column `other_monthly_costs`.
check_processed_column('other_monthly_costs')

                     output_column  non_null  null_pct  unique_non_null
0      other_monthly_costs_present     17927       0.0                2
1  other_monthly_costs_text_length      9447      47.3              130

   other_monthly_costs_present  other_monthly_costs_text_length
0                        False                             <NA>
1                        False                             <NA>
2                        False                             <NA>
3                        False                             <NA>
4                        False                             <NA>
5                        False                             <NA>
6                        False                             <NA>
7                        False                             <NA>
8                        False                             <NA>
9                        False                             <NA>

--- other_monthly_costs_present top values ---

                             count
other_monthly_costs_present
True                          9447
False                         8480

       other_monthly_costs_present  other_monthly_costs_text_length
0                            False                             <NA>
1                            False                             <NA>
2                            False                             <NA>
3                            False                             <NA>
4                            False                             <NA>
...                            ...                              ...
17922                        False                             <NA>
17923                        False                             <NA>
17924                        False                             <NA>
17925                        False                             <NA>
17926                        False                             <NA>

[17927 rows x 2 columns]

### Nhóm: Chi phí ban đầu và bảo lãnh

#### `deposit_text`

敷金, tiền cọc khi thuê nhà. Thường có khả năng hoàn lại một phần/toàn phần tùy hợp đồng, khác với tiền lễ.

In [55]:
# Kiểm tra raw column `deposit_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'deposit_text')

                deposit_text
dtype                 object
rows                   17927
non_null               17927
null_count                 0
null_pct                 0.0
sentinel_count         16129
unique_non_null          159

              count
deposit_text
-             16129
2万円              95
5万円              94
12.2万円           88
10万円             64
12.1万円           61
7.6万円            44
7万円              42
7.7万円            39
8.4万円            38
3万円              37
8.5万円            36
8.2万円            35
7.9万円            34
12.3万円           32

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      16129
unique_non_null       159
dtype: object

In [56]:
# Function xử lý riêng cho `deposit_text`: parse 敷金 tiền cọc; sentinel như '-' được hiểu là 0.
def process_deposit_text():
    output_df = pd.DataFrame({'deposit_jpy': pd.array(raw['deposit_text'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True)), dtype='Int64')})
    processed_outputs['deposit_text'] = output_df
    return output_df.head(10)

process_deposit_text()

   deposit_jpy
0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0

In [57]:
# Kiểm tra lại output sau xử lý của column `deposit_text`.
check_processed_column('deposit_text')

  output_column  non_null  null_pct  unique_non_null
0   deposit_jpy     17927       0.0              159

   deposit_jpy
0            0
1            0
2            0
3            0
4            0
5            0
6            0
7            0
8            0
9            0

       deposit_jpy
0                0
1                0
2                0
3                0
4                0
...            ...
17922            0
17923            0
17924            0
17925            0
17926            0

[17927 rows x 1 columns]

#### `key_money_text`

礼金, tiền lễ hay tiền cảm ơn chủ nhà theo tập quán thuê nhà ở Nhật. Khoản này thường không hoàn lại, nên ảnh hưởng mạnh đến chi phí ban đầu.

In [58]:
# Kiểm tra raw column `key_money_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'key_money_text')

                key_money_text
dtype                   object
rows                     17927
non_null                 17927
null_count                   0
null_pct                   0.0
sentinel_count            8485
unique_non_null            390

                count
key_money_text
-                8485
10万円              830
5万円               249
15万円              212
8万円               206
20万円              196
12万円              177
7.1万円             166
7万円               160
7.8万円             146
6万円               141
7.5万円             139
13万円              125
7.4万円             121
7.2万円             120

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       8485
unique_non_null       390
dtype: object

In [59]:
# Function xử lý riêng cho `key_money_text`: parse 礼金 tiền lễ/tền cảm ơn; sentinel như '-' được hiểu là 0.
def process_key_money_text():
    output_df = pd.DataFrame({'key_money_jpy': pd.array(raw['key_money_text'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True)), dtype='Int64')})
    processed_outputs['key_money_text'] = output_df
    return output_df.head(10)

process_key_money_text()

   key_money_jpy
0              0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0

In [60]:
# Kiểm tra lại output sau xử lý của column `key_money_text`.
check_processed_column('key_money_text')

   output_column  non_null  null_pct  unique_non_null
0  key_money_jpy     17927       0.0              390

   key_money_jpy
0              0
1              0
2              0
3              0
4              0
5              0
6              0
7              0
8              0
9              0

       key_money_jpy
0                  0
1                  0
2                  0
3                  0
4                  0
...              ...
17922          70700
17923          70700
17924          71000
17925          71000
17926          71000

[17927 rows x 1 columns]

#### `guarantee_deposit_text`

保証金, tiền bảo đảm. Tùy listing, khoản này có thể gần giống tiền cọc nhưng vẫn nên tách riêng vì ý nghĩa hợp đồng khác nhau.

In [61]:
# Kiểm tra raw column `guarantee_deposit_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'guarantee_deposit_text')

                guarantee_deposit_text
dtype                           object
rows                             17927
non_null                         17927
null_count                           0
null_pct                           0.0
sentinel_count                   17910
unique_non_null                      7

                        count
guarantee_deposit_text
-                       17910
5.9万円                       6
6.6万円                       4
2万円                         4
5万円                         1
85.8万円                      1
6.85万円                      1

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      17910
unique_non_null         7
dtype: object

In [62]:
# Lọc trực tiếp record bất thường từ analysis_raw; dataframe này không chứa URL bài gốc.
suspicious_guarantee_deposit = analysis_raw.loc[
    analysis_raw['guarantee_deposit_text'].map(normalize_text_for_profile).eq('85.8万円'),
].copy()
display(suspicious_guarantee_deposit.T)

url_columns = [
    column for column in analysis_raw.columns
    if column.lower() in {'url', 'source_url', 'final_url', 'property_url'}
]
print(f'Các cột URL bài gốc có trong analysis_raw: {url_columns}')

                                                                                        12923
task_id                                                                                  8712
batch_id                                                                                   88
source_id                                                                                   1
suumo_property_code                                                              100352006157
data_hash                    02cd89ab6183a08cd0cd71974672f440d5251eca851d6934782023583c2b8ae7
is_valid                                                                                 True
shop_property_code                                                                   98459716
information_updated_at_text                                                        2026/08/03
move_in                                                                                     即
transaction_type                                                                           仲介
contract_period                                                                           NaN
address                                                                        大阪府大阪市淀川区十三本町１
station_access                                                阪急神戸線/十三駅 歩7分\nＪＲ東海道本線/塚本駅 歩16分
rent_price_text                                                                        14.3万円
management_fee_text                                                                         -
other_monthly_costs                                                                       NaN
deposit_text                                                                                -
key_money_text                                                                              -
guarantee_deposit_text                                                                 85.8万円
depreciation_text                                                                      42.9万円
brokerage_fee                                                                             NaN
other_initial_costs                                                                       NaN
guarantee_company                                                  保証会社利用必 初回総賃料１００％　更新料１０％／年
layout                                                                                  ワンルーム
layout_detail                                                                               -
exclusive_area_text                                                                   43.56m2
building_age_text                                                                        築47年
built_at_text                                                                        1979年10月
floor_text                                                                                 2階
building_floors                                                                       2階/11階建
total_units                                                                               60戸
building_type                                                                           マンション
structure                                                                                鉄骨鉄筋
direction                                                                                   -
conditions                                                                              二人入居可
insurance                                                                                   要
parking                                                                                     -
energy_efficiency                                                                           -
insulation_performance                                                                      -
estimated_utility_cost                                                                      -
remarks                                                                          保証会社:全保連株式会社

Các cột URL bài gốc có trong analysis_raw: []

In [63]:
# Function xử lý riêng cho `guarantee_deposit_text`: parse 保証金 tiền bảo đảm; sentinel như '-' được hiểu là 0.
def process_guarantee_deposit_text():
    output_df = pd.DataFrame({'guarantee_deposit_jpy': pd.array(raw['guarantee_deposit_text'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True)), dtype='Int64')})
    processed_outputs['guarantee_deposit_text'] = output_df
    return output_df.head(10)

process_guarantee_deposit_text()

   guarantee_deposit_jpy
0                      0
1                      0
2                      0
3                      0
4                      0
5                      0
6                      0
7                      0
8                      0
9                      0

In [64]:
# Kiểm tra lại output sau xử lý của column `guarantee_deposit_text`.
check_processed_column('guarantee_deposit_text')

           output_column  non_null  null_pct  unique_non_null
0  guarantee_deposit_jpy     17927       0.0                7

   guarantee_deposit_jpy
0                      0
1                      0
2                      0
3                      0
4                      0
5                      0
6                      0
7                      0
8                      0
9                      0

--- guarantee_deposit_jpy top values ---

                       count
guarantee_deposit_jpy
0                      17910
59000                      6
66000                      4
20000                      4
50000                      1
858000                     1
68500                      1

       guarantee_deposit_jpy
0                          0
1                          0
2                          0
3                          0
4                          0
...                      ...
17922                      0
17923                      0
17924                      0
17925                      0
17926                      0

[17927 rows x 1 columns]

In [65]:
# Lọc các listing có guarantee deposit thực sự và đối chiếu depreciation cùng record.
guarantee_normalized = analysis_raw['guarantee_deposit_text'].map(normalize_text_for_profile)
has_guarantee_deposit = guarantee_normalized.notna() & ~guarantee_normalized.isin(MONEY_ZERO_SENTINELS)

guarantee_depreciation_pairs = analysis_raw.loc[
    has_guarantee_deposit,
    [
        'task_id',
        'suumo_property_code',
        'shop_property_code',
        'guarantee_deposit_text',
        'depreciation_text',
    ],
].copy()
guarantee_depreciation_pairs['guarantee_deposit_jpy'] = pd.array(
    guarantee_depreciation_pairs['guarantee_deposit_text'].map(parse_jpy_value),
    dtype='Int64',
)
guarantee_depreciation_pairs['depreciation_jpy'] = pd.array(
    guarantee_depreciation_pairs['depreciation_text'].map(
        lambda value: parse_jpy_value(value, sentinel_as_zero=True)
    ),
    dtype='Int64',
)
guarantee_depreciation_pairs = guarantee_depreciation_pairs.sort_values(
    ['guarantee_deposit_jpy', 'depreciation_jpy'],
    ascending=[False, False],
).reset_index(drop=True)

print(f'Listings có guarantee deposit: {len(guarantee_depreciation_pairs):,}')
display(guarantee_depreciation_pairs)

Listings có guarantee deposit: 17

,task_id,suumo_property_code,shop_property_code,guarantee_deposit_text,depreciation_text,guarantee_deposit_jpy,depreciation_jpy
0,8712,100352006157,98459716,85.8万円,42.9万円,858000,429000
1,6937,100518038902,12317218-846,6.85万円,-,68500,0
2,20472,100502531378,HC2-3125315-606-0246,6.6万円,6.6万円,66000,66000
3,10656,100506323594,2174845,6.6万円,6.6万円,66000,66000
4,5044,100506323784,2174957,6.6万円,6.6万円,66000,66000
5,12912,100517180571,18183425,6.6万円,-,66000,0
6,10653,100516807416,HC2-3127129-1011-0246,5.9万円,5.9万円,59000,59000
7,19341,100520739862,2728362,5.9万円,-,59000,0
8,16482,100508896415,928251,5.9万円,-,59000,0
9,15321,100498502504,112222757,5.9万円,-,59000,0
10,12963,100515542900,385685,5.9万円,-,59000,0
11,10721,100518163110,373708,5.9万円,-,59000,0
12,13843,100517117328,2641642,5万円,-,50000,0
13,17002,100518741111,104962855,2万円,-,20000,0
14,10081,100516353092,100140588,2万円,-,20000,0
15,10088,100518741035,104962882,2万円,-,20000,0
16,4426,100518741200,104962873,2万円,-,20000,0

#### `depreciation_text`

敷引/償却, khoản bị trừ hoặc khấu hao từ tiền cọc/tiền bảo đảm. Thường là phần không hoàn lại khi kết thúc hợp đồng.

In [66]:
# Kiểm tra raw column `depreciation_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'depreciation_text')

                depreciation_text
dtype                      object
rows                        17927
non_null                    17927
null_count                      0
null_pct                      0.0
sentinel_count              17921
unique_non_null                 5

                   count
depreciation_text
-                  17921
6.6万円                  3
9.1万円                  1
5.9万円                  1
42.9万円                 1

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      17921
unique_non_null         5
dtype: object

In [67]:
# Function xử lý riêng cho `depreciation_text`: parse 敷引/償却 khoản không hoàn lại/khấu hao; sentinel như '-' được hiểu là 0.
def process_depreciation_text():
    output_df = pd.DataFrame({'depreciation_jpy': pd.array(raw['depreciation_text'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True)), dtype='Int64')})
    processed_outputs['depreciation_text'] = output_df
    return output_df.head(10)

process_depreciation_text()

   depreciation_jpy
0                 0
1                 0
2                 0
3                 0
4                 0
5                 0
6                 0
7                 0
8                 0
9                 0

In [68]:
# Kiểm tra lại output sau xử lý của column `depreciation_text`.
check_processed_column('depreciation_text')

      output_column  non_null  null_pct  unique_non_null
0  depreciation_jpy     17927       0.0                5

   depreciation_jpy
0                 0
1                 0
2                 0
3                 0
4                 0
5                 0
6                 0
7                 0
8                 0
9                 0

--- depreciation_jpy top values ---

                  count
depreciation_jpy
0                 17921
66000                 3
91000                 1
59000                 1
429000                1

       depreciation_jpy
0                     0
1                     0
2                     0
3                     0
4                     0
...                 ...
17922                 0
17923                 0
17924                 0
17925                 0
17926                 0

[17927 rows x 1 columns]

#### `brokerage_fee`

仲介手数料, phí môi giới trả cho công ty môi giới. Có thể ghi bằng yen hoặc theo số tháng tiền thuê, ví dụ 1ヶ月.

In [69]:
# Kiểm tra raw column `brokerage_fee` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'brokerage_fee')

                brokerage_fee
dtype                  object
rows                    17927
non_null                 1515
null_count              16412
null_pct                91.55
sentinel_count           1296
unique_non_null            17

               count
brokerage_fee
None           16412
不要              1296
1.1ヶ月             93
0.55ヶ月            85
1ヶ月               16
0.5ヶ月             10
13.42万円            3
8.58万円             2
7.04万円             1
14.3万円             1
8.91万円             1
6.6万円              1
13.2万円             1
12.1万円             1
14.85万円            1

dtype              object
rows                17927
non_null             1515
null_count          16412
null_pct            91.55
sentinel_count       1296
unique_non_null        17
dtype: object

In [70]:
# Function xử lý riêng cho `brokerage_fee`: parse 仲介手数料 theo yen hoặc theo số tháng tiền thuê, rồi ước tính yen.
def process_brokerage_fee():
    brokerage_jpy = raw['brokerage_fee'].map(lambda value: parse_jpy_value(value, sentinel_as_zero=True))
    brokerage_months = raw['brokerage_fee'].map(parse_month_value)
    rent_jpy = raw['rent_price_text'].map(parse_jpy_value)
    estimated = pd.Series(brokerage_jpy).where(pd.Series(brokerage_jpy).notna(), pd.Series(brokerage_months) * pd.Series(rent_jpy))
    output_df = pd.DataFrame({
        'brokerage_fee_jpy': pd.array(brokerage_jpy, dtype='Int64'),
        'brokerage_fee_months': pd.array(brokerage_months, dtype='Float64'),
        'brokerage_fee_estimated_jpy': pd.array(estimated.round(), dtype='Int64'),
    })
    processed_outputs['brokerage_fee'] = output_df
    return output_df.head(10)

process_brokerage_fee()

   brokerage_fee_jpy  brokerage_fee_months  brokerage_fee_estimated_jpy
0               <NA>                  <NA>                         <NA>
1               <NA>                  <NA>                         <NA>
2               <NA>                  <NA>                         <NA>
3               <NA>                  <NA>                         <NA>
4               <NA>                  <NA>                         <NA>
5               <NA>                  <NA>                         <NA>
6               <NA>                  <NA>                         <NA>
7               <NA>                  <NA>                         <NA>
8               <NA>                  <NA>                         <NA>
9               <NA>                  <NA>                         <NA>

In [71]:
# Kiểm tra lại output sau xử lý của column `brokerage_fee`.
check_processed_column('brokerage_fee')

                 output_column  non_null  null_pct  unique_non_null
0            brokerage_fee_jpy      1311     92.69               13
1         brokerage_fee_months       204     98.86                4
2  brokerage_fee_estimated_jpy      1515     91.55              120

   brokerage_fee_jpy  brokerage_fee_months  brokerage_fee_estimated_jpy
0               <NA>                  <NA>                         <NA>
1               <NA>                  <NA>                         <NA>
2               <NA>                  <NA>                         <NA>
3               <NA>                  <NA>                         <NA>
4               <NA>                  <NA>                         <NA>
5               <NA>                  <NA>                         <NA>
6               <NA>                  <NA>                         <NA>
7               <NA>                  <NA>                         <NA>
8               <NA>                  <NA>                         <NA>
9               <NA>                  <NA>                         <NA>

--- brokerage_fee_jpy top values ---

                   count
brokerage_fee_jpy
<NA>               16616
0                   1296
134200                 3
85800                  2
110000                 1
341000                 1
148500                 1
66000                  1
121000                 1
132000                 1

--- brokerage_fee_months top values ---

                      count
brokerage_fee_months
<NA>                  17723
1.1                      93
0.55                     85
1.0                      16
0.5                      10

       brokerage_fee_jpy  brokerage_fee_months  brokerage_fee_estimated_jpy
0                   <NA>                  <NA>                         <NA>
1                   <NA>                  <NA>                         <NA>
2                   <NA>                  <NA>                         <NA>
3                   <NA>                  <NA>                         <NA>
4                   <NA>                  <NA>                         <NA>
...                  ...                   ...                          ...
17922               <NA>                  <NA>                         <NA>
17923               <NA>                  <NA>                         <NA>
17924               <NA>                  <NA>                         <NA>
17925               <NA>                  <NA>                         <NA>
17926               <NA>                  <NA>                         <NA>

[17927 rows x 3 columns]

#### `other_initial_costs`

ほか初期費用, các chi phí ban đầu khác như thay khóa, vệ sinh, bảo lãnh. Thường là free text có tổng tiền và chi tiết.

In [72]:
# Kiểm tra raw column `other_initial_costs` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'other_initial_costs')

                other_initial_costs
dtype                        object
rows                          17927
non_null                       9603
null_count                     8324
null_pct                      46.43
sentinel_count                    0
unique_non_null                2117

                               count
other_initial_costs
None                            8324
合計2.2万円(内訳:鍵交換代2.2万円)            516
合計3.3万円(内訳:鍵交換代3.3万円)            265
合計1.65万円(内訳:鍵交換代1.65万円)          236
合計2.2万円(内訳:カギ調整代(課税対象))          232
合計2.2万円(内訳:カギ交換費用22000円)         225
合計2.2万円(内訳:クリーニング代(課税対象))        175
合計2.2万円(内訳:鍵交換代 22000円税込)        146
合計2.2万円(内訳:鍵交換代(課税対象))           143
合計2.97万円(内訳:鍵交換代2.97万円)          140
合計2.75万円(内訳:鍵交換代2.75万円)          122
合計2.2万円(内訳:鍵調整代(課税対象))           114
合計2.2万円(内訳:ルームクリーニング代(課税対象))      81
合計2.75万円(内訳:鍵交換代/アクト安心ライフ24等)     77
合計1.65万円(内訳:鍵交換代(課税対象))           74

dtype              object
rows                17927
non_null             9603
null_count           8324
null_pct            46.43
sentinel_count          0
unique_non_null      2117
dtype: object

In [73]:
# Function xử lý riêng cho `other_initial_costs`: chỉ lấy tổng tiền từ prefix 合計...万円.
def process_other_initial_costs():
    output_df = pd.DataFrame({
        'other_initial_costs_total_jpy': pd.array(raw['other_initial_costs'].map(parse_initial_cost_total), dtype='Int64'),
    })
    processed_outputs['other_initial_costs'] = output_df
    return output_df.head(10)

process_other_initial_costs()

   other_initial_costs_total_jpy
0                           <NA>
1                           <NA>
2                           <NA>
3                           <NA>
4                           <NA>
5                           <NA>
6                           <NA>
7                           <NA>
8                           <NA>
9                           <NA>

In [74]:
# Kiểm tra lại output sau xử lý của column `other_initial_costs`.
check_processed_column('other_initial_costs')

                   output_column  non_null  null_pct  unique_non_null
0  other_initial_costs_total_jpy      9603     46.43              397

   other_initial_costs_total_jpy
0                           <NA>
1                           <NA>
2                           <NA>
3                           <NA>
4                           <NA>
5                           <NA>
6                           <NA>
7                           <NA>
8                           <NA>
9                           <NA>

       other_initial_costs_total_jpy
0                               <NA>
1                               <NA>
2                               <NA>
3                               <NA>
4                               <NA>
...                              ...
17922                           <NA>
17923                           <NA>
17924                           <NA>
17925                           <NA>
17926                           <NA>

[17927 rows x 1 columns]

#### `guarantee_company` — DEFERRED / SKIP PARSING

> **Trạng thái: tạm bỏ qua xử lý.** Giữ nguyên raw column và helper audit bên dưới để xem xét sau. Agent xử lý tiếp notebook không parse hoặc đưa cột này thành feature phân tích cho đến khi có rule đáng tin cậy.

保証会社, thông tin công ty bảo lãnh thuê nhà và điều kiện phí bảo lãnh.

In [75]:
# Kiểm tra raw column `guarantee_company` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'guarantee_company')

                guarantee_company
dtype                      object
rows                        17927
non_null                    14917
null_count                   3010
null_pct                    16.79
sentinel_count                  0
unique_non_null              3768

                                                           count
guarantee_company
None                                                        3010
保証会社利用必 要確認                                                  376
保証会社利用必 保証会社に基づく。                                            217
保証会社利用必 賃貸保証料 1ヶ月 1年 賃貸保証更新料 10000円                          206
保証会社利用必 都度、お問い合わせください。 都度、お問い合わせください。                        189
保証会社利用必 初回50%・毎月1.5%/外国籍(グローバルプラン)初回100%・毎月2%                165
保証会社利用必 管理会社指定                                               144
保証会社利用必 初回60%、更新時1万円/1年毎、月額保証料1%                             140
保証会社利用必 初回総賃料の50%、以後毎月更新で総賃料の1.5%                            125
保証会社利用必 初回総賃料50% 更新1.5%/月                                    123
保証会社利用必 初回保証料:総賃料50%、月額保証料:総賃料1.5%                           114
保証会社利用必 初回保証料:保証人有 総賃料50%、保証人無 総賃料70%、更新保証料:1万円/1年           109
保証会社利用必 保証会社加入要                                              102
保証会社利用必 プレサンスギャランティ(初回:総賃料50%、最低2万円、月額:総賃料の1.5%)または、日本セーフ     93
保証会社利用必 初回保証料:総賃料の50%                                         90

dtype              object
rows                17927
non_null            14917
null_count           3010
null_pct            16.79
sentinel_count          0
unique_non_null      3768
dtype: object

In [76]:
# DEFERRED/SKIP PARSING: giữ function này chỉ để audit coverage; chưa tạo feature phân tích.
def process_guarantee_company():
    """Audit raw text; KHÔNG phải parser guarantee company cho mart phân tích."""
    assert 'guarantee_company' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['guarantee_company'])
    output_df = pd.DataFrame({
        'guarantee_company_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'guarantee_company_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['guarantee_company'] = output_df
    return output_df.head(10)

process_guarantee_company()

   guarantee_company_present  guarantee_company_text_length
0                       True                             28
1                       True                             28
2                       True                             28
3                       True                             28
4                       True                             28
5                       True                             28
6                       True                             28
7                       True                             28
8                       True                             28
9                       True                             28

In [77]:
# Kiểm tra lại output sau xử lý của column `guarantee_company`.
check_processed_column('guarantee_company')

                   output_column  non_null  null_pct  unique_non_null
0      guarantee_company_present     17927      0.00                2
1  guarantee_company_text_length     14917     16.79              117

   guarantee_company_present  guarantee_company_text_length
0                       True                             28
1                       True                             28
2                       True                             28
3                       True                             28
4                       True                             28
5                       True                             28
6                       True                             28
7                       True                             28
8                       True                             28
9                       True                             28

--- guarantee_company_present top values ---

                           count
guarantee_company_present
True                       14917
False                       3010

       guarantee_company_present  guarantee_company_text_length
0                           True                             28
1                           True                             28
2                           True                             28
3                           True                             28
4                           True                             28
...                          ...                            ...
17922                      False                           <NA>
17923                      False                           <NA>
17924                      False                           <NA>
17925                      False                           <NA>
17926                      False                           <NA>

[17927 rows x 2 columns]

### Nhóm: Diện tích, layout, tầng và tuổi nhà

#### `layout`

間取り, kiểu bố trí phòng như 1R, 1K, 1DK, 1LDK. Đây là dimension quan trọng để so sánh căn hộ cùng phân khúc.

In [78]:
# Kiểm tra raw column `layout` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'layout')

                 layout
dtype            object
rows              17927
non_null          17927
null_count            0
null_pct            0.0
sentinel_count        0
unique_non_null      21

        count
layout
1K       7926
1LDK     4824
1DK      1769
ワンルーム    1533
2LDK      847
1SLDK     295
2DK       281
3LDK      215
2K        134
3DK        40
4LDK       20
2SLDK      15
4DK        10
4K          6
1SK         4

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null        21
dtype: object

In [79]:
# Function xử lý riêng cho `layout`: normalize 間取り, tách số phòng và flag service room.
def process_layout():
    parsed = raw['layout'].map(parse_layout)
    output_df = pd.DataFrame({
        'layout_normalized': parsed.map(lambda value: value[0]).astype('string'),
        'layout_room_count': pd.array(parsed.map(lambda value: value[1]), dtype='Int64'),
        'layout_has_service_room': pd.array(parsed.map(lambda value: value[2]), dtype='boolean'),
    })
    processed_outputs['layout'] = output_df
    return output_df.head(10)

process_layout()

  layout_normalized  layout_room_count  layout_has_service_room
0                1K                  1                    False
1                1K                  1                    False
2                1K                  1                    False
3                1K                  1                    False
4                1K                  1                    False
5                1K                  1                    False
6                1K                  1                    False
7                1K                  1                    False
8                1K                  1                    False
9                1K                  1                    False

In [80]:
# Kiểm tra lại output sau xử lý của column `layout`.
check_processed_column('layout')

             output_column  non_null  null_pct  unique_non_null
0        layout_normalized     17927       0.0               21
1        layout_room_count     17927       0.0                6
2  layout_has_service_room     17927       0.0                2

  layout_normalized  layout_room_count  layout_has_service_room
0                1K                  1                    False
1                1K                  1                    False
2                1K                  1                    False
3                1K                  1                    False
4                1K                  1                    False
5                1K                  1                    False
6                1K                  1                    False
7                1K                  1                    False
8                1K                  1                    False
9                1K                  1                    False

--- layout_normalized top values ---

                   count
layout_normalized
1K                  7926
1LDK                4824
1DK                 1769
1R                  1533
2LDK                 847
1SLDK                295
2DK                  281
3LDK                 215
2K                   134
3DK                   40

--- layout_room_count top values ---

                   count
layout_room_count
1                  16354
2                   1277
3                    258
4                     36
7                      1
5                      1

--- layout_has_service_room top values ---

                         count
layout_has_service_room
False                    17609
True                       318

      layout_normalized  layout_room_count  layout_has_service_room
0                    1K                  1                    False
1                    1K                  1                    False
2                    1K                  1                    False
3                    1K                  1                    False
4                    1K                  1                    False
...                 ...                ...                      ...
17922                1K                  1                    False
17923                1K                  1                    False
17924                1K                  1                    False
17925                1K                  1                    False
17926                1K                  1                    False

[17927 rows x 3 columns]

#### `layout_detail`

間取り詳細, chi tiết phòng như kích thước từng phòng. Có thể hữu ích sau này nhưng hiện là text nhiều biến thể.

In [81]:
# Kiểm tra raw column `layout_detail` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'layout_detail')

                layout_detail
dtype                  object
rows                    17927
non_null                17927
null_count                  0
null_pct                  0.0
sentinel_count           1754
unique_non_null          1970

               count
layout_detail
-               1754
洋6               862
洋6 K             452
K                416
洋6.2             305
洋7               271
洋2.5 DK6         243
LDK              233
洋8               224
洋6.5             216
洋7.2             210
洋7.3             176
洋6.8             167
洋8.1             157
洋4.4 LDK10.8     155

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       1754
unique_non_null      1970
dtype: object

In [82]:
# Function xử lý riêng cho `layout_detail`: parse feature tổng hợp và bảng layout_spaces một-nhiều.
def process_layout_detail():
    global layout_spaces

    parsed = raw['layout_detail'].map(parse_layout_detail)
    summary_rows = []
    component_rows = []
    for row_index, parsed_value in parsed.items():
        normalized, components, parse_status, failure_count = parsed_value
        if parse_status == 'missing':
            summary = {
                'layout_space_count': None,
                'western_room_count': None,
                'japanese_room_count': None,
                'service_room_count': None,
                'largest_private_room_jo': None,
                'kitchen_type': None,
                'kitchen_size_jo': None,
                'loft_present': None,
                'loft_size_jo': None,
            }
        else:
            summary = summarize_layout_detail_components(components)
        summary_rows.append({
            'layout_detail_clean': normalized,
            'layout_detail_parse_status': parse_status,
            'layout_detail_parse_failure_count': failure_count,
            **summary,
        })

        source_record = raw.loc[row_index]
        for space_order, component in enumerate(components, start=1):
            component_rows.append({
                'task_id': source_record['task_id'],
                'batch_id': source_record['batch_id'],
                'suumo_property_code': source_record['suumo_property_code'],
                'space_order': space_order,
                **component,
            })

    summary_df = pd.DataFrame(summary_rows, index=raw.index)
    output_df = pd.DataFrame({
        'layout_detail_clean': summary_df['layout_detail_clean'].astype('string'),
        'layout_detail_parse_status': summary_df['layout_detail_parse_status'].astype('string'),
        'layout_detail_parse_failure_count': pd.array(summary_df['layout_detail_parse_failure_count'], dtype='Int64'),
        'layout_space_count': pd.array(summary_df['layout_space_count'], dtype='Int64'),
        'western_room_count': pd.array(summary_df['western_room_count'], dtype='Int64'),
        'japanese_room_count': pd.array(summary_df['japanese_room_count'], dtype='Int64'),
        'service_room_count': pd.array(summary_df['service_room_count'], dtype='Int64'),
        'largest_private_room_jo': pd.array(summary_df['largest_private_room_jo'], dtype='Float64'),
        'kitchen_type': summary_df['kitchen_type'].astype('string'),
        'kitchen_size_jo': pd.array(summary_df['kitchen_size_jo'], dtype='Float64'),
        'loft_present': pd.array(summary_df['loft_present'], dtype='boolean'),
        'loft_size_jo': pd.array(summary_df['loft_size_jo'], dtype='Float64'),
    }, index=raw.index)

    layout_space_columns = [
        'task_id', 'batch_id', 'suumo_property_code', 'space_order',
        'space_label', 'space_type', 'size_jo', 'raw_token',
    ]
    layout_spaces = pd.DataFrame(component_rows, columns=layout_space_columns)
    if not layout_spaces.empty:
        layout_spaces['space_order'] = pd.array(layout_spaces['space_order'], dtype='Int64')
        layout_spaces['size_jo'] = pd.array(layout_spaces['size_jo'], dtype='Float64')

    processed_outputs['layout_detail'] = output_df
    return output_df.head(10)

process_layout_detail()

,layout_detail_clean,layout_detail_parse_status,layout_detail_parse_failure_count,layout_space_count,western_room_count,japanese_room_count,service_room_count,largest_private_room_jo,kitchen_type,kitchen_size_jo,loft_present,loft_size_jo
0,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
1,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
2,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
3,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
4,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
5,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
6,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
7,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
8,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
9,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>

In [83]:
# Kiểm tra lại output sau xử lý của column `layout_detail`.
check_processed_column('layout_detail')
print(f'Layout space rows: {len(layout_spaces):,}')
display(layout_spaces.head(20))

                        output_column  non_null  null_pct  unique_non_null
0                 layout_detail_clean     16173      9.78             1969
1          layout_detail_parse_status     17927      0.00                3
2   layout_detail_parse_failure_count     17927      0.00                2
3                  layout_space_count     16173      9.78                6
4                  western_room_count     16173      9.78                5
5                 japanese_room_count     16173      9.78                6
6                  service_room_count     16173      9.78                2
7             largest_private_room_jo     15345     14.40              168
8                        kitchen_type     11455     36.10                5
9                     kitchen_size_jo      9410     47.51              207
10                       loft_present     16173      9.78                2
11                       loft_size_jo        44     99.75               13

,layout_detail_clean,layout_detail_parse_status,layout_detail_parse_failure_count,layout_space_count,western_room_count,japanese_room_count,service_room_count,largest_private_room_jo,kitchen_type,kitchen_size_jo,loft_present,loft_size_jo
0,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
1,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
2,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
3,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
4,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
5,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
6,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
7,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
8,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>
9,洋8.1 K,full,0,2,1,0,0,8.1,K,<NA>,False,<NA>

--- layout_detail_parse_status top values ---

                            count
layout_detail_parse_status
full                        16144
missing                      1754
partial                        29

--- layout_detail_parse_failure_count top values ---

                                   count
layout_detail_parse_failure_count
0                                  17898
1                                     29

--- layout_space_count top values ---

                    count
layout_space_count
2                    9267
1                    5378
<NA>                 1754
3                    1288
4                     218
5                      20
8                       2

--- western_room_count top values ---

                    count
western_room_count
1                   14184
<NA>                 1754
0                     965
2                     940
3                      78
4                       6

--- japanese_room_count top values ---

                     count
japanese_room_count
0                    15675
<NA>                  1754
1                      410
2                       80
3                        5
4                        2
7                        1

--- service_room_count top values ---

                    count
service_room_count
0                   15906
<NA>                 1754
1                     267

--- kitchen_type top values ---

              count
kitchen_type
<NA>           6472
LDK            5662
K              3955
DK             1795
LD+K             38
D+K               5

--- loft_present top values ---

              count
loft_present
False         16126
<NA>           1754
True             47

--- loft_size_jo top values ---

              count
loft_size_jo
<NA>          17883
2.0               8
6.1               7
1.3               5
2.5               4
1.4               4
5.0               3
3.1               3
6.4               2
3.0               2

Layout space rows: 28,764

,task_id,batch_id,suumo_property_code,space_order,space_label,space_type,size_jo,raw_token
0,21525,217,100508459006,1,洋,western_room,8.1,洋8.1
1,21525,217,100508459006,2,K,kitchen,<NA>,K
2,21526,217,100508459054,1,洋,western_room,8.1,洋8.1
3,21526,217,100508459054,2,K,kitchen,<NA>,K
4,21527,217,100508459047,1,洋,western_room,8.1,洋8.1
5,21527,217,100508459047,2,K,kitchen,<NA>,K
6,21528,217,100508459049,1,洋,western_room,8.1,洋8.1
7,21528,217,100508459049,2,K,kitchen,<NA>,K
8,21529,217,100508459044,1,洋,western_room,8.1,洋8.1
9,21529,217,100508459044,2,K,kitchen,<NA>,K
10,21530,217,100508459056,1,洋,western_room,8.1,洋8.1
11,21530,217,100508459056,2,K,kitchen,<NA>,K
12,21531,217,100508459048,1,洋,western_room,8.1,洋8.1
13,21531,217,100508459048,2,K,kitchen,<NA>,K
14,21532,217,100508459045,1,洋,western_room,8.1,洋8.1
15,21532,217,100508459045,2,K,kitchen,<NA>,K
16,21533,217,100508459033,1,洋,western_room,8.1,洋8.1
17,21533,217,100508459033,2,K,kitchen,<NA>,K
18,21534,217,100508459004,1,洋,western_room,8.1,洋8.1
19,21534,217,100508459004,2,K,kitchen,<NA>,K

#### `exclusive_area_text`

専有面積, diện tích sử dụng riêng của căn hộ ở dạng text, ví dụ 25.66m2. Đây là diện tích dùng để tính giá thuê trên m2.

In [84]:
# Kiểm tra raw column `exclusive_area_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'exclusive_area_text')

                exclusive_area_text
dtype                        object
rows                          17927
non_null                      17927
null_count                        0
null_pct                        0.0
sentinel_count                    0
unique_non_null                1298

                     count
exclusive_area_text
21.89m2                568
25.67m2                477
21.09m2                406
40.75m2                381
21.9m2                 295
19.87m2                287
34.08m2                279
25.2m2                 267
25.66m2                265
46.13m2                174
23.48m2                169
23.2m2                 162
38.4m2                 157
31.75m2                149
28.69m2                148

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null      1298
dtype: object

In [85]:
# Function xử lý riêng cho `exclusive_area_text`: parse 専有面積 từ m2/m² sang số thực.
def process_exclusive_area_text():
    output_df = pd.DataFrame({'exclusive_area_m2': pd.array(raw['exclusive_area_text'].map(parse_area_m2), dtype='Float64')})
    processed_outputs['exclusive_area_text'] = output_df
    return output_df.head(10)

process_exclusive_area_text()

   exclusive_area_m2
0              25.66
1              25.66
2              25.66
3              25.66
4              25.66
5              25.66
6              25.66
7              25.66
8              25.66
9              25.66

In [86]:
# Kiểm tra lại output sau xử lý của column `exclusive_area_text`.
check_processed_column('exclusive_area_text')

       output_column  non_null  null_pct  unique_non_null
0  exclusive_area_m2     17927       0.0             1298

   exclusive_area_m2
0              25.66
1              25.66
2              25.66
3              25.66
4              25.66
5              25.66
6              25.66
7              25.66
8              25.66
9              25.66

       exclusive_area_m2
0                  25.66
1                  25.66
2                  25.66
3                  25.66
4                  25.66
...                  ...
17922              21.89
17923              21.89
17924              21.89
17925              21.89
17926              21.89

[17927 rows x 1 columns]

#### `building_age_text`

築年数, tuổi nhà dạng text. 新築 nghĩa là nhà mới xây; 築99年以上 nghĩa là ít nhất 99 năm chứ không phải giá trị chính xác.

In [87]:
# Kiểm tra raw column `building_age_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'building_age_text')

                building_age_text
dtype                      object
rows                        17927
non_null                    17927
null_count                      0
null_pct                      0.0
sentinel_count                  0
unique_non_null                72

                   count
building_age_text
新築                  5061
築2年                 1296
築3年                  674
築5年                  610
築19年                 574
築6年                  562
築7年                  556
築9年                  450
築11年                 416
築10年                 416
築4年                  395
築18年                 388
築20年                 316
築1年                  310
築8年                  307

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null        72
dtype: object

In [88]:
# Function xử lý riêng cho `building_age_text`: parse 築年数; 新築 = 0, 築99年以上 là lower bound.
def process_building_age_text():
    normalized = normalize_text_series(raw['building_age_text'])
    parsed_age = raw['building_age_text'].map(parse_building_age)
    output_df = pd.DataFrame({
        'building_age_years': pd.array(parsed_age, dtype='Int64'),
        'building_age_is_lower_bound': (parsed_age.notna() & normalized.str.endswith('以上', na=False)).astype('boolean'),
    })
    processed_outputs['building_age_text'] = output_df
    return output_df.sample(10)

process_building_age_text()

       building_age_years  building_age_is_lower_bound
14801                   3                        False
12030                   8                        False
2190                   24                        False
8022                   12                        False
1688                    0                        False
2700                    9                        False
4593                    9                        False
7124                    0                        False
7336                    8                        False
7973                    5                        False

In [89]:
# Kiểm tra lại output sau xử lý của column `building_age_text`.
check_processed_column('building_age_text')

                 output_column  non_null  null_pct  unique_non_null
0           building_age_years     17927       0.0               72
1  building_age_is_lower_bound     17927       0.0                2

   building_age_years  building_age_is_lower_bound
0                   0                        False
1                   0                        False
2                   0                        False
3                   0                        False
4                   0                        False
5                   0                        False
6                   0                        False
7                   0                        False
8                   0                        False
9                   0                        False

--- building_age_is_lower_bound top values ---

                             count
building_age_is_lower_bound
False                        17926
True                             1

       building_age_years  building_age_is_lower_bound
0                       0                        False
1                       0                        False
2                       0                        False
3                       0                        False
4                       0                        False
...                   ...                          ...
17922                   0                        False
17923                   0                        False
17924                   0                        False
17925                   1                        False
17926                   0                        False

[17927 rows x 2 columns]

#### `built_at_text`

築年月, năm/tháng xây dựng. Nếu source chỉ ghi năm thì phải giữ precision để không hiểu nhầm là tháng 1 thật.

In [90]:
# Kiểm tra raw column `built_at_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'built_at_text')

                built_at_text
dtype                  object
rows                    17927
non_null                17927
null_count                  0
null_pct                  0.0
sentinel_count              0
unique_non_null           611

               count
built_at_text
2026年7月         2329
2026年6月         1057
2026年8月          515
2026年3月          432
2025年2月          427
2025年3月          323
2025年8月          258
2026年2月          251
2017年2月          227
2020年3月          212
2026年4月          198
2020年9月          193
2018年3月          189
2026年1月          185
2024年8月          174

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null       611
dtype: object

In [91]:
# Function xử lý riêng cho `built_at_text`: parse 築年月 và ghi precision year/month.
def process_built_at_text():
    normalized = normalize_text_series(raw['built_at_text'])
    built_at = raw['built_at_text'].map(parse_year_month)
    precision = pd.Series(pd.NA, index=raw.index, dtype='string')
    precision.loc[built_at.notna() & normalized.str.fullmatch(r'[0-9]{4}年', na=False)] = 'year'
    precision.loc[built_at.notna() & normalized.str.fullmatch(r'[0-9]{4}年[0-9]{1,2}月', na=False)] = 'month'
    output_df = pd.DataFrame({
        'built_at': built_at,
        'built_at_precision': precision,
    })
    processed_outputs['built_at_text'] = output_df
    return output_df.head(10)

process_built_at_text()

    built_at built_at_precision
0 2026-07-01              month
1 2026-07-01              month
2 2026-07-01              month
3 2026-07-01              month
4 2026-07-01              month
5 2026-07-01              month
6 2026-07-01              month
7 2026-07-01              month
8 2026-07-01              month
9 2026-07-01              month

In [92]:
# Kiểm tra lại output sau xử lý của column `built_at_text`.
check_processed_column('built_at_text')

        output_column  non_null  null_pct  unique_non_null
0            built_at     17927       0.0              607
1  built_at_precision     17927       0.0                2

    built_at built_at_precision
0 2026-07-01              month
1 2026-07-01              month
2 2026-07-01              month
3 2026-07-01              month
4 2026-07-01              month
5 2026-07-01              month
6 2026-07-01              month
7 2026-07-01              month
8 2026-07-01              month
9 2026-07-01              month

--- built_at_precision top values ---

                    count
built_at_precision
month               17921
year                    6

        built_at built_at_precision
0     2026-07-01              month
1     2026-07-01              month
2     2026-07-01              month
3     2026-07-01              month
4     2026-07-01              month
...          ...                ...
17922 2026-07-01              month
17923 2026-07-01              month
17924 2026-07-01              month
17925 2026-07-01              month
17926 2026-07-01              month

[17927 rows x 2 columns]

#### `floor_text`

階, tầng của căn hộ. Có thể là một tầng cụ thể như 3階 hoặc range như 1-3階 đối với nhà nhiều tầng.

In [93]:
# Kiểm tra raw column `floor_text` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'floor_text')

                floor_text
dtype               object
rows                 17927
non_null             17927
null_count               0
null_pct               0.0
sentinel_count          13
unique_non_null         33

            count
floor_text
3階           2320
2階           2314
4階           1942
6階           1548
5階           1530
7階           1485
9階           1300
8階           1295
10階           949
1階            785
11階           671
12階           610
13階           469
14階           310
15階           251

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count         13
unique_non_null        33
dtype: object

In [94]:
# Các listing trải trên nhiều tầng: xem loại nhà, layout và tổng số tầng từ raw.
floor_text_normalized = analysis_raw['floor_text'].map(normalize_text_for_profile).astype('string')
floor_range_mask = floor_text_normalized.str.fullmatch(r'\d+\s*-\s*\d+階', na=False)
floor_range_columns = [
    'task_id', 'suumo_property_code', 'floor_text', 'building_floors',
    'building_type', 'structure', 'layout', 'layout_detail',
    'exclusive_area_text', 'total_units', 'address',
]
floor_range_listings = (
    analysis_raw.loc[floor_range_mask, floor_range_columns]
    .sort_values(['building_type', 'floor_text', 'task_id'])
    .reset_index(drop=True)
)
print(f'Listing có khoảng tầng: {len(floor_range_listings):,}')
display(floor_range_listings['building_type'].value_counts(dropna=False).to_frame('count'))
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', 100):
    display(floor_range_listings)

Listing có khoảng tầng: 31

               count
building_type
一戸建て              13
テラス・タウンハウス        12
アパート               4
その他                1
マンション              1

,task_id,suumo_property_code,floor_text,building_floors,building_type,structure,layout,layout_detail,exclusive_area_text,total_units,address
0,6262,100517967451,1-2階,1-2階/地上2階建,その他,木造,1LDK,洋3.8 LDK11.2,84.34m2,-,大阪府大阪市淀川区加島１
1,9862,100520401873,1-2階,1-2階/2階建,アパート,木造,1LDK,洋11.5 LDK18.5 ロフト 5,69.73m2,-,大阪府大阪市淀川区木川西２
2,16870,100520038679,1-2階,1-2階/2階建,アパート,木造,1LDK,洋11.5 LDK18.5,69.73m2,-,大阪府大阪市淀川区木川西２
3,8619,100517686384,1-3階,1-3階/3階建,アパート,木造,3LDK,-,79.38m2,-,大阪府大阪市淀川区田川北２
4,16772,100510396109,1-3階,1-3階/3階建,アパート,木造,1LDK,洋12.5 LDK17.7,111.63m2,-,大阪府大阪市淀川区東三国４
5,4960,100519201036,1-2階,1-2階/地上2階建,テラス・タウンハウス,木造,4DK,和6 和6 和3 洋4.5,52.89m2,-,大阪府大阪市淀川区東三国４
6,6764,100519092906,1-2階,1-2階/地上2階建,テラス・タウンハウス,木造,1LDK,洋11.5 LDK18.5,69.73m2,-,大阪府大阪市淀川区木川西２
7,8642,100508895255,1-2階,1-2階/地上2階建,テラス・タウンハウス,木造,4K,和6 和6 洋4 洋2 K4.0,53.45m2,1戸,大阪府大阪市淀川区十八条３
8,14327,100510340291,1-2階,1-2階/地上3階建,テラス・タウンハウス,木造,1SLDK,洋12.5 LDK17.7 納戸 3.2,111.63m2,3戸,大阪府大阪市淀川区東三国４
9,21609,100505481903,1-2階,1-2階/地上2階建,テラス・タウンハウス,木造,4K,和6 和6 洋4 洋2 K4.0,53.45m2,1戸,大阪府大阪市淀川区十八条３
10,6213,100519595168,1-3階,1-3階/地上3階建,テラス・タウンハウス,木造,1LDK,洋12.5 LDK17.7,111.63m2,-,大阪府大阪市淀川区東三国４
11,6297,100493979229,1-3階,1-3階/地上3階建,テラス・タウンハウス,その他,3LDK,LDK,79.38m2,-,大阪府大阪市淀川区田川北２
12,6328,100508636466,1-3階,1-3階/地上3階建,テラス・タウンハウス,その他,3LDK,洋8 洋8 LDK,79.38m2,-,大阪府大阪市淀川区田川北２
13,6348,100508607069,1-3階,1-3階/地上3階建,テラス・タウンハウス,その他,3LDK,LDK,79.38m2,-,大阪府大阪市淀川区田川北２
14,6382,100508607067,1-3階,1-3階/地上3階建,テラス・タウンハウス,その他,3LDK,洋8 洋8 LDK,79.38m2,-,大阪府大阪市淀川区田川北２
15,8587,100510134188,1-3階,1-3階/地上3階建,テラス・タウンハウス,木造,1LDK,洋12.5 LDK17.7 納戸 23.3-3.2,111.16m2,-,大阪府大阪市淀川区東三国４
16,17592,100519780866,1-3階,1-3階/地上3階建,テラス・タウンハウス,木造,1LDK,洋12.5 LDK17.7,111.63m2,-,大阪府大阪市淀川区東三国４
17,8637,100487731991,2-3階,2-3階/3階建,マンション,鉄骨,2LDK,洋6.1 洋5.3 LDK11.1,54m2,-,大阪府大阪市淀川区西三国４
18,3973,100500030267,1-2階,1-2階/地上2階建,一戸建て,木造,1LDK,洋11.5 LDK18.5 ロフト 5,69.73m2,-,大阪府大阪市淀川区木川西２
19,5253,100508895286,1-2階,1-2階/地上2階建,一戸建て,木造,4K,和6 和6 和6 和4.5,58.32m2,-,大阪府大阪市淀川区東三国５
20,11249,100500035083,1-2階,1-2階/地上2階建,一戸建て,木造,1LDK,洋11.5 LDK18.5 ロフト 5,69.73m2,-,大阪府大阪市淀川区木川西２
21,6314,100508836951,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,-,79.38m2,-,大阪府大阪市淀川区田川北２
22,6347,100510206304,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,洋8 洋8,79.38m2,1戸,大阪府大阪市淀川区田川北２
23,6381,100510206326,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,洋8 洋8,79.38m2,1戸,大阪府大阪市淀川区田川北２
24,6690,100516130205,1-3階,1-3階/地上3階建,一戸建て,鉄骨,4DK,DK,74.02m2,-,大阪府大阪市淀川区塚本４
25,14383,100514570407,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,洋8 洋8,79.38m2,-,大阪府大阪市淀川区田川北２
26,16566,100520657380,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,-,104.08m2,-,大阪府大阪市淀川区東三国２
27,17466,100520115269,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,和4.1 洋5.2 洋4.5 LDK19.2,104.08m2,-,大阪府大阪市淀川区東三国２
28,17648,100508836947,1-3階,1-3階/地上3階建,一戸建て,木造,3LDK,洋8 洋8,79.38m2,-,大阪府大阪市淀川区田川北２
29,19856,100515931222,1-3階,1-3階/地上3階建,一戸建て,木造,1LDK,洋12.5 LDK17.7,111.63m2,3戸,大阪府大阪市淀川区東三国４
30,8674,100485723780,1-4階,1-4階/地上4階建,一戸建て,鉄骨,7LDK,和8 和8 和6 洋18 洋13 洋12 洋10 LDK27,311.44m2,-,大阪府大阪市淀川区野中北１

In [95]:
# Function xử lý riêng cho `floor_text`: parse tầng đơn hoặc range tầng thành floor_min/floor_max/floor_number.
def process_floor_text():
    parsed = raw['floor_text'].map(parse_floor_range)
    floor_min = pd.Series(parsed.map(lambda value: value[0]), index=raw.index)
    floor_max = pd.Series(parsed.map(lambda value: value[1]), index=raw.index)
    output_df = pd.DataFrame({
        'floor_min': pd.array(floor_min, dtype='Int64'),
        'floor_max': pd.array(floor_max, dtype='Int64'),
        'floor_number': pd.array(floor_min.where(floor_min == floor_max), dtype='Int64'),
    }, index=raw.index)
    processed_outputs['floor_text'] = output_df
    return output_df.head(10)

process_floor_text()

   floor_min  floor_max  floor_number
0          5          5             5
1          5          5             5
2          7          7             7
3          7          7             7
4          8          8             8
5          8          8             8
6          9          9             9
7          9          9             9
8         10         10            10
9         10         10            10

In [96]:
# Kiểm tra lại output sau xử lý của column `floor_text`.
check_processed_column('floor_text')

  output_column  non_null  null_pct  unique_non_null
0     floor_min     17914      0.07               27
1     floor_max     17914      0.07               27
2  floor_number     17883      0.25               27

   floor_min  floor_max  floor_number
0          5          5             5
1          5          5             5
2          7          7             7
3          7          7             7
4          8          8             8
5          8          8             8
6          9          9             9
7          9          9             9
8         10         10            10
9         10         10            10

--- floor_min top values ---

           count
floor_min
3           2321
2           2315
4           1942
6           1548
5           1530
7           1485
9           1300
8           1295
10           949
1            815

--- floor_max top values ---

           count
floor_max
3           2340
2           2325
4           1943
6           1548
5           1530
7           1485
9           1300
8           1295
10           949
1            785

--- floor_number top values ---

              count
floor_number
3              2321
2              2314
4              1942
6              1548
5              1530
7              1485
9              1300
8              1295
10              949
1               785

       floor_min  floor_max  floor_number
0              5          5             5
1              5          5             5
2              7          7             7
3              7          7             7
4              8          8             8
...          ...        ...           ...
17922         12         12            12
17923         12         12            12
17924         13         13            13
17925         13         13            13
17926         13         13            13

[17927 rows x 3 columns]

#### `building_floors`

階建, tổng số tầng của tòa nhà hoặc mô tả kiểu 3階/10階建. Dùng để biết căn hộ nằm trong tòa cao bao nhiêu tầng.

In [97]:
# Kiểm tra raw column `building_floors` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'building_floors')

                building_floors
dtype                    object
rows                      17927
non_null                  17927
null_count                    0
null_pct                    0.0
sentinel_count                0
unique_non_null             254

                 count
building_floors
3階/10階建            488
7階/10階建            468
9階/10階建            464
4階/10階建            462
2階/10階建            423
10階/10階建           396
6階/10階建            384
8階/10階建            352
2階/3階建             322
3階/3階建             319
9階/15階建            306
12階/15階建           301
7階/15階建            275
6階/15階建            272
1階/3階建             272

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null       254
dtype: object

In [98]:
# Function xử lý riêng cho `building_floors`: parse tổng số tầng tòa nhà từ 階建.
def process_building_floors():
    output_df = pd.DataFrame({'building_total_floors': pd.array(raw['building_floors'].map(parse_building_total_floors), dtype='Int64')})
    processed_outputs['building_floors'] = output_df
    return output_df.head(10)

process_building_floors()

   building_total_floors
0                     10
1                     10
2                     10
3                     10
4                     10
5                     10
6                     10
7                     10
8                     10
9                     10

In [99]:
# Kiểm tra lại output sau xử lý của column `building_floors`.
check_processed_column('building_floors')

           output_column  non_null  null_pct  unique_non_null
0  building_total_floors     17927       0.0               24

   building_total_floors
0                     10
1                     10
2                     10
3                     10
4                     10
5                     10
6                     10
7                     10
8                     10
9                     10

--- building_total_floors top values ---

                       count
building_total_floors
10                      3736
15                      3561
12                      1491
11                      1243
13                      1216
3                        997
14                       959
8                        875
9                        845
5                        762

       building_total_floors
0                         10
1                         10
2                         10
3                         10
4                         10
...                      ...
17922                     15
17923                     15
17924                     15
17925                     15
17926                     15

[17927 rows x 1 columns]

#### `total_units`

総戸数, tổng số căn/hộ trong tòa nhà nếu source cung cấp. Có thể phản ánh quy mô tòa nhà.

In [100]:
# Kiểm tra raw column `total_units` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'total_units')

                total_units
dtype                object
rows                  17927
non_null              17927
null_count                0
null_pct                0.0
sentinel_count         8283
unique_non_null         184

             count
total_units
-             8283
168戸           810
70戸            650
36戸            629
63戸            474
90戸            387
108戸           384
72戸            336
224戸           221
19戸            211
9戸             180
91戸            175
46戸            168
84戸            147
12戸            128

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       8283
unique_non_null       184
dtype: object

In [101]:
# Function xử lý riêng cho `total_units`: parse 総戸数 từ dạng 123戸 sang số căn.
def process_total_units():
    output_df = pd.DataFrame({'total_units_count': pd.array(raw['total_units'].map(parse_total_units), dtype='Int64')})
    processed_outputs['total_units'] = output_df
    return output_df.head(10)

process_total_units()

   total_units_count
0                 19
1                 19
2                 19
3                 19
4                 19
5                 19
6                 19
7                 19
8                 19
9                 19

In [102]:
# Kiểm tra lại output sau xử lý của column `total_units`.
check_processed_column('total_units')

       output_column  non_null  null_pct  unique_non_null
0  total_units_count      9644      46.2              183

   total_units_count
0                 19
1                 19
2                 19
3                 19
4                 19
5                 19
6                 19
7                 19
8                 19
9                 19

       total_units_count
0                     19
1                     19
2                     19
3                     19
4                     19
...                  ...
17922               <NA>
17923               <NA>
17924               <NA>
17925               <NA>
17926               <NA>

[17927 rows x 1 columns]

### Nhóm: Loại tòa nhà, kết cấu và hướng

#### `building_type`

建物種別, loại bất động sản như mansion/apartment. Ở Nhật マンション thường là chung cư/kết cấu kiên cố hơn apartment nhỏ.

In [103]:
# Kiểm tra raw column `building_type` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'building_type')

                building_type
dtype                  object
rows                    17927
non_null                17927
null_count                  0
null_pct                  0.0
sentinel_count              0
unique_non_null             5

               count
building_type
マンション          17056
アパート             755
一戸建て              78
テラス・タウンハウス        28
その他               10

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null         5
dtype: object

In [104]:
# Function xử lý riêng cho `building_type`: normalize loại tòa nhà và đổi sentinel thành null.
def process_building_type():
    output_df = pd.DataFrame({'building_type_clean': clean_categorical(raw['building_type'])})
    processed_outputs['building_type'] = output_df
    return output_df.head(10)

process_building_type()

  building_type_clean
0               マンション
1               マンション
2               マンション
3               マンション
4               マンション
5               マンション
6               マンション
7               マンション
8               マンション
9               マンション

In [105]:
# Kiểm tra lại output sau xử lý của column `building_type`.
check_processed_column('building_type')

         output_column  non_null  null_pct  unique_non_null
0  building_type_clean     17927       0.0                5

  building_type_clean
0               マンション
1               マンション
2               マンション
3               マンション
4               マンション
5               マンション
6               マンション
7               マンション
8               マンション
9               マンション

--- building_type_clean top values ---

                     count
building_type_clean
マンション                17056
アパート                   755
一戸建て                    78
テラス・タウンハウス              28
その他                     10

      building_type_clean
0                   マンション
1                   マンション
2                   マンション
3                   マンション
4                   マンション
...                   ...
17922               マンション
17923               マンション
17924               マンション
17925               マンション
17926               マンション

[17927 rows x 1 columns]

#### `structure`

構造, kết cấu tòa nhà như RC, SRC, thép, gỗ. Có thể ảnh hưởng chất lượng, cách âm, tuổi thọ và giá thuê.

In [106]:
# Kiểm tra raw column `structure` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'structure')

                structure
dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null         9

           count
structure
鉄筋コン       14132
鉄骨          1838
鉄骨鉄筋        1107
木造           612
軽量鉄骨         122
気泡コン          62
その他           33
プレコン          17
ブロック           4

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count          0
unique_non_null         9
dtype: object

In [107]:
# Function xử lý riêng cho `structure`: normalize kết cấu tòa nhà và đổi sentinel thành null.
def process_structure():
    output_df = pd.DataFrame({'structure_clean': clean_categorical(raw['structure'])})
    processed_outputs['structure'] = output_df
    return output_df.head(10)

process_structure()

  structure_clean
0              鉄骨
1              鉄骨
2              鉄骨
3              鉄骨
4              鉄骨
5              鉄骨
6              鉄骨
7              鉄骨
8              鉄骨
9              鉄骨

In [108]:
# Kiểm tra lại output sau xử lý của column `structure`.
check_processed_column('structure')

     output_column  non_null  null_pct  unique_non_null
0  structure_clean     17927       0.0                9

  structure_clean
0              鉄骨
1              鉄骨
2              鉄骨
3              鉄骨
4              鉄骨
5              鉄骨
6              鉄骨
7              鉄骨
8              鉄骨
9              鉄骨

--- structure_clean top values ---

                 count
structure_clean
鉄筋コン             14132
鉄骨                1838
鉄骨鉄筋              1107
木造                 612
軽量鉄骨               122
気泡コン                62
その他                 33
プレコン                17
ブロック                 4

      structure_clean
0                  鉄骨
1                  鉄骨
2                  鉄骨
3                  鉄骨
4                  鉄骨
...               ...
17922            鉄筋コン
17923            鉄筋コン
17924            鉄筋コン
17925            鉄筋コン
17926            鉄筋コン

[17927 rows x 1 columns]

#### `direction`

向き, hướng ban công/cửa chính của căn hộ như Nam, Đông, Tây. Có thể ảnh hưởng ánh sáng và giá.

In [109]:
# Kiểm tra raw column `direction` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'direction')

                direction
dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       1926
unique_non_null         9

           count
direction
南           5020
西           3487
東           3150
北           2058
-           1926
南東           924
北西           587
南西           511
北東           264

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       1926
unique_non_null         9
dtype: object

In [110]:
# Function xử lý riêng cho `direction`: normalize hướng căn hộ và đổi sentinel thành null.
def process_direction():
    output_df = pd.DataFrame({'direction_clean': clean_categorical(raw['direction'])})
    processed_outputs['direction'] = output_df
    return output_df.head(10)

process_direction()

  direction_clean
0               西
1               西
2               西
3               西
4               西
5               西
6               西
7               西
8               西
9               西

In [111]:
# Kiểm tra lại output sau xử lý của column `direction`.
check_processed_column('direction')

     output_column  non_null  null_pct  unique_non_null
0  direction_clean     16001     10.74                8

  direction_clean
0               西
1               西
2               西
3               西
4               西
5               西
6               西
7               西
8               西
9               西

--- direction_clean top values ---

                 count
direction_clean
南                 5020
西                 3487
東                 3150
北                 2058
<NA>              1926
南東                 924
北西                 587
南西                 511
北東                 264

      direction_clean
0                   西
1                   西
2                   西
3                   西
4                   西
...               ...
17922               東
17923               東
17924               東
17925               東
17926               東

[17927 rows x 1 columns]

### Nhóm: Điều kiện thuê, bảo hiểm và bãi đỗ xe

#### `conditions`

> **DEFERRED/SKIP:** Tạm bỏ qua xử lý conditions. Giữ raw và helper audit coverage bên dưới; không tạo conditions_clean hay các policy flag cho mart. Agent sau chỉ mở lại khi có rule phân loại điều kiện thuê được kiểm chứng.

条件, điều kiện thuê như pet, người ở, loại khách thuê, hoặc các điều kiện đặc biệt. Coverage không đầy đủ nên cần dùng thận trọng.

In [112]:
# Kiểm tra raw column `conditions` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'conditions')

                conditions
dtype               object
rows                 17927
non_null             17927
null_count               0
null_pct               0.0
sentinel_count        7572
unique_non_null        256

                    count
conditions
-                    7572
二人入居可                1943
ペット相談                1912
二人入居可/ペット相談          1612
二人入居可/子供可/ペット相談       649
事務所利用不可               513
単身者可                  476
二人入居可/子供可             307
二人入居可/子供可/ルームシェア相談    305
二人入居可/事務所利用不可         220
単身者可/二人入居可            181
ペット相談/事務所利用不可         150
単身者可/ペット相談            124
事務所利用相談               123
単身者可/二人入居可/ペット相談       93

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       7572
unique_non_null       256
dtype: object

In [113]:
# DEFERRED/SKIP PARSING: chỉ audit coverage; không tạo feature điều kiện thuê cho mart.
def process_conditions():
    """Giữ hàm để rà soát sau; hiện không parse nội dung conditions."""
    assert 'conditions' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['conditions'])
    output_df = pd.DataFrame({
        'conditions_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'conditions_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['conditions'] = output_df
    return output_df.head(10)

process_conditions()

   conditions_present  conditions_text_length
0                True                       5
1                True                       5
2                True                       5
3                True                       5
4                True                       5
5                True                       5
6                True                       5
7                True                       5
8                True                       5
9                True                       5

In [114]:
# Chỉ kiểm tra audit coverage của conditions; chưa có feature phân tích.
check_processed_column('conditions')

            output_column  non_null  null_pct  unique_non_null
0      conditions_present     17927       0.0                2
1  conditions_text_length     17927       0.0               39

   conditions_present  conditions_text_length
0                True                       5
1                True                       5
2                True                       5
3                True                       5
4                True                       5
5                True                       5
6                True                       5
7                True                       5
8                True                       5
9                True                       5

--- conditions_present top values ---

                    count
conditions_present
True                10355
False                7572

       conditions_present  conditions_text_length
0                    True                       5
1                    True                       5
2                    True                       5
3                    True                       5
4                    True                       5
...                   ...                     ...
17922               False                       1
17923               False                       1
17924               False                       1
17925               False                       1
17926               False                       1

[17927 rows x 2 columns]

#### `insurance`

損保, bảo hiểm tài sản/hỏa hoạn khi thuê nhà. Có thể ghi cần bảo hiểm, số tiền, và kỳ hạn như 1.8万円2年.

Số tiền là phí cho kỳ hạn được ghi, không phải phí hàng tháng. Dấu - nghĩa là thiếu thông tin, không phải không cần bảo hiểm; chưa tự động cộng phí này vào chi phí ban đầu.

In [115]:
# Kiểm tra raw column `insurance` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'insurance')

                insurance
dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       1696
unique_non_null       125

           count
insurance
要           7742
2万円2年       2171
1.8万円2年     1762
-           1696
1.1万円1年      747
1.6万円2年      583
2.2万円2年      580
2.4万円2年      430
1.5万円2年      410
1万円1年        355
1.66万円2年     319
1.7万円2年      193
1.3万円2年      164
1.9万円2年       94
2.15万円2年      68

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       1696
unique_non_null       125
dtype: object

In [116]:
# Function xử lý riêng cho `insurance`: parse yêu cầu bảo hiểm, số tiền và kỳ hạn bảo hiểm.
def process_insurance():
    parsed = raw['insurance'].map(parse_insurance)
    output_df = pd.DataFrame({
        'insurance_required': pd.array(parsed.map(lambda value: value[0]), dtype='boolean'),
        'insurance_jpy': pd.array(parsed.map(lambda value: value[1]), dtype='Int64'),
        'insurance_period_years': pd.array(parsed.map(lambda value: value[2]), dtype='Int64'),
    })
    processed_outputs['insurance'] = output_df
    return output_df.sample(10)

process_insurance()

       insurance_required  insurance_jpy  insurance_period_years
4578                 True           <NA>                    <NA>
16457                True          20000                       2
16025                True           <NA>                    <NA>
467                  True          20000                       2
16876                True          16000                       2
8885                 <NA>           <NA>                    <NA>
1720                 True          20000                       2
3460                 True          24000                       2
10920                True          22000                       2
10313                True          20000                       2

In [117]:
# Kiểm tra output và liệt kê giá trị có nội dung nhưng parser chưa hiểu.
check_processed_column('insurance')
insurance_normalized = normalize_text_series(raw['insurance'])
insurance_unparsed_mask = (
    insurance_normalized.notna()
    & ~insurance_normalized.isin(NULL_SENTINELS)
    & processed_outputs['insurance']['insurance_required'].isna()
)
print(f'Insurance values chưa parse được: {insurance_unparsed_mask.sum():,}')
display(insurance_normalized.loc[insurance_unparsed_mask].value_counts().to_frame('count'))

            output_column  non_null  null_pct  unique_non_null
0      insurance_required     16231      9.46                1
1           insurance_jpy      8489     52.65              100
2  insurance_period_years      8448     52.88                3

   insurance_required  insurance_jpy  insurance_period_years
0                True           <NA>                    <NA>
1                True           <NA>                    <NA>
2                True           <NA>                    <NA>
3                True           <NA>                    <NA>
4                True           <NA>                    <NA>
5                True           <NA>                    <NA>
6                True           <NA>                    <NA>
7                True           <NA>                    <NA>
8                True           <NA>                    <NA>
9                True           <NA>                    <NA>

--- insurance_required top values ---

                    count
insurance_required
True                16231
<NA>                 1696

--- insurance_period_years top values ---

                        count
insurance_period_years
<NA>                     9479
2                        7233
1                        1214
3                           1

Insurance values chưa parse được: 0

Empty DataFrame
Columns: [count]
Index: []

#### `parking`

駐車場, thông tin chỗ đỗ xe. Dấu - nghĩa là thiếu thông tin, không phải không có chỗ đỗ. 付無料 là miễn phí; giá ghi trong raw không được tự động cộng vào tiền thuê.

Quy tắc parking_max_spaces: chỉ 駐2台可 → 2, 駐3台可 → 3; không có mục 台可 → null. Kiểu chỗ đỗ như 屋内駐 được giữ riêng trong parking_detail.

In [118]:
# Kiểm tra raw column `parking` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'parking')

                parking
dtype            object
rows              17927
non_null          17927
null_count            0
null_pct            0.0
sentinel_count     6991
unique_non_null     507

               count
parking
-               6991
敷地内27500円        655
敷地内22000円        638
敷地内33000円        633
敷地内20000円        468
近隣200m22000円     451
近隣100m22000円     303
敷地内23000円        283
敷地内19800円        243
敷地内20000円/屋内駐    242
近隣100m18000円     222
近隣300m18700円     213
近隣100m27500円     209
敷地内16000円        198
敷地内23000円/平置駐    175

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count       6991
unique_non_null       507
dtype: object

In [119]:
# Function xử lý riêng cho `parking`: tách vị trí, khoảng cách, giá, kiểu chỗ đỗ và số xe.
def process_parking():
    parsed = raw['parking'].map(parse_parking)
    output_df = pd.DataFrame({
        'parking_listed': pd.array(parsed.map(lambda value: value[0]), dtype='boolean'),
        'parking_location': parsed.map(lambda value: value[1]).astype('string'),
        'parking_distance_m': pd.array(parsed.map(lambda value: value[2]), dtype='Int64'),
        'parking_fee_jpy': pd.array(parsed.map(lambda value: value[3]), dtype='Int64'),
        'parking_detail': parsed.map(lambda value: value[4]).astype('string'),
        'parking_max_spaces': pd.array(parsed.map(lambda value: value[5]), dtype='Int64'),
    })
    processed_outputs['parking'] = output_df
    return output_df.head(10)

process_parking()

,parking_listed,parking_location,parking_distance_m,parking_fee_jpy,parking_detail,parking_max_spaces
0,True,onsite,<NA>,16000,<NA>,<NA>
1,True,onsite,<NA>,16000,<NA>,<NA>
2,True,onsite,<NA>,16000,<NA>,<NA>
3,True,onsite,<NA>,16000,<NA>,<NA>
4,True,onsite,<NA>,16000,<NA>,<NA>
5,True,onsite,<NA>,16000,<NA>,<NA>
6,True,onsite,<NA>,16000,<NA>,<NA>
7,True,onsite,<NA>,16000,<NA>,<NA>
8,True,onsite,<NA>,16000,<NA>,<NA>
9,True,onsite,<NA>,16000,<NA>,<NA>

In [120]:
# Kiểm tra output và liệt kê giá trị có nội dung nhưng parser chưa hiểu.
check_processed_column('parking')
parking_normalized = normalize_text_series(raw['parking'])
parking_unparsed_mask = (
    parking_normalized.notna()
    & ~parking_normalized.isin(NULL_SENTINELS)
    & processed_outputs['parking']['parking_listed'].isna()
)
print(f'Parking values chưa parse được: {parking_unparsed_mask.sum():,}')
display(parking_normalized.loc[parking_unparsed_mask].value_counts().to_frame('count'))

        output_column  non_null  null_pct  unique_non_null
0      parking_listed     10936     39.00                1
1    parking_location     10936     39.00                3
2  parking_distance_m      4212     76.50               39
3     parking_fee_jpy     10662     40.53              112
4      parking_detail      1710     90.46                7
5  parking_max_spaces        84     99.53                2

,parking_listed,parking_location,parking_distance_m,parking_fee_jpy,parking_detail,parking_max_spaces
0,True,onsite,<NA>,16000,<NA>,<NA>
1,True,onsite,<NA>,16000,<NA>,<NA>
2,True,onsite,<NA>,16000,<NA>,<NA>
3,True,onsite,<NA>,16000,<NA>,<NA>
4,True,onsite,<NA>,16000,<NA>,<NA>
5,True,onsite,<NA>,16000,<NA>,<NA>
6,True,onsite,<NA>,16000,<NA>,<NA>
7,True,onsite,<NA>,16000,<NA>,<NA>
8,True,onsite,<NA>,16000,<NA>,<NA>
9,True,onsite,<NA>,16000,<NA>,<NA>

--- parking_listed top values ---

                count
parking_listed
True            10936
<NA>             6991

--- parking_location top values ---

                  count
parking_location
<NA>               6991
onsite             6364
nearby             4212
unspecified         360

--- parking_detail top values ---

                count
parking_detail
<NA>            16217
平置駐               854
屋内駐               814
平置屋根付駐             21
屋根付駐               11
機械式駐                7
リモコンシャッタ付駐          2
シャッタ付屋内駐            1

--- parking_max_spaces top values ---

                    count
parking_max_spaces
<NA>                17843
3                      66
2                      18

Parking values chưa parse được: 0

Empty DataFrame
Columns: [count]
Index: []

### Nhóm: Năng lượng và tiện ích dự kiến

#### `energy_efficiency`

> **DEFERRED/SKIP:** Tạm bỏ qua xử lý energy_efficiency. Giữ raw và helper audit coverage; không tạo feature phân tích hay đưa vào mart. Snapshot hiện chỉ có 1/17.927 dòng khác sentinel.

エネルギー消費性能, hiệu suất tiêu thụ năng lượng. Snapshot hiện gần như chỉ có sentinel thiếu dữ liệu nên chưa có giá trị phân tích.

In [121]:
# Kiểm tra raw column `energy_efficiency` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'energy_efficiency')

                energy_efficiency
dtype                      object
rows                        17927
non_null                    17927
null_count                      0
null_pct                      0.0
sentinel_count              17926
unique_non_null                 2

                   count
energy_efficiency
-                  17926
★★★★★★(削減率50%達成)       1

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      17926
unique_non_null         2
dtype: object

In [122]:
# DEFERRED/SKIP PARSING: chỉ audit coverage; không tạo feature hiệu suất năng lượng.
def process_energy_efficiency():
    """Giữ hàm để rà soát sau; hiện không parse energy_efficiency."""
    assert 'energy_efficiency' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['energy_efficiency'])
    output_df = pd.DataFrame({
        'energy_efficiency_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'energy_efficiency_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['energy_efficiency'] = output_df
    return output_df.head(10)

process_energy_efficiency()

   energy_efficiency_present  energy_efficiency_text_length
0                      False                              1
1                      False                              1
2                      False                              1
3                      False                              1
4                      False                              1
5                      False                              1
6                      False                              1
7                      False                              1
8                      False                              1
9                      False                              1

In [123]:
# Chỉ kiểm tra audit coverage của energy_efficiency; chưa có feature phân tích.
check_processed_column('energy_efficiency')

                   output_column  non_null  null_pct  unique_non_null
0      energy_efficiency_present     17927       0.0                2
1  energy_efficiency_text_length     17927       0.0                2

   energy_efficiency_present  energy_efficiency_text_length
0                      False                              1
1                      False                              1
2                      False                              1
3                      False                              1
4                      False                              1
5                      False                              1
6                      False                              1
7                      False                              1
8                      False                              1
9                      False                              1

--- energy_efficiency_present top values ---

                           count
energy_efficiency_present
False                      17926
True                           1

--- energy_efficiency_text_length top values ---

                               count
energy_efficiency_text_length
1                              17926
16                                 1

       energy_efficiency_present  energy_efficiency_text_length
0                          False                              1
1                          False                              1
2                          False                              1
3                          False                              1
4                          False                              1
...                          ...                            ...
17922                      False                              1
17923                      False                              1
17924                      False                              1
17925                      False                              1
17926                      False                              1

[17927 rows x 2 columns]

#### `insulation_performance`

> **DEFERRED/SKIP:** Tạm bỏ qua xử lý insulation_performance. Giữ raw và helper audit coverage; không tạo feature phân tích hay đưa vào mart. Snapshot hiện chỉ có 1/17.927 dòng khác sentinel.

断熱性能, hiệu suất cách nhiệt. Snapshot hiện gần như không có dữ liệu thực.

In [124]:
# Kiểm tra raw column `insulation_performance` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'insulation_performance')

                insulation_performance
dtype                           object
rows                             17927
non_null                         17927
null_count                           0
null_pct                           0.0
sentinel_count                   17926
unique_non_null                      2

                        count
insulation_performance
-                       17926
6段階/7段階中                    1

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      17926
unique_non_null         2
dtype: object

In [125]:
# DEFERRED/SKIP PARSING: chỉ audit coverage; không tạo feature cách nhiệt.
def process_insulation_performance():
    """Giữ hàm để rà soát sau; hiện không parse insulation_performance."""
    assert 'insulation_performance' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['insulation_performance'])
    output_df = pd.DataFrame({
        'insulation_performance_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'insulation_performance_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['insulation_performance'] = output_df
    return output_df.head(10)

process_insulation_performance()

   insulation_performance_present  insulation_performance_text_length
0                           False                                   1
1                           False                                   1
2                           False                                   1
3                           False                                   1
4                           False                                   1
5                           False                                   1
6                           False                                   1
7                           False                                   1
8                           False                                   1
9                           False                                   1

In [126]:
# Chỉ kiểm tra audit coverage của insulation_performance; chưa có feature phân tích.
check_processed_column('insulation_performance')

                        output_column  non_null  null_pct  unique_non_null
0      insulation_performance_present     17927       0.0                2
1  insulation_performance_text_length     17927       0.0                2

   insulation_performance_present  insulation_performance_text_length
0                           False                                   1
1                           False                                   1
2                           False                                   1
3                           False                                   1
4                           False                                   1
5                           False                                   1
6                           False                                   1
7                           False                                   1
8                           False                                   1
9                           False                                   1

--- insulation_performance_present top values ---

                                count
insulation_performance_present
False                           17926
True                                1

--- insulation_performance_text_length top values ---

                                    count
insulation_performance_text_length
1                                   17926
8                                       1

       insulation_performance_present  insulation_performance_text_length
0                               False                                   1
1                               False                                   1
2                               False                                   1
3                               False                                   1
4                               False                                   1
...                               ...                                 ...
17922                           False                                   1
17923                           False                                   1
17924                           False                                   1
17925                           False                                   1
17926                           False                                   1

[17927 rows x 2 columns]

#### `estimated_utility_cost`

> **DEFERRED/SKIP:** Tạm bỏ qua xử lý estimated_utility_cost. Giữ raw và helper audit coverage; không đổi giá trị sang JPY và không đưa vào tổng chi phí. Snapshot hiện chỉ có 1/17.927 dòng khác sentinel.

目安光熱費, chi phí điện/nước/gas tham khảo. Snapshot hiện gần như không có dữ liệu thực.

In [127]:
# Kiểm tra raw column `estimated_utility_cost` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'estimated_utility_cost')

                estimated_utility_cost
dtype                           object
rows                             17927
non_null                         17927
null_count                           0
null_pct                           0.0
sentinel_count                   17926
unique_non_null                      2

                        count
estimated_utility_cost
-                       17926
約10.4万円/年                   1

dtype              object
rows                17927
non_null            17927
null_count              0
null_pct              0.0
sentinel_count      17926
unique_non_null         2
dtype: object

In [128]:
# DEFERRED/SKIP PARSING: chỉ audit coverage; không tạo JPY hay cộng vào tổng chi phí.
def process_estimated_utility_cost():
    """Giữ hàm để rà soát sau; hiện không parse estimated_utility_cost."""
    assert 'estimated_utility_cost' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['estimated_utility_cost'])
    output_df = pd.DataFrame({
        'estimated_utility_cost_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'estimated_utility_cost_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['estimated_utility_cost'] = output_df
    return output_df.head(10)

process_estimated_utility_cost()

   estimated_utility_cost_present  estimated_utility_cost_text_length
0                           False                                   1
1                           False                                   1
2                           False                                   1
3                           False                                   1
4                           False                                   1
5                           False                                   1
6                           False                                   1
7                           False                                   1
8                           False                                   1
9                           False                                   1

In [129]:
# Chỉ kiểm tra audit coverage của estimated_utility_cost; chưa có feature phân tích.
check_processed_column('estimated_utility_cost')

                        output_column  non_null  null_pct  unique_non_null
0      estimated_utility_cost_present     17927       0.0                2
1  estimated_utility_cost_text_length     17927       0.0                2

   estimated_utility_cost_present  estimated_utility_cost_text_length
0                           False                                   1
1                           False                                   1
2                           False                                   1
3                           False                                   1
4                           False                                   1
5                           False                                   1
6                           False                                   1
7                           False                                   1
8                           False                                   1
9                           False                                   1

--- estimated_utility_cost_present top values ---

                                count
estimated_utility_cost_present
False                           17926
True                                1

--- estimated_utility_cost_text_length top values ---

                                    count
estimated_utility_cost_text_length
1                                   17926
9                                       1

       estimated_utility_cost_present  estimated_utility_cost_text_length
0                               False                                   1
1                               False                                   1
2                               False                                   1
3                               False                                   1
4                               False                                   1
...                               ...                                 ...
17922                           False                                   1
17923                           False                                   1
17924                           False                                   1
17925                           False                                   1
17926                           False                                   1

[17927 rows x 2 columns]

### Nhóm: Free text cần giữ staging/audit

#### `remarks`

> **DEFERRED/SKIP:** Tạm bỏ qua xử lý remarks. Giữ nguyên raw và helper audit coverage; không tạo feature phân tích hay đưa ghi chú tự do vào mart.

備考, ghi chú tự do của listing. Có thể chứa nhiều thông tin phụ nhưng noise cao và không nên đưa vào mart wide nếu chưa có NLP/rule parse.

In [130]:
# Kiểm tra raw column `remarks` trước khi áp dụng rule.
inspect_column_values(analysis_raw, 'remarks')

                remarks
dtype            object
rows              17927
non_null          15958
null_count         1969
null_pct          10.98
sentinel_count        0
unique_non_null    5400

                                                                                                                          count
remarks
None                                                                                                                       1969
巡回管理                                                                                                                       1045
アンティホームなら仲介手数料無料です。物件の詳細や初期費用ついてはご遠慮なくご相談ください。また分割ローンやクレジットカード決済も可能です。ご案内の際は現地待ち合わせ、送迎サービスもございます。お気軽にお申し付けください。             410
アンティホームなら仲介手数料無料です。物件の詳細や初期費用ついてはご遠慮なくご相談ください。また分割ローンやクレジットカード決済も可能です。 ご案内の際は現地待ち合わせ、送迎サービスもございます。お気軽にお申し付けください。            377
ハウスモ江坂店では経験豊富なスタッフが在籍しており、大阪府内全域でお部屋探しが可能です。インターネットに掲載している物件はごく一部ですので是非お気軽にお問い合わせ下さいませ。各種クレジットカードも利用可能です。賃貸、売買、事務所、店舗...    242
ハウスモ不動産新大阪南店では経験豊富なスタッフが在籍しており、大阪府内全域でお部屋探しが可能です。インターネットに掲載している物件はごく一部ですので是非お気軽にお問い合わせ下さいませ。各種クレジットカードも利用可能です。賃貸、売買、事...    205
阪急電鉄宝塚線十三駅徒歩5分/巡回管理/『超便利機能★マルチファンクションライト付』訪れた人を奥へと誘うようにデザインされたエントランスは木目調とモザイクタイルの飾りがアクセントを加える住む人が誇らしくなる迎賓空間。                176
巡回管理/当物件ご案内の際、現地でのお待ち合わせ等も可能です。お気軽にお申し付け下さいませ。TEL:06-6195-4440                                                              174
短期解約違約金有 1ヵ月(1年未満)                                                                                                          162
原付3,300円、バイク5,500円 近隣駐車場有り 保証会社:信和CM保証                                                                                      140
[退去時費用 ハウスクリーニング代:38,500円※故意・過失等別途実費]部屋によってカラーパターンあり 保証会社:プレサンスギャランティ                                                       123
※短期契約違約金:1年未満での解約は家賃・共益費の1ヶ月分要 保証会社:日本セーフティ                                                                                 109
通勤管理                                                                                                                        105
オンライン内覧やWEB契約など、ご来店なしで契約ができます★関西圏のお部屋探しはRoom Heartsまで♪                                                                       96
☆お部屋探しでのお悩みは当店へ、ご相談くださいませ☆現地での待ち合わせ、主要駅までのお出迎えサービスなどもございます☆初期費用の相見積もりサービスも実施中☆日本最大級を誇るネットワークの情報量で、経験豊富なスタッフが一生懸命お応えいた...     94

dtype              object
rows                17927
non_null            15958
null_count           1969
null_pct            10.98
sentinel_count          0
unique_non_null      5400
dtype: object

In [131]:
# DEFERRED/SKIP PARSING: chỉ audit coverage; không tạo feature từ nội dung ghi chú.
def process_remarks():
    """Giữ hàm để rà soát sau; hiện không parse remarks."""
    assert 'remarks' in DEFERRED_PROCESSING_COLUMNS
    normalized = normalize_text_series(raw['remarks'])
    output_df = pd.DataFrame({
        'remarks_present': normalized.notna() & ~normalized.isin(NULL_SENTINELS),
        'remarks_text_length': normalized.str.len().astype('Int64'),
    })
    processed_outputs['remarks'] = output_df
    return output_df.head(10)

process_remarks()

   remarks_present  remarks_text_length
0             True                   69
1             True                   69
2             True                   69
3             True                   69
4             True                   69
5             True                   69
6             True                   69
7             True                   69
8             True                   69
9             True                   69

In [132]:
# Chỉ kiểm tra audit coverage của remarks; chưa có feature phân tích.
check_processed_column('remarks')

         output_column  non_null  null_pct  unique_non_null
0      remarks_present     17927      0.00                2
1  remarks_text_length     15958     10.98              238

   remarks_present  remarks_text_length
0             True                   69
1             True                   69
2             True                   69
3             True                   69
4             True                   69
5             True                   69
6             True                   69
7             True                   69
8             True                   69
9             True                   69

--- remarks_present top values ---

                 count
remarks_present
True             15958
False             1969

       remarks_present  remarks_text_length
0                 True                   69
1                 True                   69
2                 True                   69
3                 True                   69
4                 True                   69
...                ...                  ...
17922            False                 <NA>
17923            False                 <NA>
17924            False                 <NA>
17925            False                 <NA>
17926            False                 <NA>

[17927 rows x 2 columns]

## Bước 6 - Sanity checks cho rule quan trọng

Cell này thay thế cho test Python rời. Nếu một assert fail, dừng lại và sửa rule trước khi xuất CSV.

In [133]:
# Chỉ test parser active; các cột DEFERRED/SKIP không có sanity test ở đây.
assert parse_jpy_value('8.15万円') == 81_500
assert parse_jpy_value('８，０００円') == 8_000
assert parse_jpy_value('-', sentinel_as_zero=True) == 0
assert parse_month_value('1.1ヶ月') == 1.1
assert parse_month_value('0.55ヶ月') == 0.55
assert parse_month_value('１ヵ月') == 1.0
assert parse_month_value('不要') is None
assert parse_month_value('13.42万円') is None
assert parse_initial_cost_total('合計2.2万円(内訳:鍵交換代2.2万円)') == 22_000
assert parse_initial_cost_total('合計8.67万円(内訳:退去時清掃費52250円、鍵交換費16500円)') == 86_700
assert parse_initial_cost_total('鍵交換代2.2万円') is None
assert parse_layout('ワンルーム') == ('1R', 1, False)
assert parse_layout('1LDK') == ('1LDK', 1, False)
assert parse_layout('2SLDK') == ('2SLDK', 2, True)
assert parse_layout('1SDK') == ('1SDK', 1, True)
assert parse_layout('unknown') == (None, None, None)
layout_detail_example = parse_layout_detail('洋4.4 LDK10.8')
assert layout_detail_example[2:] == ('full', 0)
assert summarize_layout_detail_components(layout_detail_example[1])['kitchen_size_jo'] == 10.8
layout_detail_compound = parse_layout_detail('洋6.7 洋4.3 LD18.4K3.5 納戸 2.3')
assert layout_detail_compound[2:] == ('full', 0)
assert summarize_layout_detail_components(layout_detail_compound[1])['kitchen_type'] == 'LD+K'
layout_detail_range = parse_layout_detail('洋6.1 K2 ロフト 1.8-1.8')
assert layout_detail_range[2] == 'partial'
assert summarize_layout_detail_components(layout_detail_range[1])['loft_present'] is True
assert parse_layout_detail('-') == (None, [], 'missing', 0)
assert parse_area_m2('25.66m2') == 25.66
assert parse_area_m2('２５．６６㎡') == 25.66
assert parse_area_m2('25.66m²') == 25.66
assert parse_area_m2('-') is None
assert parse_area_m2('0m2') is None
assert parse_area_m2('25.66畳') is None
assert parse_building_age('新築') == 0
assert parse_building_age('築2年') == 2
assert parse_building_age('築99年以上') == 99
assert parse_building_age('築９９年以上') == 99
assert parse_building_age('-') is None
assert parse_building_age('99年') is None
assert parse_floor_range('1-3階') == (1, 3)
assert parse_floor_range('03階') == (3, 3)
assert parse_floor_range('2-3階') == (2, 3)
assert parse_floor_range('-') == (None, None)
assert parse_floor_range('3-1階') == (None, None)
assert parse_building_total_floors('平屋') == 1
assert parse_building_total_floors('3階/10階建') == 10
assert parse_building_total_floors('1-3階/地上3階建') == 3
assert parse_building_total_floors('8階/地下1地上12階建') == 12
assert parse_building_total_floors('3階建') == 3
assert parse_building_total_floors('-') is None
assert parse_building_total_floors('4階/3階建') is None
assert parse_total_units('168戸') == 168
assert parse_total_units('１戸') == 1
assert parse_total_units('-') is None
assert parse_total_units('0戸') is None
assert parse_total_units('168') is None
assert parse_year_month('2008年') == pd.Timestamp('2008-01-01')
assert parse_year_month('2026年7月') == pd.Timestamp('2026-07-01')
assert parse_year_month('２０２６年７月') == pd.Timestamp('2026-07-01')
assert pd.isna(parse_year_month('2026年13月'))
assert pd.isna(parse_year_month('-'))
assert parse_move_in('即') == ('immediate', None, None)
assert parse_move_in('相談') == ('consultation', None, None)
assert parse_move_in("'26年9月初旬") == ('scheduled', '2026-09', 'early')
assert parse_move_in("'26年9月中旬") == ('scheduled', '2026-09', 'middle')
assert parse_move_in("'26年9月下旬") == ('scheduled', '2026-09', 'late')
assert parse_contract('普通借家 2年') == ('ordinary', 2, 0)
assert parse_contract('定期借家 5年4ヶ月') == ('fixed_term', 5, 4)
assert parse_contract('普通借家 2ヶ月') == ('ordinary', 0, 2)
assert parse_contract('定期借家 西暦2086年9月まで') == (None, None, None)
assert parse_insurance('1.8万円2年') == (True, 18_000, 2)
assert parse_insurance('要') == (True, None, None)
assert parse_insurance('2万円') == (True, 20_000, None)
assert parse_insurance('１．８万円２年') == (True, 18_000, 2)
assert parse_insurance('-') == (None, None, None)
assert parse_insurance('不要') == (False, None, None)
assert parse_insurance('0万円2年') == (None, None, None)
assert parse_insurance('1万円0年') == (None, None, None)
assert parse_insurance('不明') == (None, None, None)
assert parse_parking('近隣200m22000円') == (True, 'nearby', 200, 22_000, None, None)
assert parse_parking('敷地内20000円/屋内駐') == (True, 'onsite', None, 20_000, '屋内駐', None)
assert parse_parking('付無料') == (True, 'unspecified', None, 0, None, None)
assert parse_parking('平置駐') == (True, 'unspecified', None, None, '平置駐', None)
assert parse_parking('駐2台可') == (True, 'unspecified', None, None, None, 2)
assert parse_parking('敷地内23000円/駐3台可') == (True, 'onsite', None, 23_000, None, 3)
assert parse_parking('付無料/駐2台可') == (True, 'unspecified', None, 0, None, 2)
assert parse_parking('敷地内22000円')[5] is None
assert parse_parking('駐4台可') == (None, None, None, None, None, None)
assert parse_parking('-') == (None, None, None, None, None, None)
row = pd.Series({'task_id': 1, 'batch_id': 1, 'suumo_property_code': '1', 'station_access': '阪急宝塚線/十三駅 バス8分 (バス停)加島中 歩3分'})
station_records, station_failures = _station_rows_for_record(row)
assert station_failures == 0
assert station_records[0]['station_name'] == '十三'
assert station_records[0]['total_travel_minutes'] == 11
print('Sanity checks passed')

Sanity checks passed

## Bước 7 - Ghép kết quả từng cột và chọn listing hiện tại

Chỉ ghép các output đã xử lý; các cột DEFERRED/SKIP giữ ở raw/history, không tạo feature cho current mart. History giữ đủ số dòng và data_hash. Current chọn bản hợp lệ mới nhất theo suumo_property_code, parsed_at và task_id. Station và layout spaces giữ ở bảng một-nhiều riêng.

In [134]:
# Ghép kết quả đã chạy ở từng section; thiếu section active thì dừng rõ ràng.
active_source_columns = [
    column for column in ordered_analysis_columns
    if column not in DEFERRED_PROCESSING_COLUMNS and column != 'data_hash'
]
missing_outputs = sorted(set(active_source_columns) - set(processed_outputs))
if missing_outputs:
    raise RuntimeError(f'Chưa chạy các section active: {missing_outputs}')

cleaned = raw.copy()
derived_columns = []
for source_column in active_source_columns:
    output_df = processed_outputs[source_column]
    if len(output_df) != len(raw) or not output_df.index.equals(raw.index):
        raise ValueError(f'Index/row count không khớp: {source_column}')
    if output_df.columns.has_duplicates:
        raise ValueError(f'Output trùng tên cột trong {source_column}')
    for output_column in output_df.columns:
        if output_column in cleaned.columns and output_column != source_column:
            raise ValueError(f'Output ghi đè raw column khác: {output_column}')
        cleaned[output_column] = output_df[output_column]
        if output_column not in raw.columns:
            derived_columns.append(output_column)

if cleaned['task_id'].isna().any() or cleaned['task_id'].duplicated().any():
    raise ValueError('task_id phải có giá trị và duy nhất trong history')
if cleaned['data_hash'].isna().any():
    raise ValueError('data_hash của raw không được mất trong clean history')

cleaned['parsed_at_utc'] = pd.to_datetime(
    cleaned['parsed_at'], format='mixed', errors='coerce', utc=True
)
cleaned['base_monthly_cost_jpy'] = (
    cleaned['rent_jpy'] + cleaned['management_fee_jpy']
).astype('Int64')
area_m2 = cleaned['exclusive_area_m2'].astype('Float64')
cleaned['rent_per_m2_jpy'] = (
    cleaned['rent_jpy'].astype('Float64') / area_m2.where(area_m2 > 0)
).astype('Float64')

# Chỉ flag lỗi kiểm chứng được từ các cột active; không tự đặt ngưỡng outlier.
cleaned['flag_missing_core'] = cleaned[['rent_jpy', 'exclusive_area_m2']].isna().any(axis=1).astype('boolean')
cleaned['flag_floor_exceeds_building'] = (
    cleaned['floor_max'] > cleaned['building_total_floors']
).fillna(False).astype('boolean')
cleaned['flag_station_parse_failure'] = (
    cleaned['station_parse_failure_count'].fillna(0) > 0
).astype('boolean')
cleaned['flag_layout_detail_parse_failure'] = (
    cleaned['layout_detail_parse_failure_count'].fillna(0) > 0
).astype('boolean')
quality_flag_columns = [
    'flag_missing_core', 'flag_floor_exceeds_building',
    'flag_station_parse_failure', 'flag_layout_detail_parse_failure',
]
cleaned['quality_issue_count'] = cleaned[quality_flag_columns].astype('Int64').sum(axis=1).astype('Int64')

eligible = cleaned['is_valid'].eq(True).fillna(False) & cleaned['suumo_property_code'].notna()
current_full = (
    cleaned.loc[eligible]
    .sort_values(['suumo_property_code', 'parsed_at_utc', 'task_id'], kind='stable', na_position='first')
    .drop_duplicates('suumo_property_code', keep='last')
    .sort_values('task_id', kind='stable')
)
current_columns = list(dict.fromkeys([
    'task_id', 'batch_id', 'source_id', 'suumo_property_code', 'data_hash',
    'parsed_at', 'parsed_at_utc',
    *(output_column for source_column in active_source_columns
      for output_column in processed_outputs[source_column].columns),
    'base_monthly_cost_jpy', 'rent_per_m2_jpy',
    *quality_flag_columns, 'quality_issue_count',
]))
current = current_full[current_columns].reset_index(drop=True)

# Bảng station một-nhiều từ cùng parser dùng ở section station_access.
station_columns = [
    'task_id', 'batch_id', 'suumo_property_code', 'access_order',
    'station_line', 'station_name', 'access_mode', 'total_travel_minutes',
]
station_rows = []
station_failures = 0
for _, record in raw[['task_id', 'batch_id', 'suumo_property_code', 'station_access']].iterrows():
    record_rows, failures = _station_rows_for_record(record)
    station_rows.extend(record_rows)
    station_failures += failures
stations = pd.DataFrame(station_rows, columns=station_columns)
for column in ['task_id', 'batch_id', 'access_order', 'total_travel_minutes']:
    stations[column] = pd.array(stations[column], dtype='Int64')
current_task_ids = set(current['task_id'].dropna().astype(int))
current_stations = stations.loc[stations['task_id'].isin(current_task_ids)].copy()
layout_spaces_history = layout_spaces.copy()
layout_spaces_current = layout_spaces_history.loc[
    layout_spaces_history['task_id'].isin(current_task_ids)
].copy()

report = {
    'raw_rows': len(raw),
    'clean_history_rows': len(cleaned),
    'current_listing_rows': len(current),
    'raw_columns': len(raw.columns),
    'clean_history_columns': len(cleaned.columns),
    'current_columns': len(current.columns),
    'deferred_columns': sorted(DEFERRED_PROCESSING_COLUMNS),
    'active_source_columns': active_source_columns,
    'derived_non_null_counts': {
        column: int(cleaned[column].notna().sum()) for column in derived_columns
    },
    'quality_flag_counts': {
        column: int(cleaned[column].sum()) for column in quality_flag_columns
    },
    'station_rows': len(stations),
    'station_parse_failures': station_failures,
    'layout_space_rows': len(layout_spaces_history),
}

pd.DataFrame({
    'dataset': ['raw history', 'clean history', 'current listings', 'station history',
                'current stations', 'layout spaces history', 'current layout spaces'],
    'rows': [len(raw), len(cleaned), len(current), len(stations),
             len(current_stations), len(layout_spaces_history), len(layout_spaces_current)],
    'columns': [len(raw.columns), len(cleaned.columns), len(current.columns),
                len(stations.columns), len(current_stations.columns),
                len(layout_spaces_history.columns), len(layout_spaces_current.columns)],
})

                 dataset   rows  columns
0            raw history  17927       57
1          clean history  17927      134
2       current listings  17380       84
3        station history  53044        8
4       current stations  51415        8
5  layout spaces history  28764        8
6  current layout spaces  27819        8

## Bước 8 - Kiểm tra chất lượng output active

Chỉ xem parse failures và các flag của cột đã xử lý. Các cột DEFERRED/SKIP đã được ghi chú ở section riêng, không đi vào test, coverage hay mart.

In [135]:
parse_failure_counts = pd.Series({
    'station_access_lines': int(cleaned['station_parse_failure_count'].sum()),
    'layout_detail_tokens': int(cleaned['layout_detail_parse_failure_count'].sum()),
}, name='count')
display(parse_failure_counts.to_frame())
display(pd.Series(report['quality_flag_counts'], name='count').to_frame())

active_sentinel_counts = pd.Series({
    column: int(normalize_text_series(raw[column]).isin(NULL_SENTINELS).sum())
    for column in active_source_columns
}, name='sentinel_count').sort_values(ascending=False)
display(active_sentinel_counts.head(25).to_frame())

                      count
station_access_lines      0
layout_detail_tokens     29

                                  count
flag_missing_core                     0
flag_floor_exceeds_building           0
flag_station_parse_failure            0
flag_layout_detail_parse_failure     29

                             sentinel_count
depreciation_text                     17921
guarantee_deposit_text                17910
deposit_text                          16129
key_money_text                         8485
total_units                            8283
parking                                6991
direction                              1926
layout_detail                          1754
insurance                              1696
management_fee_text                     966
shop_property_code                      668
floor_text                               13
station_access                            1
information_updated_at_text               0
structure                                 0
building_type                             0
source_id                                 0
building_floors                           0
built_at_text                             0
building_age_text                         0
exclusive_area_text                       0
other_initial_costs                       0
layout                                    0
move_in                                   0
brokerage_fee                             0

In [136]:
safe_clean_columns = [
    'task_id', 'suumo_property_code', 'data_hash', 'parsed_at_utc',
    'rent_jpy', 'management_fee_jpy', 'base_monthly_cost_jpy',
    'deposit_jpy', 'key_money_jpy', 'exclusive_area_m2', 'rent_per_m2_jpy',
    'layout_normalized', 'building_age_years', 'floor_min', 'floor_max',
    'building_total_floors', 'direction_clean', 'building_type_clean',
    'primary_station_name', 'primary_total_travel_minutes',
    'move_in_status', 'parking_location', 'parking_fee_jpy',
    'quality_issue_count',
]
current[safe_clean_columns].head(20)

,task_id,suumo_property_code,data_hash,parsed_at_utc,rent_jpy,management_fee_jpy,base_monthly_cost_jpy,deposit_jpy,key_money_jpy,exclusive_area_m2,rent_per_m2_jpy,layout_normalized,building_age_years,floor_min,floor_max,building_total_floors,direction_clean,building_type_clean,primary_station_name,primary_total_travel_minutes,move_in_status,parking_location,parking_fee_jpy,quality_issue_count
0,3625,100511946230,2ab2daed3123f001de95ffaf224f67d1799f312ffc614cabc8a74beeb822acbc,2026-08-04 00:16:39.847077+00:00,36000,4000,40000,0,0,14.0,2571.428571,1R,42,1,1,5,北,マンション,新大阪,14,consultation,nearby,25300,0
1,3626,100515701227,5509e82b538bb13bde43c2c514fdfb664dfd28bc9265a439d894434bca9a7231,2026-08-04 00:16:39.881544+00:00,65000,4000,69000,0,0,21.0,3095.238095,1SK,11,1,1,2,西,アパート,三国,8,scheduled,nearby,16500,0
2,3627,100515553892,4e5a62463de7da864a1f841289af1e94f368d02d4be009f2b63bec3d46e6c77f,2026-08-04 00:16:39.924047+00:00,65000,4000,69000,0,0,21.0,3095.238095,1K,11,1,1,2,西,アパート,三国,8,scheduled,<NA>,<NA>,0
3,3628,100474048599,be80ca6c2faa04d9cc679bed077d36365589ce96d1feb30cb70ebb514cf215e3,2026-08-04 00:16:39.945794+00:00,62000,4000,66000,0,62000,29.34,2113.156101,1LDK,3,1,1,3,西,アパート,神崎川,8,scheduled,<NA>,<NA>,0
4,3629,100509979159,641fbc1aeb1f5615ff29730f3d6c59de9ee8e912bb257fb0da7625d836c1e716,2026-08-04 00:16:39.979544+00:00,72000,5000,77000,0,72000,33.14,2172.601086,1LDK,7,1,1,3,<NA>,アパート,加島,9,consultation,nearby,19800,0
5,3630,100518267173,36172c0aa8b8c4b25b7ac0401ccacfa380530208e9e5bd0d3575088e013ef14a,2026-08-04 00:16:40.010300+00:00,70000,10000,80000,0,0,31.93,2192.295647,1LDK,10,3,3,3,南,アパート,加島,5,immediate,nearby,18000,0
6,3631,100503044072,cd249f4d64cfb4046173b653e8b6122b60fb7866f09c42c3c6fc7d2e70ebe7c0,2026-08-04 00:16:40.045497+00:00,70000,10000,80000,0,0,31.93,2192.295647,1LDK,10,2,2,3,南,アパート,加島,5,immediate,nearby,27500,0
7,3632,100515913598,83aeade7c26738e162f71a4681a577783cb2e3514b72bbe0420b8be691411e57,2026-08-04 00:16:40.078006+00:00,70000,10000,80000,0,0,31.93,2192.295647,1LDK,10,2,2,3,南,アパート,加島,5,consultation,<NA>,<NA>,0
8,3633,100513373218,2a14a894766e7259b73432824f368f80c0c6bc33babf02325153272262466807,2026-08-04 00:16:40.111990+00:00,73000,10000,83000,0,0,31.93,2286.251174,1LDK,10,2,2,3,南,アパート,加島,5,immediate,nearby,22000,0
9,3634,100513373228,10d640828f11e75c0a6f039e84a2b944415e70041d0bcebb416a8a3ad8277846,2026-08-04 00:16:40.145212+00:00,73000,10000,83000,0,0,31.93,2286.251174,1LDK,10,2,2,3,南,アパート,加島,5,immediate,nearby,22000,0
10,3635,100513394104,e781b7d00c4a3de58bc5bb765f65f5dac92f06655c707f7d4d2b76683f3624bc,2026-08-04 00:16:40.176122+00:00,73000,10000,83000,0,0,31.93,2286.251174,1LDK,10,3,3,3,南,アパート,加島,7,immediate,<NA>,<NA>,0
11,3636,100494909378,d80abd077746985e7d8883583ef7312b4008590e2d2863a866d4d923629c4d38,2026-08-04 00:16:40.204034+00:00,70000,10000,80000,0,0,31.93,2192.295647,1LDK,10,2,2,3,南,アパート,加島,5,immediate,<NA>,<NA>,0
12,3637,100497391713,b9be7aacc8476a37380f65e4844d10e20eb0a46fc60533787459f253adef8e8d,2026-08-04 00:16:40.285113+00:00,73000,10000,83000,0,0,31.93,2286.251174,1LDK,10,3,3,3,南,アパート,加島,5,immediate,nearby,16500,0
13,3638,100514180883,ada7f6268f00707892dac6a0ab41ec467320b8b13d93245b99cedc75a1527508,2026-08-04 00:16:40.320674+00:00,73000,10000,83000,0,0,31.93,2286.251174,1LDK,10,2,2,3,南,アパート,加島,5,immediate,nearby,14300,0
14,3639,100517913996,1654555b2157f7795c72a9e4df07fe66740826e14d817451156c88b17e68f3c4,2026-08-04 00:16:40.356598+00:00,76000,13000,89000,0,100000,30.73,2473.15327,1LDK,8,6,6,8,南,マンション,十三,9,scheduled,nearby,17000,0
15,3640,100506945567,0ef90cacb652f4a32830f8e674cf6dbd14c5a560d9fb858e4bfa1e27f4359158,2026-08-04 00:16:40.390893+00:00,63000,3000,66000,0,0,30.39,2073.050346,1LDK,7,1,1,3,西,アパート,加島,9,immediate,<NA>,<NA>,0
16,3641,100511838155,34ebfea60b5dfa3dec3524922e8dd23b4370b9966e2eb7490a15bbcd276f461e,2026-08-04 00:16:40.421561+00:00,86000,4000,90000,0,86000,31.68,2714.646465,1LDK,7,2,2,3,北,アパート,三国,6,immediate,nearby,18700,0
17,3642,100507701244,bc37025d030d38b15a46d9aa850622e5f0ee69b96ec8c8bf33285843273d1156,2026-08-04 00:16:40.454019+00:00,72000,5000,77000,0,72000,34.63,2079.122148,1LDK,7,2,2,3,西,アパート,加島,8,immediate,nearby,14300,0
18,3643,100509917286,7d9e006181efc424263b07d725b8170cb7f857d27ef37a78508de92c395982aa,2026-08-04 00:16:40.526068+00:00,76000,7000,83000,0,0,26.01,2921.953095,1DK,20,6,6,13,東,マンション,東三国,5,scheduled,<NA>,<NA>,0
19,3644,100518426565,13db6c9d9ec55f886da8b1101a64ca9e2bc483ecf219235aadc22cf5d69a5a22,2026-08-04 00:16:40.559523+00:00,86000,7000,93000,0,0,30.3,2838.283828,1LDK,20,12,12,13,東,マンション,東三国,3,immediate,onsite,27500,0

## Bước 9 - EDA sau cleaning

Xem phân phối và coverage của các feature active trên current listings. Không đưa cột DEFERRED/SKIP vào các bảng này.

In [137]:
numeric_columns = [
    'rent_jpy', 'management_fee_jpy', 'base_monthly_cost_jpy',
    'deposit_jpy', 'key_money_jpy', 'guarantee_deposit_jpy',
    'depreciation_jpy', 'brokerage_fee_estimated_jpy',
    'other_initial_costs_total_jpy', 'exclusive_area_m2',
    'rent_per_m2_jpy', 'building_age_years', 'building_total_floors',
    'total_units_count', 'primary_total_travel_minutes',
    'insurance_jpy', 'parking_fee_jpy',
]
numeric = current[numeric_columns].apply(pd.to_numeric, errors='coerce')
numeric.describe(percentiles=[.01, .05, .25, .5, .75, .95, .99]).T

,count,mean,std,min,1%,5%,25%,50%,75%,95%,99%,max
rent_jpy,17380.0,89833.360184,40283.749803,19000.0,33000.0,44500.0,68000.0,79000.0,110000.0,157000.0,210000.0,950000.0
management_fee_jpy,17380.0,8595.881703,4441.567679,0.0,0.0,0.0,6500.0,8000.0,10000.0,15000.0,20000.0,100000.0
base_monthly_cost_jpy,17380.0,98429.241887,42531.088766,24000.0,38000.0,50000.0,75000.0,87000.0,119000.0,169500.0,229210.0,995000.0
deposit_jpy,17380.0,11868.993096,45093.795722,0.0,0.0,0.0,0.0,0.0,0.0,100000.0,198000.0,950000.0
key_money_jpy,17380.0,63450.759494,87128.372716,0.0,0.0,0.0,0.0,53000.0,100000.0,200000.0,400000.0,1200000.0
guarantee_deposit_jpy,17380.0,96.346375,6712.705343,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,858000.0
depreciation_jpy,17380.0,44.706559,3466.494895,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,429000.0
brokerage_fee_estimated_jpy,1499.0,15029.156104,40933.69309,0.0,0.0,0.0,0.0,0.0,0.0,131010.0,167200.0,341000.0
other_initial_costs_total_jpy,9196.0,33295.813397,22174.504975,100.0,3300.0,11000.0,22000.0,27500.0,38500.0,77000.0,116000.0,271000.0
exclusive_area_m2,17380.0,30.355796,12.604931,10.75,15.0,19.87,22.33,25.67,34.71,50.32,79.38,311.44
rent_per_m2_jpy,17380.0,2994.779843,746.740169,771.589673,1425.957197,1763.66843,2546.628407,3142.857143,3459.291001,3893.80531,4155.03876,35878.564857
building_age_years,17380.0,13.113464,15.030227,0.0,0.0,0.0,0.0,7.0,21.0,44.0,53.0,99.0
building_total_floors,17380.0,10.605754,4.502965,1.0,2.0,3.0,8.0,10.0,14.0,15.0,22.0,72.0
total_units_count,9224.0,95.894406,79.274158,1.0,6.0,12.0,39.0,72.0,131.0,224.0,362.0,745.0
primary_total_travel_minutes,17379.0,6.990161,3.54014,1.0,1.0,2.0,5.0,7.0,9.0,13.0,16.0,74.0
insurance_jpy,8345.0,17759.580587,4167.100183,700.0,10000.0,10000.0,16000.0,18000.0,20000.0,24000.0,26000.0,110000.0
parking_fee_jpy,10257.0,23233.061811,6147.42614,0.0,10000.0,16000.0,19800.0,22000.0,27500.0,33000.0,36300.0,66000.0

In [138]:
category_columns = [
    'layout_normalized', 'layout_detail_parse_status', 'direction_clean',
    'building_type_clean', 'structure_clean', 'transaction_type_clean',
    'move_in_status', 'contract_type', 'parking_location',
    'parking_detail', 'insurance_required',
]
for column in category_columns:
    print(f'\n--- {column} ---')
    display(current[column].value_counts(dropna=False).head(15).to_frame('count'))

--- layout_normalized ---

                   count
layout_normalized
1K                  7704
1LDK                4666
1DK                 1725
1R                  1463
2LDK                 812
1SLDK                293
2DK                  272
3LDK                 212
2K                   131
3DK                   39
4LDK                  20
2SLDK                 15
4DK                   10
4K                     6
1SK                    4

--- layout_detail_parse_status ---

                            count
layout_detail_parse_status
full                        15627
missing                      1725
partial                        28

--- direction_clean ---

                 count
direction_clean
南                 4860
西                 3337
東                 3092
北                 1999
<NA>              1884
南東                 911
北西                 550
南西                 489
北東                 258

--- building_type_clean ---

                     count
building_type_clean
マンション                16533
アパート                   734
一戸建て                    77
テラス・タウンハウス              26
その他                     10

--- structure_clean ---

                 count
structure_clean
鉄筋コン             13689
鉄骨                1773
鉄骨鉄筋              1094
木造                 591
軽量鉄骨               120
気泡コン                60
その他                 32
プレコン                17
ブロック                 4

--- transaction_type_clean ---

                        count
transaction_type_clean
仲介                      17251
貸主                         99
代理                         30

--- move_in_status ---

                count
move_in_status
immediate       10461
scheduled        3839
consultation     3079
unknown             1

--- contract_type ---

               count
contract_type
<NA>            9608
ordinary        7449
fixed_term       323

--- parking_location ---

                  count
parking_location
<NA>               6850
onsite             6104
nearby             4070
unspecified         356

--- parking_detail ---

                count
parking_detail
<NA>            15755
平置駐               799
屋内駐               784
平置屋根付駐             21
屋根付駐               11
機械式駐                7
リモコンシャッタ付駐          2
シャッタ付屋内駐            1

--- insurance_required ---

                    count
insurance_required
True                15728
<NA>                 1652

In [139]:
coverage_columns = [
    'rent_jpy', 'management_fee_jpy', 'deposit_jpy', 'key_money_jpy',
    'exclusive_area_m2', 'building_age_years', 'built_at',
    'building_total_floors', 'total_units_count',
    'primary_station_name', 'primary_total_travel_minutes',
    'contract_type', 'insurance_jpy', 'parking_fee_jpy',
    'other_initial_costs_total_jpy', 'direction_clean',
]
coverage = pd.DataFrame({
    'non_null': current[coverage_columns].notna().sum(),
    'coverage_pct': (current[coverage_columns].notna().mean() * 100).round(2),
}).sort_values('coverage_pct')
coverage

                               non_null  coverage_pct
contract_type                      7772         44.72
insurance_jpy                      8345         48.01
other_initial_costs_total_jpy      9196         52.91
total_units_count                  9224         53.07
parking_fee_jpy                   10257         59.02
direction_clean                   15496         89.16
primary_station_name              17379         99.99
primary_total_travel_minutes      17379         99.99
rent_jpy                          17380        100.00
management_fee_jpy                17380        100.00
deposit_jpy                       17380        100.00
key_money_jpy                     17380        100.00
exclusive_area_m2                 17380        100.00
building_age_years                17380        100.00
built_at                          17380        100.00
building_total_floors             17380        100.00

In [140]:
review_columns = [
    'task_id', 'suumo_property_code', 'rent_jpy', 'exclusive_area_m2',
    'rent_per_m2_jpy', 'layout_normalized', 'building_age_years',
    'building_type_clean', 'primary_total_travel_minutes',
    *quality_flag_columns, 'quality_issue_count',
]
review_candidates = (
    current.loc[current['quality_issue_count'] > 0, review_columns]
    .sort_values(['quality_issue_count', 'rent_per_m2_jpy'], ascending=[False, False])
)
review_candidates.head(100)

,task_id,suumo_property_code,rent_jpy,exclusive_area_m2,rent_per_m2_jpy,layout_normalized,building_age_years,building_type_clean,primary_total_travel_minutes,flag_missing_core,flag_floor_exceeds_building,flag_station_parse_failure,flag_layout_detail_parse_failure,quality_issue_count
4376,8480,100506383505,250000,62.57,3995.525012,2LDK,0,マンション,5,False,False,False,True,1
9065,13222,100515424034,250000,62.57,3995.525012,2LDK,1,マンション,5,False,False,False,True,1
15395,19633,100488414591,137000,34.4,3982.55814,1LDK,2,マンション,12,False,False,False,True,1
15172,19410,100430558545,110000,29.65,3709.94941,1LDK,2,マンション,10,False,False,False,True,1
4881,8996,100511079938,90000,24.43,3683.995088,1DK,4,マンション,5,False,False,False,True,1
10888,15075,100520759339,90000,24.43,3683.995088,1DK,4,マンション,5,False,False,False,True,1
14266,18504,100506929709,111000,30.8,3603.896104,1LDK,3,マンション,5,False,False,False,True,1
14777,19015,100497740329,76200,21.46,3550.792171,1K,4,マンション,2,False,False,False,True,1
1698,5445,100515017695,150000,44.55,3367.003367,1LDK,51,マンション,5,False,False,False,True,1
2165,5937,100514663812,137000,40.92,3347.99609,1LDK,2,マンション,12,False,False,False,True,1
10958,15145,100515693517,85000,25.65,3313.840156,1K,7,マンション,7,False,False,False,True,1
9452,13618,100507103104,105000,32.5,3230.769231,1LDK,0,マンション,15,False,False,False,True,1
12217,16412,100519000746,82000,25.66,3195.63523,1K,0,マンション,12,False,False,False,True,1
9450,13616,100507103698,103500,32.5,3184.615385,1LDK,0,マンション,15,False,False,False,True,1
4918,9033,100505529536,59000,18.9,3121.693122,1K,21,マンション,5,False,False,False,True,1
11115,15305,100496926362,107000,34.32,3117.715618,1LDK,9,マンション,10,False,False,False,True,1
11684,15876,100513829757,55000,18.9,2910.05291,1K,21,マンション,5,False,False,False,True,1
345,4051,100514672262,70000,24.1,2904.564315,1K,13,マンション,6,False,False,False,True,1
11129,15319,100519443635,53000,19.02,2786.540484,1K,25,マンション,4,False,False,False,True,1
15007,19245,100460754574,65000,25.21,2578.341928,1K,23,マンション,3,False,False,False,True,1
4364,8468,100513299373,200000,78.84,2536.783359,3LDK,14,マンション,8,False,False,False,True,1
3488,7465,100443150503,162000,68.22,2374.670185,3LDK,23,マンション,7,False,False,False,True,1
4477,8587,100510134188,260000,111.16,2338.970853,1LDK,3,テラス・タウンハウス,4,False,False,False,True,1
13680,17918,100360692874,250000,111.63,2239.541342,1LDK,3,テラス・タウンハウス,5,False,False,False,True,1
7022,11161,100275922018,100000,45.57,2194.426158,2LDK,38,マンション,13,False,False,False,True,1
4556,8668,100513661817,39000,20.0,1950.0,1K,39,マンション,12,False,False,False,True,1
15729,19967,100520982439,72000,37.74,1907.790143,1LDK,7,アパート,8,False,False,False,True,1
3950,8013,100504159102,65000,45.22,1437.417072,1LDK,50,マンション,8,False,False,False,True,1

## Bước 10 - Xuất dữ liệu mới

Chỉ chạy sau khi đã xem các bảng kiểm tra. Cell này ghi lại clean history, current mart, hai bảng station, hai bảng layout spaces và report JSON. File raw của notebook 01 không bị ghi đè.

In [141]:
LAYOUT_SPACES_PATH = DATA_DIR / 'suumo_layout_spaces.csv'
CURRENT_LAYOUT_SPACES_PATH = DATA_DIR / 'suumo_layout_spaces_current.csv'
output_paths = [
    CLEAN_PATH, CURRENT_PATH, STATION_PATH, CURRENT_STATION_PATH,
    LAYOUT_SPACES_PATH, CURRENT_LAYOUT_SPACES_PATH, REPORT_PATH,
]
if RAW_PATH.resolve() in {path.resolve() for path in output_paths}:
    raise ValueError('Output path không được trùng raw CSV của notebook 01')
for path in output_paths:
    path.parent.mkdir(parents=True, exist_ok=True)

cleaned.to_csv(CLEAN_PATH, index=False, encoding='utf-8-sig')
current.to_csv(CURRENT_PATH, index=False, encoding='utf-8-sig')
stations.to_csv(STATION_PATH, index=False, encoding='utf-8-sig')
current_stations.to_csv(CURRENT_STATION_PATH, index=False, encoding='utf-8-sig')
layout_spaces_history.to_csv(LAYOUT_SPACES_PATH, index=False, encoding='utf-8-sig')
layout_spaces_current.to_csv(CURRENT_LAYOUT_SPACES_PATH, index=False, encoding='utf-8-sig')

report['outputs'] = {
    'raw_history': str(RAW_PATH.resolve()),
    'clean_history': str(CLEAN_PATH.resolve()),
    'current_listings': str(CURRENT_PATH.resolve()),
    'station_access': str(STATION_PATH.resolve()),
    'current_station_access': str(CURRENT_STATION_PATH.resolve()),
    'layout_spaces': str(LAYOUT_SPACES_PATH.resolve()),
    'current_layout_spaces': str(CURRENT_LAYOUT_SPACES_PATH.resolve()),
}
REPORT_PATH.write_text(
    json.dumps(report, ensure_ascii=False, indent=2, default=str) + '\n',
    encoding='utf-8',
)

for label, frame, path in [
    ('Clean history', cleaned, CLEAN_PATH),
    ('Current listings', current, CURRENT_PATH),
    ('Station history', stations, STATION_PATH),
    ('Current stations', current_stations, CURRENT_STATION_PATH),
    ('Layout spaces history', layout_spaces_history, LAYOUT_SPACES_PATH),
    ('Current layout spaces', layout_spaces_current, CURRENT_LAYOUT_SPACES_PATH),
]:
    print(f'{label}: {len(frame):,} rows x {len(frame.columns)} columns -> {path.name}')
print(f'Raw history không đổi: {RAW_PATH.name}')
print(f'Report: {REPORT_PATH.name}')

Clean history: 17,927 rows x 134 columns -> suumo_parser_records_clean.csv
Current listings: 17,380 rows x 84 columns -> suumo_rentals_current.csv
Station history: 53,044 rows x 8 columns -> suumo_station_access.csv
Current stations: 51,415 rows x 8 columns -> suumo_station_access_current.csv
Layout spaces history: 28,764 rows x 8 columns -> suumo_layout_spaces.csv
Current layout spaces: 27,819 rows x 8 columns -> suumo_layout_spaces_current.csv
Raw history không đổi: suumo_parser_records_raw.csv
Report: suumo_clean_report.json

## Các file dữ liệu sau khi chạy notebook

Tất cả file dưới đây nằm trong thư mục notebook/data. Cell xuất dữ liệu ở Bước 10 tạo hoặc cập nhật sáu CSV đầu ra và một báo cáo JSON; không ghi đè file raw của notebook 01.

| File | Vai trò và mức dữ liệu | Nội dung / khi nào dùng |
| --- | --- | --- |
| suumo_parser_records_raw.csv | Đầu vào; một dòng cho mỗi bản ghi crawl (task_id) | Dữ liệu gốc do notebook 01 tạo, gồm các cột raw và data_hash. Giữ nguyên để kiểm tra nguồn và chạy lại quy tắc xử lý. |
| suumo_parser_records_eda.csv | Đầu vào dự phòng (legacy), nếu có | Chỉ được dùng khi không tìm thấy raw CSV; notebook sẽ sao chép thành suumo_parser_records_raw.csv. Không phải đầu ra phân tích của notebook này. |
| suumo_parser_records_clean.csv | Đầu ra lịch sử; một dòng cho mỗi task_id | Giữ toàn bộ cột raw, kể cả data_hash và các cột tạm hoãn xử lý, rồi thêm các cột đã chuẩn hóa, chỉ số và cờ chất lượng. Dùng để phân tích thay đổi theo các lần crawl hoặc kiểm tra lại giá trị gốc. |
| suumo_rentals_current.csv | Đầu ra hiện hành; tối đa một dòng cho mỗi suumo_property_code | Chọn bản ghi is_valid mới nhất theo parsed_at_utc (nếu trùng thì theo task_id). Gồm khóa, data_hash và feature đã xử lý đang active; dùng cho phân tích danh sách căn tại thời điểm gần nhất. Không mang các feature DEFERRED/SKIP. |
| suumo_station_access.csv | Đầu ra chi tiết lịch sử; một dòng cho mỗi tuyến/ga được parse trong một task_id | Có thứ tự tuyến, tên tuyến/ga, cách đi và tổng phút di chuyển. Một task_id có thể có nhiều dòng; ghép với clean history bằng task_id. |
| suumo_station_access_current.csv | Đầu ra chi tiết hiện hành; một dòng cho mỗi tuyến/ga của task_id hiện hành | Chỉ giữ các tuyến/ga thuộc những bản ghi đã chọn trong suumo_rentals_current.csv; ghép bằng task_id, quan hệ một-nhiều. |
| suumo_layout_spaces.csv | Đầu ra chi tiết lịch sử; một dòng cho mỗi thành phần phòng của layout_detail trong một task_id | Lưu thứ tự phòng, nhãn/loại phòng, diện tích theo 畳 và token gốc; ghép với clean history bằng task_id. |
| suumo_layout_spaces_current.csv | Đầu ra chi tiết hiện hành; một dòng cho mỗi thành phần phòng của task_id hiện hành | Chỉ giữ chi tiết layout của các bản ghi trong suumo_rentals_current.csv; ghép bằng task_id, quan hệ một-nhiều. |
| suumo_clean_report.json | Đầu ra kiểm tra, không phải bảng căn hộ | Ghi số dòng/cột, danh sách cột active/tạm hoãn, số giá trị derived không null, số cờ chất lượng, lỗi parse ga và đường dẫn file đầu ra. |

Để phân tích một dòng mỗi căn, bắt đầu từ suumo_rentals_current.csv. Nếu cần toàn bộ lịch sử, dùng suumo_parser_records_clean.csv. Khi ghép thêm station hoặc layout, dùng đúng cặp history/current và khóa task_id; mỗi bảng chi tiết có thể làm tăng số dòng sau khi ghép. Các cột được đánh dấu DEFERRED/SKIP chỉ được giữ ở dạng raw trong file lịch sử, chưa tạo feature phân tích riêng. Khi quy tắc ổn định, có thể chuyển phần xử lý active sang dbt staging/intermediate models.